Halide: Halide::Internal::StubOutputBufferBase Class Reference
Halide::Internal::StubOutputBufferBase Class Reference
#include <Generator.h>
Inherited by Halide::Internal::StubOutputBuffer< T >.
Public Member Functions
Realization realize (std::vector< int32_t > sizes)
template<typename... Args>
Realization realize (Args &&...args)
template<typename Dst >
void realize (Dst dst)
Protected Member Functions
void check_scheduled (const char *m) const
Target get_target () const
StubOutputBufferBase (const Func &f, std::shared_ptr< GeneratorBase > generator)
StubOutputBufferBase ()=default
Protected Attributes
Func f
std::shared_ptr< GeneratorBase > generator
Detailed Description
Definition at line 1311 of file Generator.h.
Constructor & Destructor Documentation
StubOutputBufferBase() [1/2]
Halide::Internal::StubOutputBufferBase::StubOutputBufferBase (const Func & f, std::shared_ptr< GeneratorBase > generator) inline explicit protected
Definition at line 1319 of file Generator.h.
StubOutputBufferBase() [2/2]
Halide::Internal::StubOutputBufferBase::StubOutputBufferBase () protected default
Member Function Documentation
check_scheduled()
void Halide::Internal::StubOutputBufferBase::check_scheduled (const char * m) const protected
Referenced by realize().
get_target()
Target Halide::Internal::StubOutputBufferBase::get_target () const protected
Referenced by realize().
realize() [1/3]
Realization Halide::Internal::StubOutputBufferBase::realize (std::vector< int32_t > sizes) inline
Definition at line 1325 of file Generator.h.
References check_scheduled(), f, get_target(), and Halide::Func::realize().
realize() [2/3]
template<typename... Args> Realization Halide::Internal::StubOutputBufferBase::realize (Args &&... args) inline
Definition at line 1331 of file Generator.h.
References check_scheduled(), f, get_target(), and Halide::Func::realize().
realize() [3/3]
template<typename Dst > void Halide::Internal::StubOutputBufferBase::realize (Dst dst) inline
Definition at line 1337 of file Generator.h.
References check_scheduled(), dst, f, get_target(), and Halide::Func::realize().
Member Data Documentation
f
Func Halide::Internal::StubOutputBufferBase::f protected
Definition at line 1313 of file Generator.h.
Referenced by Halide::Internal::GeneratorOutput_Buffer< T >::operator=(), and realize().
generator
std::shared_ptr<GeneratorBase> Halide::Internal::StubOutputBufferBase::generator protected
Definition at line 1314 of file Generator.h.
The documentation for this class was generated from the following file:
/Users/halidenightly/build_bot_new/worker/halide-main-llvm13-x86-64-osx-cmake/halide-source/src/Generator.h