Halide: Halide::Internal::GeneratorInput_Arithmetic< T > Class Template Reference
Halide::Internal::GeneratorInput_Arithmetic< T > Class Template Reference
#include <Generator.h>
Inherits Halide::Internal::GeneratorInput_Scalar< T >.
Public Member Functions
GeneratorInput_Arithmetic (const std::string &name)
GeneratorInput_Arithmetic (const std::string &name, const TBase &def)
GeneratorInput_Arithmetic (size_t array_size, const std::string &name)
GeneratorInput_Arithmetic (size_t array_size, const std::string &name, const TBase &def)
GeneratorInput_Arithmetic (const std::string &name, const TBase &def, const TBase &min, const TBase &max)
GeneratorInput_Arithmetic (size_t array_size, const std::string &name, const TBase &def, const TBase &min, const TBase &max)
Public Member Functions inherited from Halide::Internal::GeneratorInput_Scalar< T >
GeneratorInput_Scalar (const std::string &name)
GeneratorInput_Scalar (const std::string &name, const TBase &def)
GeneratorInput_Scalar (size_t array_size, const std::string &name)
GeneratorInput_Scalar (size_t array_size, const std::string &name, const TBase &def)
operator Expr () const
You can use this Input as an expression in a halide function definition.
operator ExternFuncArgument () const
Using an Input as the argument to an external stage treats it as an Expr.
template<typename T2 = T, typename std::enable_if< std::is_pointer< T2 >::value >::type * = nullptr>
void set_estimate (const TBase &value)
template<typename T2 = T, typename std::enable_if<!std::is_array< T2 >::value &&!std::is_pointer< T2 >::value >::type * = nullptr>
void set_estimate (const TBase &value)
template<typename T2 = T, typename std::enable_if< std::is_array< T2 >::value >::type * = nullptr>
void set_estimate (size_t index, const TBase &value)
Public Member Functions inherited from Halide::Internal::GeneratorInputImpl< T, Expr >
size_t size () const
const Expr & operator[] (size_t i) const
const Expr & at (size_t i) const
std::vector< Expr >::const_iterator begin () const
std::vector< Expr >::const_iterator end () const
Public Member Functions inherited from Halide::Internal::GeneratorInputBase
~GeneratorInputBase () override
Public Member Functions inherited from Halide::Internal::GIOBase
bool array_size_defined () const
size_t array_size () const
const std::string & name () const
IOKind kind () const
bool types_defined () const
const std::vector< Type > & types () const
Type type () const
bool dims_defined () const
int dims () const
const std::vector< Func > & funcs () const
const std::vector< Expr > & exprs () const
virtual ~GIOBase ()=default
GIOBase (const GIOBase &)=delete
GIOBase & operator= (const GIOBase &)=delete
GIOBase (GIOBase &&)=delete
GIOBase & operator= (GIOBase &&)=delete
Protected Types
using TBase = typename Super::TBase
Protected Types inherited from Halide::Internal::GeneratorInput_Scalar< T >
using TBase = typename Super::TBase
Protected Types inherited from Halide::Internal::GeneratorInputImpl< T, Expr >
using TBase = typename std::remove_all_extents< T >::type
Protected Member Functions
void set_def_min_max () override
Protected Member Functions inherited from Halide::Internal::GeneratorInput_Scalar< T >
std::string get_c_type () const override
Protected Member Functions inherited from Halide::Internal::GeneratorInputImpl< T, Expr >
bool is_array () const override
GeneratorInputImpl (const std::string &name, IOKind kind, const std::vector< Type > &t, int d)
GeneratorInputImpl (const std::string &name, IOKind kind, const std::vector< Type > &t, int d)
GeneratorInputImpl (const std::string &name, IOKind kind, const std::vector< Type > &t, int d)
Protected Member Functions inherited from Halide::Internal::GeneratorInputBase
GeneratorInputBase (size_t array_size, const std::string &name, IOKind kind, const std::vector< Type > &t, int d)
GeneratorInputBase (const std::string &name, IOKind kind, const std::vector< Type > &t, int d)
Parameter parameter () const
void init_internals ()
void set_inputs (const std::vector< StubInput > &inputs)
void verify_internals () override
void check_value_writable () const override
const char * input_or_output () const override
void set_estimate_impl (const Var &var, const Expr &min, const Expr &extent)
void set_estimates_impl (const Region &estimates)
Protected Member Functions inherited from Halide::Internal::GIOBase
GIOBase (size_t array_size, const std::string &name, IOKind kind, const std::vector< Type > &types, int dims)
std::string array_name (size_t i) const
void check_matching_array_size (size_t size) const
void check_matching_types (const std::vector< Type > &t) const
void check_matching_dims (int d) const
template<typename ElemType >
const std::vector< ElemType > & get_values () const
void check_gio_access () const
template<>
const std::vector< Expr > & get_values () const
template<>
const std::vector< Func > & get_values () const
Protected Attributes
const Expr min_
const Expr max_
Protected Attributes inherited from Halide::Internal::GeneratorInput_Scalar< T >
const TBase def_ {TBase()}
const Expr def_expr_
Protected Attributes inherited from Halide::Internal::GeneratorInputBase
std::vector< Parameter > parameters_
Protected Attributes inherited from Halide::Internal::GIOBase
int array_size_
const std::string name_
const IOKind kind_
std::vector< Type > types_
int dims_
std::vector< Func > funcs_
std::vector< Expr > exprs_
GeneratorBase * generator {nullptr}
Additional Inherited Members
Static Protected Member Functions inherited from Halide::Internal::GeneratorInput_Scalar< T >
template<typename TBase2 = TBase, typename std::enable_if<!std::is_pointer< TBase2 >::value >::type * = nullptr>
static Expr TBaseToExpr (const TBase2 &value)
template<typename TBase2 = TBase, typename std::enable_if< std::is_pointer< TBase2 >::value >::type * = nullptr>
static Expr TBaseToExpr (const TBase2 &value)
Detailed Description
template<typename T>
class Halide::Internal::GeneratorInput_Arithmetic< T >
Definition at line 2023 of file Generator.h.
Member Typedef Documentation
TBase
template<typename T > using Halide::Internal::GeneratorInput_Arithmetic< T >::TBase = typename Super::TBase protected
Definition at line 2028 of file Generator.h.
Constructor & Destructor Documentation
GeneratorInput_Arithmetic() [1/6]
template<typename T > Halide::Internal::GeneratorInput_Arithmetic< T >::GeneratorInput_Arithmetic (const std::string & name) inline explicit
Definition at line 2048 of file Generator.h.
GeneratorInput_Arithmetic() [2/6]
template<typename T > Halide::Internal::GeneratorInput_Arithmetic< T >::GeneratorInput_Arithmetic (const std::string & name, const TBase & def) inline
Definition at line 2052 of file Generator.h.
GeneratorInput_Arithmetic() [3/6]
template<typename T > Halide::Internal::GeneratorInput_Arithmetic< T >::GeneratorInput_Arithmetic (size_t array_size, const std::string & name) inline
Definition at line 2057 of file Generator.h.
GeneratorInput_Arithmetic() [4/6]
template<typename T > Halide::Internal::GeneratorInput_Arithmetic< T >::GeneratorInput_Arithmetic (size_t array_size, const std::string & name, const TBase & def) inline
Definition at line 2062 of file Generator.h.
GeneratorInput_Arithmetic() [5/6]
template<typename T > Halide::Internal::GeneratorInput_Arithmetic< T >::GeneratorInput_Arithmetic (const std::string & name, const TBase & def, const TBase & min, const TBase & max) inline
Definition at line 2068 of file Generator.h.
GeneratorInput_Arithmetic() [6/6]
template<typename T > Halide::Internal::GeneratorInput_Arithmetic< T >::GeneratorInput_Arithmetic (size_t array_size, const std::string & name, const TBase & def, const TBase & min, const TBase & max) inline
Definition at line 2075 of file Generator.h.
Member Function Documentation
set_def_min_max()
template<typename T > void Halide::Internal::GeneratorInput_Arithmetic< T >::set_def_min_max () inline override protected virtual
Reimplemented from Halide::Internal::GeneratorInput_Scalar< T >.
Definition at line 2032 of file Generator.h.
References Halide::Internal::IntrusivePtr< T >::defined(), Halide::Internal::GeneratorInput_Arithmetic< T >::max_, Halide::Internal::GeneratorInput_Arithmetic< T >::min_, Halide::Internal::GeneratorInputBase::parameters_, Halide::Internal::GeneratorInput_Scalar< T >::set_def_min_max(), Halide::Internal::Parameter::set_max_value(), and Halide::Internal::Parameter::set_min_value().
Member Data Documentation
min_
template<typename T > const Expr Halide::Internal::GeneratorInput_Arithmetic< T >::min_ protected
Definition at line 2030 of file Generator.h.
Referenced by Halide::Internal::GeneratorInput_Arithmetic< T >::set_def_min_max().
max_
template<typename T > const Expr Halide::Internal::GeneratorInput_Arithmetic< T >::max_ protected
Definition at line 2030 of file Generator.h.
Referenced by Halide::Internal::GeneratorInput_Arithmetic< T >::set_def_min_max().
The documentation for this class was generated from the following file:
/Users/halidenightly/build_bot_new/worker/halide-main-llvm13-x86-64-osx-cmake/halide-source/src/Generator.h