Halide: Halide::Internal::GPUCompilationCache< ContextT, ModuleStateT > Class Template Reference
Halide::Internal::GPUCompilationCache< ContextT, ModuleStateT > Class Template Reference
#include <gpu_context_common.h>
Public Member Functions
HALIDE_MUST_USE_RESULT bool insert (const CachedCompilation &entry)
HALIDE_MUST_USE_RESULT bool find_internal (ContextT context, uint32_t id, ModuleStateT *&module_state, int increment)
HALIDE_MUST_USE_RESULT bool lookup (ContextT context, void *state_ptr, ModuleStateT &module_state)
HALIDE_MUST_USE_RESULT bool resize_table (int size_bits)
template<typename FreeModuleT >
void release_context (void *user_context, bool all, ContextT context, FreeModuleT &f)
template<typename FreeModuleT >
void delete_context (void *user_context, ContextT context, FreeModuleT &f)
template<typename FreeModuleT >
void release_all (void *user_context, FreeModuleT &f)
template<typename CompileModuleT , typename... Args>
HALIDE_MUST_USE_RESULT bool kernel_state_setup (void *user_context, void **state_ptr, ContextT context, ModuleStateT &result, CompileModuleT f, Args... args)
void release_hold (void *user_context, ContextT context, void *state_ptr)
Static Public Member Functions
static ALWAYS_INLINE uintptr_t kernel_hash (ContextT context, uint32_t id, uint32_t bits)
Detailed Description
template<typename ContextT, typename ModuleStateT>
class Halide::Internal::GPUCompilationCache< ContextT, ModuleStateT >
Definition at line 8 of file gpu_context_common.h.
Member Function Documentation
kernel_hash()
template<typename ContextT , typename ModuleStateT > static ALWAYS_INLINE uintptr_t Halide::Internal::GPUCompilationCache< ContextT, ModuleStateT >::kernel_hash (ContextT context, uint32_t id, uint32_t bits) inline static
Definition at line 36 of file gpu_context_common.h.
Referenced by Halide::Internal::GPUCompilationCache< ContextT, ModuleStateT >::find_internal(), and Halide::Internal::GPUCompilationCache< ContextT, ModuleStateT >::insert().
insert()
template<typename ContextT , typename ModuleStateT > HALIDE_MUST_USE_RESULT bool Halide::Internal::GPUCompilationCache< ContextT, ModuleStateT >::insert (const CachedCompilation & entry) inline
Definition at line 47 of file gpu_context_common.h.
References halide_assert, Halide::Internal::GPUCompilationCache< ContextT, ModuleStateT >::kernel_hash(), and Halide::Internal::GPUCompilationCache< ContextT, ModuleStateT >::resize_table().
Referenced by Halide::Internal::GPUCompilationCache< ContextT, ModuleStateT >::kernel_state_setup(), and Halide::Internal::GPUCompilationCache< ContextT, ModuleStateT >::resize_table().
find_internal()
template<typename ContextT , typename ModuleStateT > HALIDE_MUST_USE_RESULT bool Halide::Internal::GPUCompilationCache< ContextT, ModuleStateT >::find_internal (ContextT context, uint32_t id, ModuleStateT *& module_state, int increment) inline
Definition at line 73 of file gpu_context_common.h.
References Halide::Internal::GPUCompilationCache< ContextT, ModuleStateT >::kernel_hash().
Referenced by Halide::Internal::GPUCompilationCache< ContextT, ModuleStateT >::kernel_state_setup(), Halide::Internal::GPUCompilationCache< ContextT, ModuleStateT >::lookup(), and Halide::Internal::GPUCompilationCache< ContextT, ModuleStateT >::release_hold().
lookup()
template<typename ContextT , typename ModuleStateT > HALIDE_MUST_USE_RESULT bool Halide::Internal::GPUCompilationCache< ContextT, ModuleStateT >::lookup (ContextT context, void * state_ptr, ModuleStateT & module_state) inline
Definition at line 97 of file gpu_context_common.h.
References Halide::Internal::GPUCompilationCache< ContextT, ModuleStateT >::find_internal().
resize_table()
template<typename ContextT , typename ModuleStateT > HALIDE_MUST_USE_RESULT bool Halide::Internal::GPUCompilationCache< ContextT, ModuleStateT >::resize_table (int size_bits) inline
Definition at line 108 of file gpu_context_common.h.
References free(), halide_assert, Halide::Internal::GPUCompilationCache< ContextT, ModuleStateT >::insert(), malloc(), and memset().
Referenced by Halide::Internal::GPUCompilationCache< ContextT, ModuleStateT >::insert().
release_context()
template<typename ContextT , typename ModuleStateT > template<typename FreeModuleT > void Halide::Internal::GPUCompilationCache< ContextT, ModuleStateT >::release_context (void * user_context, bool all, ContextT context, FreeModuleT & f) inline
Definition at line 137 of file gpu_context_common.h.
References user_context.
Referenced by Halide::Internal::GPUCompilationCache< ContextT, ModuleStateT >::delete_context(), and Halide::Internal::GPUCompilationCache< ContextT, ModuleStateT >::release_all().
delete_context()
template<typename ContextT , typename ModuleStateT > template<typename FreeModuleT > void Halide::Internal::GPUCompilationCache< ContextT, ModuleStateT >::delete_context (void * user_context, ContextT context, FreeModuleT & f) inline
Definition at line 158 of file gpu_context_common.h.
References Halide::Internal::GPUCompilationCache< ContextT, ModuleStateT >::release_context(), and user_context.
release_all()
template<typename ContextT , typename ModuleStateT > template<typename FreeModuleT > void Halide::Internal::GPUCompilationCache< ContextT, ModuleStateT >::release_all (void * user_context, FreeModuleT & f) inline
Definition at line 165 of file gpu_context_common.h.
References free(), Halide::Internal::GPUCompilationCache< ContextT, ModuleStateT >::release_context(), and user_context.
kernel_state_setup()
template<typename ContextT , typename ModuleStateT > template<typename CompileModuleT , typename... Args> HALIDE_MUST_USE_RESULT bool Halide::Internal::GPUCompilationCache< ContextT, ModuleStateT >::kernel_state_setup (void * user_context, void ** state_ptr, ContextT context, ModuleStateT & result, CompileModuleT f, Args... args) inline
Definition at line 178 of file gpu_context_common.h.
References Halide::Internal::GPUCompilationCache< ContextT, ModuleStateT >::find_internal(), Halide::Internal::GPUCompilationCache< ContextT, ModuleStateT >::insert(), Halide::Internal::IRMatcher::mod(), and user_context.
release_hold()
template<typename ContextT , typename ModuleStateT > void Halide::Internal::GPUCompilationCache< ContextT, ModuleStateT >::release_hold (void * user_context, ContextT context, void * state_ptr) inline
Definition at line 211 of file gpu_context_common.h.
References Halide::Internal::GPUCompilationCache< ContextT, ModuleStateT >::find_internal(), halide_assert, Halide::Internal::IRMatcher::mod(), and user_context.
The documentation for this class was generated from the following file:
/Users/halidenightly/build_bot_new/worker/halide-main-llvm13-x86-64-osx-cmake/halide-source/src/runtime/gpu_context_common.h