Halide: Halide::Internal::GeneratorParamImpl< T > Class Template Reference
Halide::Internal::GeneratorParamImpl< T > Class Template Reference
#include <Generator.h>
Inherits Halide::Internal::GeneratorParamBase.
Inherited by Halide::Internal::GeneratorParam_Arithmetic< T >, Halide::Internal::GeneratorParam_Enum< T >, Halide::Internal::GeneratorParam_MachineParams< T >, Halide::Internal::GeneratorParam_String< T >, Halide::Internal::GeneratorParam_Synthetic< T >, and Halide::Internal::GeneratorParam_Target< T >.
Public Types
using type = T
Public Member Functions
GeneratorParamImpl (const std::string &name, const T &value)
T value () const
operator T () const
operator Expr () const
void set (const std::string &new_value)
Public Member Functions inherited from Halide::Internal::GeneratorParamBase
GeneratorParamBase (const std::string &name)
virtual ~GeneratorParamBase ()
const std::string & name () const
void set (const std::string &new_value)
void set (const char *new_value)
GeneratorParamBase (const GeneratorParamBase &)=delete
GeneratorParamBase & operator= (const GeneratorParamBase &)=delete
GeneratorParamBase (GeneratorParamBase &&)=delete
GeneratorParamBase & operator= (GeneratorParamBase &&)=delete
Protected Member Functions
virtual void set_impl (const T &new_value)
Protected Member Functions inherited from Halide::Internal::GeneratorParamBase
void check_value_readable () const
void check_value_writable () const
virtual void set_from_string (const std::string &value_string)=0
virtual std::string call_to_string (const std::string &v) const =0
virtual std::string get_c_type () const =0
virtual std::string get_type_decls () const
virtual std::string get_default_value () const =0
virtual bool is_synthetic_param () const
virtual bool is_looplevel_param () const
void fail_wrong_type (const char *type)
Protected Attributes
T value_
Detailed Description
template<typename T>
class Halide::Internal::GeneratorParamImpl< T >
Definition at line 501 of file Generator.h.
Member Typedef Documentation
type
template<typename T > using Halide::Internal::GeneratorParamImpl< T >::type = T
Definition at line 503 of file Generator.h.
Constructor & Destructor Documentation
GeneratorParamImpl()
template<typename T > Halide::Internal::GeneratorParamImpl< T >::GeneratorParamImpl (const std::string & name, const T & value) inline
Definition at line 505 of file Generator.h.
Member Function Documentation
value()
template<typename T > T Halide::Internal::GeneratorParamImpl< T >::value () const inline
Definition at line 509 of file Generator.h.
References Halide::Internal::GeneratorParamBase::check_value_readable(), and Halide::Internal::GeneratorParamImpl< T >::value_.
Referenced by Halide::Internal::GeneratorParam_Target< T >::get_default_value(), Halide::Internal::GeneratorParam_MachineParams< T >::get_default_value(), Halide::Internal::GeneratorParam_Arithmetic< T >::get_default_value(), Halide::Internal::GeneratorParam_Bool< T >::get_default_value(), Halide::Internal::GeneratorParam_Enum< T >::get_default_value(), Halide::Internal::GeneratorParam_Type< T >::get_default_value(), Halide::Internal::GeneratorParam_String< T >::get_default_value(), Halide::Internal::GeneratorParamImpl< T >::operator Expr(), and Halide::Internal::GeneratorParamImpl< LoopLevel >::operator LoopLevel().
operator T()
template<typename T > Halide::Internal::GeneratorParamImpl< T >::operator T () const inline
Definition at line 514 of file Generator.h.
operator Expr()
template<typename T > Halide::Internal::GeneratorParamImpl< T >::operator Expr () const inline
Definition at line 518 of file Generator.h.
References Halide::Internal::make_const(), and Halide::Internal::GeneratorParamImpl< T >::value().
set()
template<typename T > void Halide::Internal::GeneratorParamImpl< T >::set (const std::string & new_value) inline
Definition at line 546 of file Generator.h.
References Halide::Internal::GeneratorParamBase::check_value_writable(), and Halide::Internal::GeneratorParamImpl< T >::value_.
Referenced by Halide::Internal::GeneratorParam_Arithmetic< T >::GeneratorParam_Arithmetic(), Halide::Internal::GeneratorParam_Target< T >::set_from_string(), Halide::Internal::GeneratorParam_MachineParams< T >::set_from_string(), Halide::Internal::GeneratorParam_Arithmetic< T >::set_from_string(), Halide::Internal::GeneratorParam_Bool< T >::set_from_string(), and Halide::Internal::GeneratorParam_String< T >::set_from_string().
set_impl()
template<typename T > virtual void Halide::Internal::GeneratorParamImpl< T >::set_impl (const T & new_value) inline protected virtual
Reimplemented in Halide::Internal::GeneratorParam_Arithmetic< T >.
Definition at line 552 of file Generator.h.
References Halide::Internal::GeneratorParamBase::check_value_writable(), and Halide::Internal::GeneratorParamImpl< T >::value_.
Referenced by Halide::Internal::GeneratorParam_Enum< T >::set(), Halide::Internal::GeneratorParam_Enum< T >::set_from_string(), and Halide::Internal::GeneratorParam_Arithmetic< T >::set_impl().
Member Data Documentation
value_
template<typename T > T Halide::Internal::GeneratorParamImpl< T >::value_ protected
Definition at line 558 of file Generator.h.
Referenced by Halide::Internal::GeneratorParamImpl< T >::set(), Halide::Internal::GeneratorParamImpl< T >::set_impl(), and Halide::Internal::GeneratorParamImpl< T >::value().
The documentation for this class was generated from the following file:
/Users/halidenightly/build_bot_new/worker/halide-main-llvm13-x86-64-osx-cmake/halide-source/src/Generator.h