Halide: Halide::Internal::GeneratorOutput_Func< T > Class Template Reference
Halide::Internal::GeneratorOutput_Func< T > Class Template Reference
#include <Generator.h>
Inherits Halide::Internal::GeneratorOutputImpl< T >.
Public Member Functions
template<typename T2 = T, typename std::enable_if<!std::is_array< T2 >::value >::type * = nullptr>
GeneratorOutput_Func< T > & operator= (const Func &f)
template<typename T2 = T, typename std::enable_if< std::is_array< T2 >::value >::type * = nullptr>
Func & operator[] (size_t i)
template<typename T2 = T, typename std::enable_if< std::is_array< T2 >::value >::type * = nullptr>
const Func & operator[] (size_t i) const
GeneratorOutput_Func< T > & set_estimate (const Var &var, const Expr &min, const Expr &extent)
GeneratorOutput_Func< T > & set_estimates (const Region &estimates)
Public Member Functions inherited from Halide::Internal::GeneratorOutputImpl< T >
template<typename... Args, typename T2 = T, typename std::enable_if<!std::is_array< T2 >::value >::type * = nullptr>
FuncRef operator() (Args &&...args) const
template<typename ExprOrVar , typename T2 = T, typename std::enable_if<!std::is_array< T2 >::value >::type * = nullptr>
FuncRef operator() (std::vector< ExprOrVar > args) const
template<typename T2 = T, typename std::enable_if<!std::is_array< T2 >::value >::type * = nullptr>
operator Func () const
template<typename T2 = T, typename std::enable_if<!std::is_array< T2 >::value >::type * = nullptr>
operator Stage () const
template<typename T2 = T, typename std::enable_if< std::is_array< T2 >::value >::type * = nullptr>
size_t size () const
template<typename T2 = T, typename std::enable_if< std::is_array< T2 >::value >::type * = nullptr>
const ValueType & operator[] (size_t i) const
template<typename T2 = T, typename std::enable_if< std::is_array< T2 >::value >::type * = nullptr>
const ValueType & at (size_t i) const
template<typename T2 = T, typename std::enable_if< std::is_array< T2 >::value >::type * = nullptr>
std::vector< ValueType >::const_iterator begin () const
template<typename T2 = T, typename std::enable_if< std::is_array< T2 >::value >::type * = nullptr>
std::vector< ValueType >::const_iterator end () const
template<typename T2 = T, typename std::enable_if< std::is_array< T2 >::value &&std::rank< T2 >::value==1 &&std::extent< T2, 0 >::value==0 >::type * = nullptr>
void resize (size_t size)
Public Member Functions inherited from Halide::Internal::GeneratorOutputBase
~GeneratorOutputBase () override
Public Member Functions inherited from Halide::Internal::GIOBase
bool array_size_defined () const
size_t array_size () const
const std::string & name () const
IOKind kind () const
bool types_defined () const
const std::vector< Type > & types () const
Type type () const
bool dims_defined () const
int dims () const
const std::vector< Func > & funcs () const
const std::vector< Expr > & exprs () const
virtual ~GIOBase ()=default
GIOBase (const GIOBase &)=delete
GIOBase & operator= (const GIOBase &)=delete
GIOBase (GIOBase &&)=delete
GIOBase & operator= (GIOBase &&)=delete
Protected Types
using TBase = typename Super::TBase
Protected Types inherited from Halide::Internal::GeneratorOutputImpl< T >
using TBase = typename std::remove_all_extents< T >::type
using ValueType = Func
Protected Member Functions
GeneratorOutput_Func (const std::string &name)
GeneratorOutput_Func (const std::string &name, const std::vector< Type > &t, int d=-1)
GeneratorOutput_Func (size_t array_size, const std::string &name, const std::vector< Type > &t, int d)
Protected Member Functions inherited from Halide::Internal::GeneratorOutputImpl< T >
bool is_array () const override
template<typename T2 = T, typename std::enable_if< !std::is_array< T2 >::value >::type * = nullptr>
GeneratorOutputImpl (const std::string &name, IOKind kind, const std::vector< Type > &t, int d)
template<typename T2 = T, typename std::enable_if< std::is_array< T2 >::value &&std::rank< T2 >::value==1 &&(std::extent< T2, 0 >::value > 0)>::type * = nullptr>
GeneratorOutputImpl (const std::string &name, IOKind kind, const std::vector< Type > &t, int d)
template<typename T2 = T, typename std::enable_if< std::is_array< T2 >::value &&std::rank< T2 >::value==1 &&std::extent< T2, 0 >::value==0 >::type * = nullptr>
GeneratorOutputImpl (const std::string &name, IOKind kind, const std::vector< Type > &t, int d)
Protected Member Functions inherited from Halide::Internal::GeneratorOutputBase
template<typename T2 , typename std::enable_if< std::is_same< T2, Func >::value >::type * = nullptr>
HALIDE_NO_USER_CODE_INLINE T2 as () const
GeneratorOutputBase (size_t array_size, const std::string &name, IOKind kind, const std::vector< Type > &t, int d)
Forward schedule-related methods to the underlying Func.
GeneratorOutputBase (const std::string &name, IOKind kind, const std::vector< Type > &t, int d)
void init_internals ()
void resize (size_t size)
virtual std::string get_c_type () const
void check_value_writable () const override
const char * input_or_output () const override
Protected Member Functions inherited from Halide::Internal::GIOBase
GIOBase (size_t array_size, const std::string &name, IOKind kind, const std::vector< Type > &types, int dims)
std::string array_name (size_t i) const
virtual void verify_internals ()
void check_matching_array_size (size_t size) const
void check_matching_types (const std::vector< Type > &t) const
void check_matching_dims (int d) const
template<typename ElemType >
const std::vector< ElemType > & get_values () const
void check_gio_access () const
template<>
const std::vector< Expr > & get_values () const
template<>
const std::vector< Func > & get_values () const
Additional Inherited Members
Protected Attributes inherited from Halide::Internal::GIOBase
int array_size_
const std::string name_
const IOKind kind_
std::vector< Type > types_
int dims_
std::vector< Func > funcs_
std::vector< Expr > exprs_
GeneratorBase * generator {nullptr}
Detailed Description
template<typename T>
class Halide::Internal::GeneratorOutput_Func< T >
Definition at line 2540 of file Generator.h.
Member Typedef Documentation
TBase
template<typename T > using Halide::Internal::GeneratorOutput_Func< T >::TBase = typename Super::TBase protected
Definition at line 2550 of file Generator.h.
Constructor & Destructor Documentation
GeneratorOutput_Func() [1/3]
template<typename T > Halide::Internal::GeneratorOutput_Func< T >::GeneratorOutput_Func (const std::string & name) inline protected
Definition at line 2552 of file Generator.h.
GeneratorOutput_Func() [2/3]
template<typename T > Halide::Internal::GeneratorOutput_Func< T >::GeneratorOutput_Func (const std::string & name, const std::vector< Type > & t, int d = -1) inline protected
Definition at line 2556 of file Generator.h.
GeneratorOutput_Func() [3/3]
template<typename T > Halide::Internal::GeneratorOutput_Func< T >::GeneratorOutput_Func (size_t array_size, const std::string & name, const std::vector< Type > & t, int d) inline protected
Definition at line 2560 of file Generator.h.
Member Function Documentation
operator=()
template<typename T > template<typename T2 = T, typename std::enable_if<!std::is_array< T2 >::value >::type * = nullptr> GeneratorOutput_Func<T>& Halide::Internal::GeneratorOutput_Func< T >::operator= (const Func & f) inline
Definition at line 2567 of file Generator.h.
References Halide::Internal::GIOBase::check_gio_access(), and Halide::Internal::GeneratorOutputBase::check_value_writable().
operator[]() [1/2]
template<typename T > template<typename T2 = T, typename std::enable_if< std::is_array< T2 >::value >::type * = nullptr> Func& Halide::Internal::GeneratorOutput_Func< T >::operator[] (size_t i) inline
Definition at line 2579 of file Generator.h.
References Halide::Internal::GIOBase::check_gio_access(), and Halide::Internal::GeneratorOutputBase::check_value_writable().
operator[]() [2/2]
template<typename T > template<typename T2 = T, typename std::enable_if< std::is_array< T2 >::value >::type * = nullptr> const Func& Halide::Internal::GeneratorOutput_Func< T >::operator[] (size_t i) const inline
Definition at line 2587 of file Generator.h.
References Halide::Internal::GIOBase::check_gio_access(), and Halide::Internal::GeneratorOutputImpl< T >::operator[]().
set_estimate()
template<typename T > GeneratorOutput_Func<T>& Halide::Internal::GeneratorOutput_Func< T >::set_estimate (const Var & var, const Expr & min, const Expr & extent) inline
Definition at line 2592 of file Generator.h.
References Halide::Internal::GIOBase::check_gio_access(), Halide::Internal::GIOBase::exprs_, Halide::Internal::GIOBase::funcs_, internal_assert, Halide::min(), and Halide::Func::set_estimate().
set_estimates()
template<typename T > GeneratorOutput_Func<T>& Halide::Internal::GeneratorOutput_Func< T >::set_estimates (const Region & estimates) inline
Definition at line 2601 of file Generator.h.
References Halide::Internal::GIOBase::check_gio_access(), Halide::Internal::GIOBase::exprs_, Halide::Internal::GIOBase::funcs_, internal_assert, and Halide::Func::set_estimates().
The documentation for this class was generated from the following file:
/Users/halidenightly/build_bot_new/worker/halide-main-llvm13-x86-64-osx-cmake/halide-source/src/Generator.h