Halide: Halide::Runtime::Internal::Synchronization Namespace Reference
Halide::Runtime::Internal::Synchronization Namespace Reference
Classes
class spin_control
struct word_lock_queue_data
class word_lock
struct queue_data
struct hash_bucket
struct hash_table
struct bucket_pair
struct validate_action
struct parking_control
struct mutex_parking_control
class fast_mutex
struct signal_parking_control
struct broadcast_parking_control
struct wait_parking_control
class fast_cond
Functions
ALWAYS_INLINE void check_hash (uintptr_t hash)
WEAK hash_bucket & lock_bucket (uintptr_t addr)
WEAK bucket_pair lock_bucket_pair (uintptr_t addr_from, uintptr_t addr_to)
WEAK void unlock_bucket_pair (bucket_pair &buckets)
WEAK bool parking_control_validate (void *control, validate_action &action)
WEAK void parking_control_before_sleep (void *control)
WEAK uintptr_t parking_control_unpark (void *control, int unparked, bool more_waiters)
WEAK void parking_control_requeue_callback (void *control, const validate_action &action, bool one_to_wake, bool some_requeued)
WEAK uintptr_t park (uintptr_t addr, parking_control &control)
WEAK uintptr_t unpark_one (uintptr_t addr, parking_control &control)
WEAK uintptr_t unpark_all (uintptr_t addr, uintptr_t unpark_info)
WEAK int unpark_requeue (uintptr_t addr_from, uintptr_t addr_to, parking_control &control, uintptr_t unpark_info)
WEAK bool mutex_parking_control_validate (void *control, validate_action &action)
WEAK uintptr_t mutex_parking_control_unpark (void *control, int unparked, bool more_waiters)
WEAK uintptr_t signal_parking_control_unpark (void *control, int unparked, bool more_waiters)
WEAK bool broadcast_parking_control_validate (void *control, validate_action &action)
WEAK void broadcast_parking_control_requeue_callback (void *control, const validate_action &action, bool one_to_wake, bool some_requeued)
WEAK bool wait_parking_control_validate (void *control, validate_action &action)
WEAK void wait_parking_control_before_sleep (void *control)
WEAK uintptr_t wait_parking_control_unpark (void *control, int unparked, bool more_waiters)
Variables
WEAK char table_storage [sizeof(hash_table)]
Function Documentation
check_hash()
ALWAYS_INLINE void Halide::Runtime::Internal::Synchronization::check_hash (uintptr_t hash)
Definition at line 481 of file synchronization_common.h.
References halide_assert, and table.
Referenced by lock_bucket(), and lock_bucket_pair().
lock_bucket()
WEAK hash_bucket& Halide::Runtime::Internal::Synchronization::lock_bucket (uintptr_t addr)
Definition at line 509 of file synchronization_common.h.
References check_hash(), HASH_TABLE_BITS, Halide::Runtime::Internal::Synchronization::word_lock::lock(), Halide::Runtime::Internal::Synchronization::hash_bucket::mutex, and table.
Referenced by park(), unpark_all(), and unpark_one().
lock_bucket_pair()
WEAK bucket_pair Halide::Runtime::Internal::Synchronization::lock_bucket_pair (uintptr_t addr_from, uintptr_t addr_to)
Definition at line 531 of file synchronization_common.h.
References check_hash(), HASH_TABLE_BITS, Halide::Runtime::Internal::Synchronization::word_lock::lock(), Halide::Runtime::Internal::Synchronization::hash_bucket::mutex, and table.
Referenced by unpark_requeue().
unlock_bucket_pair()
WEAK void Halide::Runtime::Internal::Synchronization::unlock_bucket_pair (bucket_pair & buckets)
Definition at line 560 of file synchronization_common.h.
References Halide::Runtime::Internal::Synchronization::bucket_pair::from, Halide::Runtime::Internal::Synchronization::hash_bucket::mutex, Halide::Runtime::Internal::Synchronization::bucket_pair::to, and Halide::Runtime::Internal::Synchronization::word_lock::unlock().
Referenced by unpark_requeue().
parking_control_validate()
WEAK bool Halide::Runtime::Internal::Synchronization::parking_control_validate (void * control, validate_action & action)
Definition at line 583 of file synchronization_common.h.
parking_control_before_sleep()
WEAK void Halide::Runtime::Internal::Synchronization::parking_control_before_sleep (void * control)
Definition at line 586 of file synchronization_common.h.
parking_control_unpark()
WEAK uintptr_t Halide::Runtime::Internal::Synchronization::parking_control_unpark (void * control, int unparked, bool more_waiters)
Definition at line 587 of file synchronization_common.h.
parking_control_requeue_callback()
WEAK void Halide::Runtime::Internal::Synchronization::parking_control_requeue_callback (void * control, const validate_action & action, bool one_to_wake, bool some_requeued)
Definition at line 590 of file synchronization_common.h.
park()
WEAK uintptr_t Halide::Runtime::Internal::Synchronization::park (uintptr_t addr, parking_control & control)
Definition at line 605 of file synchronization_common.h.
References Halide::Runtime::Internal::Synchronization::parking_control::before_sleep, Halide::Runtime::Internal::Synchronization::hash_bucket::head, Halide::Runtime::Internal::Synchronization::validate_action::invalid_unpark_info, lock_bucket(), Halide::Runtime::Internal::Synchronization::hash_bucket::mutex, Halide::Runtime::Internal::Synchronization::queue_data::next, Halide::Runtime::Internal::Synchronization::queue_data::parker, Halide::Runtime::Internal::Synchronization::queue_data::sleep_address, Halide::Runtime::Internal::Synchronization::hash_bucket::tail, Halide::Runtime::Internal::Synchronization::word_lock::unlock(), Halide::Runtime::Internal::Synchronization::queue_data::unpark_info, and Halide::Runtime::Internal::Synchronization::parking_control::validate.
Referenced by Halide::Runtime::Internal::Synchronization::fast_cond::wait().
unpark_one()
WEAK uintptr_t Halide::Runtime::Internal::Synchronization::unpark_one (uintptr_t addr, parking_control & control)
Definition at line 636 of file synchronization_common.h.
References Halide::Runtime::Internal::Synchronization::hash_bucket::head, lock_bucket(), Halide::Runtime::Internal::Synchronization::hash_bucket::mutex, Halide::Runtime::Internal::Synchronization::queue_data::next, Halide::Runtime::Internal::Synchronization::queue_data::parker, Halide::Runtime::Internal::Synchronization::queue_data::sleep_address, Halide::Runtime::Internal::Synchronization::hash_bucket::tail, Halide::Runtime::Internal::Synchronization::word_lock::unlock(), Halide::Runtime::Internal::Synchronization::parking_control::unpark, and Halide::Runtime::Internal::Synchronization::queue_data::unpark_info.
Referenced by Halide::Runtime::Internal::Synchronization::fast_cond::signal().
unpark_all()
WEAK uintptr_t Halide::Runtime::Internal::Synchronization::unpark_all (uintptr_t addr, uintptr_t unpark_info)
Definition at line 687 of file synchronization_common.h.
References free(), Halide::Runtime::Internal::Synchronization::hash_bucket::head, lock_bucket(), malloc(), Halide::Runtime::Internal::Synchronization::hash_bucket::mutex, Halide::Runtime::Internal::Synchronization::queue_data::next, Halide::Runtime::Internal::Synchronization::queue_data::parker, Halide::Runtime::Internal::Synchronization::queue_data::sleep_address, Halide::Runtime::Internal::Synchronization::hash_bucket::tail, Halide::Runtime::Internal::Synchronization::word_lock::unlock(), and Halide::Runtime::Internal::Synchronization::queue_data::unpark_info.
unpark_requeue()
WEAK int Halide::Runtime::Internal::Synchronization::unpark_requeue (uintptr_t addr_from, uintptr_t addr_to, parking_control & control, uintptr_t unpark_info)
Definition at line 753 of file synchronization_common.h.
References Halide::Runtime::Internal::Synchronization::bucket_pair::from, Halide::Runtime::Internal::Synchronization::hash_bucket::head, lock_bucket_pair(), Halide::Runtime::Internal::Synchronization::queue_data::next, Halide::Runtime::Internal::Synchronization::queue_data::parker, Halide::Runtime::Internal::Synchronization::parking_control::requeue_callback, Halide::Runtime::Internal::Synchronization::queue_data::sleep_address, Halide::Runtime::Internal::Synchronization::hash_bucket::tail, Halide::Runtime::Internal::Synchronization::bucket_pair::to, unlock_bucket_pair(), Halide::Runtime::Internal::Synchronization::queue_data::unpark_info, Halide::Runtime::Internal::Synchronization::validate_action::unpark_one, and Halide::Runtime::Internal::Synchronization::parking_control::validate.
Referenced by Halide::Runtime::Internal::Synchronization::fast_cond::broadcast().
mutex_parking_control_validate()
WEAK bool Halide::Runtime::Internal::Synchronization::mutex_parking_control_validate (void * control, validate_action & action)
Definition at line 840 of file synchronization_common.h.
References Halide::Runtime::Internal::Synchronization::mutex_parking_control::lock_state.
Referenced by Halide::Runtime::Internal::Synchronization::mutex_parking_control::mutex_parking_control().
mutex_parking_control_unpark()
WEAK uintptr_t Halide::Runtime::Internal::Synchronization::mutex_parking_control_unpark (void * control, int unparked, bool more_waiters)
Definition at line 849 of file synchronization_common.h.
References Halide::Runtime::Internal::Synchronization::mutex_parking_control::lock_state.
Referenced by Halide::Runtime::Internal::Synchronization::mutex_parking_control::mutex_parking_control().
signal_parking_control_unpark()
WEAK uintptr_t Halide::Runtime::Internal::Synchronization::signal_parking_control_unpark (void * control, int unparked, bool more_waiters)
Definition at line 968 of file synchronization_common.h.
References Halide::Runtime::Internal::Synchronization::signal_parking_control::cond_state, and Halide::Runtime::Internal::Synchronization::signal_parking_control::mutex.
Referenced by Halide::Runtime::Internal::Synchronization::signal_parking_control::signal_parking_control().
broadcast_parking_control_validate()
WEAK bool Halide::Runtime::Internal::Synchronization::broadcast_parking_control_validate (void * control, validate_action & action)
Definition at line 996 of file synchronization_common.h.
References Halide::Runtime::Internal::Synchronization::broadcast_parking_control::cond_state, Halide::Runtime::Internal::Synchronization::fast_mutex::make_parked_if_locked(), Halide::Runtime::Internal::Synchronization::broadcast_parking_control::mutex, and Halide::Runtime::Internal::Synchronization::validate_action::unpark_one.
Referenced by Halide::Runtime::Internal::Synchronization::broadcast_parking_control::broadcast_parking_control().
broadcast_parking_control_requeue_callback()
WEAK void Halide::Runtime::Internal::Synchronization::broadcast_parking_control_requeue_callback (void * control, const validate_action & action, bool one_to_wake, bool some_requeued)
Definition at line 1016 of file synchronization_common.h.
References Halide::Runtime::Internal::Synchronization::fast_mutex::make_parked(), Halide::Runtime::Internal::Synchronization::broadcast_parking_control::mutex, and Halide::Runtime::Internal::Synchronization::validate_action::unpark_one.
Referenced by Halide::Runtime::Internal::Synchronization::broadcast_parking_control::broadcast_parking_control().
wait_parking_control_validate()
WEAK bool Halide::Runtime::Internal::Synchronization::wait_parking_control_validate (void * control, validate_action & action)
Definition at line 1038 of file synchronization_common.h.
References Halide::Runtime::Internal::Synchronization::wait_parking_control::cond_state, Halide::Runtime::Internal::Synchronization::validate_action::invalid_unpark_info, and Halide::Runtime::Internal::Synchronization::wait_parking_control::mutex.
Referenced by Halide::Runtime::Internal::Synchronization::wait_parking_control::wait_parking_control().
wait_parking_control_before_sleep()
WEAK void Halide::Runtime::Internal::Synchronization::wait_parking_control_before_sleep (void * control)
Definition at line 1056 of file synchronization_common.h.
References Halide::Runtime::Internal::Synchronization::wait_parking_control::mutex, and Halide::Runtime::Internal::Synchronization::fast_mutex::unlock().
Referenced by Halide::Runtime::Internal::Synchronization::wait_parking_control::wait_parking_control().
wait_parking_control_unpark()
WEAK uintptr_t Halide::Runtime::Internal::Synchronization::wait_parking_control_unpark (void * control, int unparked, bool more_waiters)
Definition at line 1062 of file synchronization_common.h.
References Halide::Runtime::Internal::Synchronization::wait_parking_control::cond_state.
Referenced by Halide::Runtime::Internal::Synchronization::wait_parking_control::wait_parking_control().
Variable Documentation
table_storage
WEAK char Halide::Runtime::Internal::Synchronization::table_storage[sizeof(hash_table)]
Definition at line 478 of file synchronization_common.h.