Halide: Halide::Internal::IRMatcher Namespace Reference
Halide::Internal::IRMatcher Namespace Reference
An alternative template-metaprogramming approach to expression matching.
Classes
struct MatcherState
To save stack space, the matcher objects are largely stateless and immutable.
struct enable_if_pattern
struct bindings
struct SpecificExpr
struct WildConstInt
struct WildConstUInt
struct WildConstFloat
struct WildConst
struct Wild
struct IntLiteral
struct BinOp
struct CmpOp
struct Intrin
struct NotOp
struct SelectOp
struct BroadcastOp
struct RampOp
struct VectorReduceOp
struct NegateOp
struct CastOp
struct Fold
struct Overflows
struct Overflow
struct IsConst
struct CanProve
struct IsFloat
struct IsInt
struct IsUInt
struct IsScalar
struct IsMaxValue
struct IsMinValue
struct Rewriter
Functions
HALIDE_NEVER_INLINE Expr make_const_special_expr (halide_type_t ty)
HALIDE_ALWAYS_INLINE Expr make_const_expr (halide_scalar_value_t val, halide_type_t ty)
bool equal_helper (const BaseExprNode &a, const BaseExprNode &b) noexcept
HALIDE_ALWAYS_INLINE bool equal (const BaseExprNode &a, const BaseExprNode &b) noexcept
std::ostream & operator<< (std::ostream &s, const SpecificExpr &e)
template<int i>
std::ostream & operator<< (std::ostream &s, const WildConstInt< i > &c)
template<int i>
std::ostream & operator<< (std::ostream &s, const WildConstUInt< i > &c)
template<int i>
std::ostream & operator<< (std::ostream &s, const WildConstFloat< i > &c)
template<int i>
std::ostream & operator<< (std::ostream &s, const WildConst< i > &c)
template<int i>
std::ostream & operator<< (std::ostream &s, const Wild< i > &op)
HALIDE_ALWAYS_INLINE int64_t unwrap (IntLiteral t)
template<typename T , typename = typename std::decay<T>::type::pattern_tag>
HALIDE_ALWAYS_INLINE T pattern_arg (T t)
HALIDE_ALWAYS_INLINE IntLiteral pattern_arg (int64_t x)
template<typename T >
HALIDE_ALWAYS_INLINE void assert_is_lvalue_if_expr ()
HALIDE_ALWAYS_INLINE SpecificExpr pattern_arg (const Expr &e)
template<typename T , typename = typename std::decay<T>::type::pattern_tag, typename = typename std::enable_if<!std::is_same<typename std::decay<T>::type, SpecificExpr>::value>::type>
HALIDE_ALWAYS_INLINE T unwrap (T t)
HALIDE_ALWAYS_INLINE const BaseExprNode & unwrap (const SpecificExpr &e)
std::ostream & operator<< (std::ostream &s, const IntLiteral &op)
template<typename Op >
int64_t constant_fold_bin_op (halide_type_t &, int64_t, int64_t) noexcept
template<typename Op >
uint64_t constant_fold_bin_op (halide_type_t &, uint64_t, uint64_t) noexcept
template<typename Op >
double constant_fold_bin_op (halide_type_t &, double, double) noexcept
constexpr bool commutative (IRNodeType t)
template<typename Op >
uint64_t constant_fold_cmp_op (int64_t, int64_t) noexcept
template<typename Op >
uint64_t constant_fold_cmp_op (uint64_t, uint64_t) noexcept
template<typename Op >
uint64_t constant_fold_cmp_op (double, double) noexcept
template<typename A , typename B >
std::ostream & operator<< (std::ostream &s, const BinOp< Add, A, B > &op)
template<typename A , typename B >
std::ostream & operator<< (std::ostream &s, const BinOp< Sub, A, B > &op)
template<typename A , typename B >
std::ostream & operator<< (std::ostream &s, const BinOp< Mul, A, B > &op)
template<typename A , typename B >
std::ostream & operator<< (std::ostream &s, const BinOp< Div, A, B > &op)
template<typename A , typename B >
std::ostream & operator<< (std::ostream &s, const BinOp< And, A, B > &op)
template<typename A , typename B >
std::ostream & operator<< (std::ostream &s, const BinOp< Or, A, B > &op)
template<typename A , typename B >
std::ostream & operator<< (std::ostream &s, const BinOp< Min, A, B > &op)
template<typename A , typename B >
std::ostream & operator<< (std::ostream &s, const BinOp< Max, A, B > &op)
template<typename A , typename B >
std::ostream & operator<< (std::ostream &s, const CmpOp< LE, A, B > &op)
template<typename A , typename B >
std::ostream & operator<< (std::ostream &s, const CmpOp< LT, A, B > &op)
template<typename A , typename B >
std::ostream & operator<< (std::ostream &s, const CmpOp< GE, A, B > &op)
template<typename A , typename B >
std::ostream & operator<< (std::ostream &s, const CmpOp< GT, A, B > &op)
template<typename A , typename B >
std::ostream & operator<< (std::ostream &s, const CmpOp< EQ, A, B > &op)
template<typename A , typename B >
std::ostream & operator<< (std::ostream &s, const CmpOp< NE, A, B > &op)
template<typename A , typename B >
std::ostream & operator<< (std::ostream &s, const BinOp< Mod, A, B > &op)
template<typename A , typename B >
HALIDE_ALWAYS_INLINE auto operator+ (A &&a, B &&b) noexcept -> BinOp< Add, decltype(pattern_arg(a)), decltype(pattern_arg(b))>
template<typename A , typename B >
HALIDE_ALWAYS_INLINE auto add (A &&a, B &&b) -> decltype(IRMatcher::operator+(a, b))
template<>
HALIDE_ALWAYS_INLINE int64_t constant_fold_bin_op< Add > (halide_type_t &t, int64_t a, int64_t b) noexcept
template<>
HALIDE_ALWAYS_INLINE uint64_t constant_fold_bin_op< Add > (halide_type_t &t, uint64_t a, uint64_t b) noexcept
template<>
HALIDE_ALWAYS_INLINE double constant_fold_bin_op< Add > (halide_type_t &t, double a, double b) noexcept
template<typename A , typename B >
HALIDE_ALWAYS_INLINE auto operator- (A &&a, B &&b) noexcept -> BinOp< Sub, decltype(pattern_arg(a)), decltype(pattern_arg(b))>
template<typename A , typename B >
HALIDE_ALWAYS_INLINE auto sub (A &&a, B &&b) -> decltype(IRMatcher::operator-(a, b))
template<>
HALIDE_ALWAYS_INLINE int64_t constant_fold_bin_op< Sub > (halide_type_t &t, int64_t a, int64_t b) noexcept
template<>
HALIDE_ALWAYS_INLINE uint64_t constant_fold_bin_op< Sub > (halide_type_t &t, uint64_t a, uint64_t b) noexcept
template<>
HALIDE_ALWAYS_INLINE double constant_fold_bin_op< Sub > (halide_type_t &t, double a, double b) noexcept
template<typename A , typename B >
HALIDE_ALWAYS_INLINE auto operator* (A &&a, B &&b) noexcept -> BinOp< Mul, decltype(pattern_arg(a)), decltype(pattern_arg(b))>
template<typename A , typename B >
HALIDE_ALWAYS_INLINE auto mul (A &&a, B &&b) -> decltype(IRMatcher::operator*(a, b))
template<>
HALIDE_ALWAYS_INLINE int64_t constant_fold_bin_op< Mul > (halide_type_t &t, int64_t a, int64_t b) noexcept
template<>
HALIDE_ALWAYS_INLINE uint64_t constant_fold_bin_op< Mul > (halide_type_t &t, uint64_t a, uint64_t b) noexcept
template<>
HALIDE_ALWAYS_INLINE double constant_fold_bin_op< Mul > (halide_type_t &t, double a, double b) noexcept
template<typename A , typename B >
HALIDE_ALWAYS_INLINE auto operator/ (A &&a, B &&b) noexcept -> BinOp< Div, decltype(pattern_arg(a)), decltype(pattern_arg(b))>
template<typename A , typename B >
HALIDE_ALWAYS_INLINE auto div (A &&a, B &&b) -> decltype(IRMatcher::operator/(a, b))
template<>
HALIDE_ALWAYS_INLINE int64_t constant_fold_bin_op< Div > (halide_type_t &t, int64_t a, int64_t b) noexcept
template<>
HALIDE_ALWAYS_INLINE uint64_t constant_fold_bin_op< Div > (halide_type_t &t, uint64_t a, uint64_t b) noexcept
template<>
HALIDE_ALWAYS_INLINE double constant_fold_bin_op< Div > (halide_type_t &t, double a, double b) noexcept
template<typename A , typename B >
HALIDE_ALWAYS_INLINE auto operator% (A &&a, B &&b) noexcept -> BinOp< Mod, decltype(pattern_arg(a)), decltype(pattern_arg(b))>
template<typename A , typename B >
HALIDE_ALWAYS_INLINE auto mod (A &&a, B &&b) -> decltype(IRMatcher::operator%(a, b))
template<>
HALIDE_ALWAYS_INLINE int64_t constant_fold_bin_op< Mod > (halide_type_t &t, int64_t a, int64_t b) noexcept
template<>
HALIDE_ALWAYS_INLINE uint64_t constant_fold_bin_op< Mod > (halide_type_t &t, uint64_t a, uint64_t b) noexcept
template<>
HALIDE_ALWAYS_INLINE double constant_fold_bin_op< Mod > (halide_type_t &t, double a, double b) noexcept
template<typename A , typename B >
HALIDE_ALWAYS_INLINE auto min (A &&a, B &&b) noexcept -> BinOp< Min, decltype(pattern_arg(a)), decltype(pattern_arg(b))>
template<>
HALIDE_ALWAYS_INLINE int64_t constant_fold_bin_op< Min > (halide_type_t &t, int64_t a, int64_t b) noexcept
template<>
HALIDE_ALWAYS_INLINE uint64_t constant_fold_bin_op< Min > (halide_type_t &t, uint64_t a, uint64_t b) noexcept
template<>
HALIDE_ALWAYS_INLINE double constant_fold_bin_op< Min > (halide_type_t &t, double a, double b) noexcept
template<typename A , typename B >
HALIDE_ALWAYS_INLINE auto max (A &&a, B &&b) noexcept -> BinOp< Max, decltype(pattern_arg(a)), decltype(pattern_arg(b))>
template<>
HALIDE_ALWAYS_INLINE int64_t constant_fold_bin_op< Max > (halide_type_t &t, int64_t a, int64_t b) noexcept
template<>
HALIDE_ALWAYS_INLINE uint64_t constant_fold_bin_op< Max > (halide_type_t &t, uint64_t a, uint64_t b) noexcept
template<>
HALIDE_ALWAYS_INLINE double constant_fold_bin_op< Max > (halide_type_t &t, double a, double b) noexcept
template<typename A , typename B >
HALIDE_ALWAYS_INLINE auto operator< (A &&a, B &&b) noexcept -> CmpOp< LT, decltype(pattern_arg(a)), decltype(pattern_arg(b))>
template<typename A , typename B >
HALIDE_ALWAYS_INLINE auto lt (A &&a, B &&b) -> decltype(IRMatcher::operator<(a, b))
template<>
HALIDE_ALWAYS_INLINE uint64_t constant_fold_cmp_op< LT > (int64_t a, int64_t b) noexcept
template<>
HALIDE_ALWAYS_INLINE uint64_t constant_fold_cmp_op< LT > (uint64_t a, uint64_t b) noexcept
template<>
HALIDE_ALWAYS_INLINE uint64_t constant_fold_cmp_op< LT > (double a, double b) noexcept
template<typename A , typename B >
HALIDE_ALWAYS_INLINE auto operator> (A &&a, B &&b) noexcept -> CmpOp< GT, decltype(pattern_arg(a)), decltype(pattern_arg(b))>
template<typename A , typename B >
HALIDE_ALWAYS_INLINE auto gt (A &&a, B &&b) -> decltype(IRMatcher::operator>(a, b))
template<>
HALIDE_ALWAYS_INLINE uint64_t constant_fold_cmp_op< GT > (int64_t a, int64_t b) noexcept
template<>
HALIDE_ALWAYS_INLINE uint64_t constant_fold_cmp_op< GT > (uint64_t a, uint64_t b) noexcept
template<>
HALIDE_ALWAYS_INLINE uint64_t constant_fold_cmp_op< GT > (double a, double b) noexcept
template<typename A , typename B >
HALIDE_ALWAYS_INLINE auto operator<= (A &&a, B &&b) noexcept -> CmpOp< LE, decltype(pattern_arg(a)), decltype(pattern_arg(b))>
template<typename A , typename B >
HALIDE_ALWAYS_INLINE auto le (A &&a, B &&b) -> decltype(IRMatcher::operator<=(a, b))
template<>
HALIDE_ALWAYS_INLINE uint64_t constant_fold_cmp_op< LE > (int64_t a, int64_t b) noexcept
template<>
HALIDE_ALWAYS_INLINE uint64_t constant_fold_cmp_op< LE > (uint64_t a, uint64_t b) noexcept
template<>
HALIDE_ALWAYS_INLINE uint64_t constant_fold_cmp_op< LE > (double a, double b) noexcept
template<typename A , typename B >
HALIDE_ALWAYS_INLINE auto operator>= (A &&a, B &&b) noexcept -> CmpOp< GE, decltype(pattern_arg(a)), decltype(pattern_arg(b))>
template<typename A , typename B >
HALIDE_ALWAYS_INLINE auto ge (A &&a, B &&b) -> decltype(IRMatcher::operator>=(a, b))
template<>
HALIDE_ALWAYS_INLINE uint64_t constant_fold_cmp_op< GE > (int64_t a, int64_t b) noexcept
template<>
HALIDE_ALWAYS_INLINE uint64_t constant_fold_cmp_op< GE > (uint64_t a, uint64_t b) noexcept
template<>
HALIDE_ALWAYS_INLINE uint64_t constant_fold_cmp_op< GE > (double a, double b) noexcept
template<typename A , typename B >
HALIDE_ALWAYS_INLINE auto operator== (A &&a, B &&b) noexcept -> CmpOp< EQ, decltype(pattern_arg(a)), decltype(pattern_arg(b))>
template<typename A , typename B >
HALIDE_ALWAYS_INLINE auto eq (A &&a, B &&b) -> decltype(IRMatcher::operator==(a, b))
template<>
HALIDE_ALWAYS_INLINE uint64_t constant_fold_cmp_op< EQ > (int64_t a, int64_t b) noexcept
template<>
HALIDE_ALWAYS_INLINE uint64_t constant_fold_cmp_op< EQ > (uint64_t a, uint64_t b) noexcept
template<>
HALIDE_ALWAYS_INLINE uint64_t constant_fold_cmp_op< EQ > (double a, double b) noexcept
template<typename A , typename B >
HALIDE_ALWAYS_INLINE auto operator!= (A &&a, B &&b) noexcept -> CmpOp< NE, decltype(pattern_arg(a)), decltype(pattern_arg(b))>
template<typename A , typename B >
HALIDE_ALWAYS_INLINE auto ne (A &&a, B &&b) -> decltype(IRMatcher::operator!=(a, b))
template<>
HALIDE_ALWAYS_INLINE uint64_t constant_fold_cmp_op< NE > (int64_t a, int64_t b) noexcept
template<>
HALIDE_ALWAYS_INLINE uint64_t constant_fold_cmp_op< NE > (uint64_t a, uint64_t b) noexcept
template<>
HALIDE_ALWAYS_INLINE uint64_t constant_fold_cmp_op< NE > (double a, double b) noexcept
template<typename A , typename B >
HALIDE_ALWAYS_INLINE auto operator|| (A &&a, B &&b) noexcept -> BinOp< Or, decltype(pattern_arg(a)), decltype(pattern_arg(b))>
template<typename A , typename B >
HALIDE_ALWAYS_INLINE auto or_op (A &&a, B &&b) -> decltype(IRMatcher::operator||(a, b))
template<>
HALIDE_ALWAYS_INLINE int64_t constant_fold_bin_op< Or > (halide_type_t &t, int64_t a, int64_t b) noexcept
template<>
HALIDE_ALWAYS_INLINE uint64_t constant_fold_bin_op< Or > (halide_type_t &t, uint64_t a, uint64_t b) noexcept
template<>
HALIDE_ALWAYS_INLINE double constant_fold_bin_op< Or > (halide_type_t &t, double a, double b) noexcept
template<typename A , typename B >
HALIDE_ALWAYS_INLINE auto operator&& (A &&a, B &&b) noexcept -> BinOp< And, decltype(pattern_arg(a)), decltype(pattern_arg(b))>
template<typename A , typename B >
HALIDE_ALWAYS_INLINE auto and_op (A &&a, B &&b) -> decltype(IRMatcher::operator&&(a, b))
template<>
HALIDE_ALWAYS_INLINE int64_t constant_fold_bin_op< And > (halide_type_t &t, int64_t a, int64_t b) noexcept
template<>
HALIDE_ALWAYS_INLINE uint64_t constant_fold_bin_op< And > (halide_type_t &t, uint64_t a, uint64_t b) noexcept
template<>
HALIDE_ALWAYS_INLINE double constant_fold_bin_op< And > (halide_type_t &t, double a, double b) noexcept
constexpr uint32_t bitwise_or_reduce ()
template<typename... Args>
constexpr uint32_t bitwise_or_reduce (uint32_t first, Args... rest)
constexpr bool and_reduce ()
template<typename... Args>
constexpr bool and_reduce (bool first, Args... rest)
constexpr int const_min (int a, int b)
template<typename... Args>
std::ostream & operator<< (std::ostream &s, const Intrin< Args... > &op)
template<typename... Args>
HALIDE_ALWAYS_INLINE auto intrin (Call::IntrinsicOp intrinsic_op, Args... args) noexcept -> Intrin< decltype(pattern_arg(args))... >
template<typename A , typename B >
auto widening_add (A &&a, B &&b) noexcept -> Intrin< decltype(pattern_arg(a)), decltype(pattern_arg(b))>
template<typename A , typename B >
auto widening_sub (A &&a, B &&b) noexcept -> Intrin< decltype(pattern_arg(a)), decltype(pattern_arg(b))>
template<typename A , typename B >
auto widening_mul (A &&a, B &&b) noexcept -> Intrin< decltype(pattern_arg(a)), decltype(pattern_arg(b))>
template<typename A , typename B >
auto saturating_add (A &&a, B &&b) noexcept -> Intrin< decltype(pattern_arg(a)), decltype(pattern_arg(b))>
template<typename A , typename B >
auto saturating_sub (A &&a, B &&b) noexcept -> Intrin< decltype(pattern_arg(a)), decltype(pattern_arg(b))>
template<typename A , typename B >
auto halving_add (A &&a, B &&b) noexcept -> Intrin< decltype(pattern_arg(a)), decltype(pattern_arg(b))>
template<typename A , typename B >
auto halving_sub (A &&a, B &&b) noexcept -> Intrin< decltype(pattern_arg(a)), decltype(pattern_arg(b))>
template<typename A , typename B >
auto rounding_halving_add (A &&a, B &&b) noexcept -> Intrin< decltype(pattern_arg(a)), decltype(pattern_arg(b))>
template<typename A , typename B >
auto rounding_halving_sub (A &&a, B &&b) noexcept -> Intrin< decltype(pattern_arg(a)), decltype(pattern_arg(b))>
template<typename A , typename B >
auto shift_left (A &&a, B &&b) noexcept -> Intrin< decltype(pattern_arg(a)), decltype(pattern_arg(b))>
template<typename A , typename B >
auto shift_right (A &&a, B &&b) noexcept -> Intrin< decltype(pattern_arg(a)), decltype(pattern_arg(b))>
template<typename A , typename B >
auto rounding_shift_left (A &&a, B &&b) noexcept -> Intrin< decltype(pattern_arg(a)), decltype(pattern_arg(b))>
template<typename A , typename B >
auto rounding_shift_right (A &&a, B &&b) noexcept -> Intrin< decltype(pattern_arg(a)), decltype(pattern_arg(b))>
template<typename A >
HALIDE_ALWAYS_INLINE auto operator! (A &&a) noexcept -> NotOp< decltype(pattern_arg(a))>
template<typename A >
HALIDE_ALWAYS_INLINE auto not_op (A &&a) -> decltype(IRMatcher::operator!(a))
template<typename A >
std::ostream & operator<< (std::ostream &s, const NotOp< A > &op)
template<typename C , typename T , typename F >
std::ostream & operator<< (std::ostream &s, const SelectOp< C, T, F > &op)
template<typename C , typename T , typename F >
HALIDE_ALWAYS_INLINE auto select (C &&c, T &&t, F &&f) noexcept -> SelectOp< decltype(pattern_arg(c)), decltype(pattern_arg(t)), decltype(pattern_arg(f))>
template<typename A , typename B >
std::ostream & operator<< (std::ostream &s, const BroadcastOp< A, B > &op)
template<typename A , typename B >
HALIDE_ALWAYS_INLINE auto broadcast (A &&a, B lanes) noexcept -> BroadcastOp< decltype(pattern_arg(a)), decltype(pattern_arg(lanes))>
template<typename A , typename B , typename C >
std::ostream & operator<< (std::ostream &s, const RampOp< A, B, C > &op)
template<typename A , typename B , typename C >
HALIDE_ALWAYS_INLINE auto ramp (A &&a, B &&b, C &&c) noexcept -> RampOp< decltype(pattern_arg(a)), decltype(pattern_arg(b)), decltype(pattern_arg(c))>
template<typename A , typename B , VectorReduce::Operator reduce_op>
std::ostream & operator<< (std::ostream &s, const VectorReduceOp< A, B, reduce_op > &op)
template<typename A , typename B >
HALIDE_ALWAYS_INLINE auto h_add (A &&a, B lanes) noexcept -> VectorReduceOp< decltype(pattern_arg(a)), decltype(pattern_arg(lanes)), VectorReduce::Add >
template<typename A , typename B >
HALIDE_ALWAYS_INLINE auto h_min (A &&a, B lanes) noexcept -> VectorReduceOp< decltype(pattern_arg(a)), decltype(pattern_arg(lanes)), VectorReduce::Min >
template<typename A , typename B >
HALIDE_ALWAYS_INLINE auto h_max (A &&a, B lanes) noexcept -> VectorReduceOp< decltype(pattern_arg(a)), decltype(pattern_arg(lanes)), VectorReduce::Max >
template<typename A , typename B >
HALIDE_ALWAYS_INLINE auto h_and (A &&a, B lanes) noexcept -> VectorReduceOp< decltype(pattern_arg(a)), decltype(pattern_arg(lanes)), VectorReduce::And >
template<typename A , typename B >
HALIDE_ALWAYS_INLINE auto h_or (A &&a, B lanes) noexcept -> VectorReduceOp< decltype(pattern_arg(a)), decltype(pattern_arg(lanes)), VectorReduce::Or >
template<typename A >
std::ostream & operator<< (std::ostream &s, const NegateOp< A > &op)
template<typename A >
HALIDE_ALWAYS_INLINE auto operator- (A &&a) noexcept -> NegateOp< decltype(pattern_arg(a))>
template<typename A >
HALIDE_ALWAYS_INLINE auto negate (A &&a) -> decltype(IRMatcher::operator-(a))
template<typename A >
std::ostream & operator<< (std::ostream &s, const CastOp< A > &op)
template<typename A >
HALIDE_ALWAYS_INLINE auto cast (halide_type_t t, A &&a) noexcept -> CastOp< decltype(pattern_arg(a))>
template<typename A >
HALIDE_ALWAYS_INLINE auto fold (A &&a) noexcept -> Fold< decltype(pattern_arg(a))>
template<typename A >
std::ostream & operator<< (std::ostream &s, const Fold< A > &op)
template<typename A >
HALIDE_ALWAYS_INLINE auto overflows (A &&a) noexcept -> Overflows< decltype(pattern_arg(a))>
template<typename A >
std::ostream & operator<< (std::ostream &s, const Overflows< A > &op)
std::ostream & operator<< (std::ostream &s, const Overflow &op)
template<typename A >
HALIDE_ALWAYS_INLINE auto is_const (A &&a) noexcept -> IsConst< decltype(pattern_arg(a))>
template<typename A >
std::ostream & operator<< (std::ostream &s, const IsConst< A > &op)
template<typename A , typename Prover >
HALIDE_ALWAYS_INLINE auto can_prove (A &&a, Prover *p) noexcept -> CanProve< decltype(pattern_arg(a)), Prover >
template<typename A , typename Prover >
std::ostream & operator<< (std::ostream &s, const CanProve< A, Prover > &op)
template<typename A >
HALIDE_ALWAYS_INLINE auto is_float (A &&a) noexcept -> IsFloat< decltype(pattern_arg(a))>
template<typename A >
std::ostream & operator<< (std::ostream &s, const IsFloat< A > &op)
template<typename A >
HALIDE_ALWAYS_INLINE auto is_int (A &&a, int bits=0) noexcept -> IsInt< decltype(pattern_arg(a))>
template<typename A >
std::ostream & operator<< (std::ostream &s, const IsInt< A > &op)
template<typename A >
HALIDE_ALWAYS_INLINE auto is_uint (A &&a, int bits=0) noexcept -> IsUInt< decltype(pattern_arg(a))>
template<typename A >
std::ostream & operator<< (std::ostream &s, const IsUInt< A > &op)
template<typename A >
HALIDE_ALWAYS_INLINE auto is_scalar (A &&a) noexcept -> IsScalar< decltype(pattern_arg(a))>
template<typename A >
HALIDE_ALWAYS_INLINE auto is_max_value (A &&a) noexcept -> IsMaxValue< decltype(pattern_arg(a))>
template<typename A >
HALIDE_ALWAYS_INLINE auto is_min_value (A &&a) noexcept -> IsMinValue< decltype(pattern_arg(a))>
template<typename A >
std::ostream & operator<< (std::ostream &s, const IsScalar< A > &op)
template<typename Before , typename After , typename Predicate , typename = typename std::enable_if<std::decay<Before>::type::foldable && std::decay<After>::type::foldable>::type>
HALIDE_NEVER_INLINE void fuzz_test_rule (Before &&before, After &&after, Predicate &&pred, halide_type_t wildcard_type, halide_type_t output_type) noexcept
template<typename Before , typename After , typename Predicate , typename = typename std::enable_if<!(std::decay<Before>::type::foldable && std::decay<After>::type::foldable)>::type>
HALIDE_ALWAYS_INLINE void fuzz_test_rule (Before &&before, After &&after, Predicate &&pred, halide_type_t, halide_type_t, int dummy=0) noexcept
HALIDE_ALWAYS_INLINE bool evaluate_predicate (bool x, MatcherState &) noexcept
template<typename Pattern , typename = typename enable_if_pattern<Pattern>::type>
HALIDE_ALWAYS_INLINE bool evaluate_predicate (Pattern p, MatcherState &state)
template<typename Instance , typename = typename enable_if_pattern<Instance>::type>
HALIDE_ALWAYS_INLINE auto rewriter (Instance instance, halide_type_t output_type, halide_type_t wildcard_type) noexcept -> Rewriter< decltype(pattern_arg(instance))>
Construct a rewriter for the given instance, which may be a pattern with concrete expressions as leaves, or just an expression.
template<typename Instance , typename = typename enable_if_pattern<Instance>::type>
HALIDE_ALWAYS_INLINE auto rewriter (Instance instance, halide_type_t output_type) noexcept -> Rewriter< decltype(pattern_arg(instance))>
HALIDE_ALWAYS_INLINE auto rewriter (const Expr &e, halide_type_t wildcard_type) noexcept -> Rewriter< decltype(pattern_arg(e))>
HALIDE_ALWAYS_INLINE auto rewriter (const Expr &e) noexcept -> Rewriter< decltype(pattern_arg(e))>
Variables
constexpr int max_wild = 6
Detailed Description
An alternative template-metaprogramming approach to expression matching.
Potentially more efficient. We lift the expression pattern into a type, and then use force-inlined functions to generate efficient matching and reconstruction code for any pattern. Pattern elements are either one of the classes in the namespace IRMatcher, or are non-null Exprs (represented as BaseExprNode &).
Pattern elements that are fully specified by their pattern can be built into an expression using the make method. Some patterns, such as a broadcast that matches any number of lanes, don't have enough information to recreate an Expr.
Function Documentation
make_const_special_expr()
HALIDE_NEVER_INLINE Expr Halide::Internal::IRMatcher::make_const_special_expr (halide_type_t ty) inline
Definition at line 145 of file IRMatch.h.
References halide_type_t::lanes, Halide::Internal::make_signed_integer_overflow(), Halide::Internal::IRMatcher::MatcherState::signed_integer_overflow, and Halide::Internal::IRMatcher::MatcherState::special_values_mask.
Referenced by Halide::Internal::IRMatcher::Overflow::make(), and make_const_expr().
make_const_expr()
HALIDE_ALWAYS_INLINE Expr Halide::Internal::IRMatcher::make_const_expr (halide_scalar_value_t val, halide_type_t ty)
Definition at line 156 of file IRMatch.h.
References halide_type_t::code, halide_scalar_value_t::f64, halide_type_bfloat, halide_type_float, halide_type_int, halide_type_uint, halide_scalar_value_t::i64, halide_type_t::lanes, Halide::Internal::Broadcast::make(), Halide::Internal::FloatImm::make(), Halide::Internal::IntImm::make(), Halide::Internal::UIntImm::make(), make_const_special_expr(), Halide::Internal::IRMatcher::MatcherState::special_values_mask, halide_scalar_value_t::u, and halide_scalar_value_t::u64.
Referenced by fuzz_test_rule(), Halide::Internal::IRMatcher::WildConstInt< i >::make(), Halide::Internal::IRMatcher::WildConstUInt< i >::make(), Halide::Internal::IRMatcher::WildConstFloat< i >::make(), Halide::Internal::IRMatcher::WildConst< i >::make(), and Halide::Internal::IRMatcher::Fold< A >::make().
equal_helper()
bool Halide::Internal::IRMatcher::equal_helper (const BaseExprNode & a, const BaseExprNode & b) noexcept
Referenced by equal().
equal()
HALIDE_ALWAYS_INLINE bool Halide::Internal::IRMatcher::equal (const BaseExprNode & a, const BaseExprNode & b) noexcept
Definition at line 191 of file IRMatch.h.
References equal_helper().
Referenced by Halide::Internal::IRMatcher::SpecificExpr::match(), and Halide::Internal::IRMatcher::Wild< i >::match().
operator<<() [1/39]
std::ostream& Halide::Internal::IRMatcher::operator<< (std::ostream & s, const SpecificExpr & e) inline
Definition at line 225 of file IRMatch.h.
References Halide::Internal::IRMatcher::SpecificExpr::expr.
operator<<() [2/39]
template<int i> std::ostream& Halide::Internal::IRMatcher::operator<< (std::ostream & s, const WildConstInt< i > & c)
Definition at line 291 of file IRMatch.h.
operator<<() [3/39]
template<int i> std::ostream& Halide::Internal::IRMatcher::operator<< (std::ostream & s, const WildConstUInt< i > & c)
Definition at line 344 of file IRMatch.h.
operator<<() [4/39]
template<int i> std::ostream& Halide::Internal::IRMatcher::operator<< (std::ostream & s, const WildConstFloat< i > & c)
Definition at line 397 of file IRMatch.h.
operator<<() [5/39]
template<int i> std::ostream& Halide::Internal::IRMatcher::operator<< (std::ostream & s, const WildConst< i > & c)
Definition at line 455 of file IRMatch.h.
operator<<() [6/39]
template<int i> std::ostream& Halide::Internal::IRMatcher::operator<< (std::ostream & s, const Wild< i > & op)
Definition at line 512 of file IRMatch.h.
unwrap() [1/3]
HALIDE_ALWAYS_INLINE int64_t Halide::Internal::IRMatcher::unwrap (IntLiteral t)
Definition at line 590 of file IRMatch.h.
References Halide::Internal::IRMatcher::IntLiteral::v.
Referenced by Halide::Internal::IRMatcher::BinOp< Op, A, B >::match(), Halide::Internal::IRMatcher::BroadcastOp< A, B >::match(), Halide::Internal::IRMatcher::CastOp< A >::match(), Halide::Internal::IRMatcher::CmpOp< Op, A, B >::match(), Halide::Internal::IRMatcher::NotOp< A >::match(), Halide::Internal::IRMatcher::RampOp< A, B, C >::match(), Halide::Internal::IRMatcher::SelectOp< C, T, F >::match(), Halide::Internal::IRMatcher::VectorReduceOp< A, B, reduce_op >::match(), Halide::Internal::IRMatcher::NegateOp< A >::match(), and Halide::Internal::IRMatcher::Rewriter< Instance >::operator()().
pattern_arg() [1/3]
template<typename T , typename = typename std::decay<T>::type::pattern_tag> HALIDE_ALWAYS_INLINE T Halide::Internal::IRMatcher::pattern_arg (T t)
Definition at line 598 of file IRMatch.h.
Referenced by broadcast(), can_prove(), cast(), fold(), h_add(), h_and(), h_max(), h_min(), h_or(), halving_add(), halving_sub(), intrin(), is_const(), is_float(), is_int(), is_max_value(), is_min_value(), is_scalar(), is_uint(), max(), min(), operator!(), operator!=(), operator%(), operator&&(), operator*(), operator+(), operator-(), operator/(), operator<(), operator<=(), operator==(), operator>(), operator>=(), operator||(), overflows(), ramp(), rewriter(), rounding_halving_add(), rounding_halving_sub(), rounding_shift_left(), rounding_shift_right(), saturating_add(), saturating_sub(), select(), shift_left(), shift_right(), widening_add(), widening_mul(), and widening_sub().
pattern_arg() [2/3]
HALIDE_ALWAYS_INLINE IntLiteral Halide::Internal::IRMatcher::pattern_arg (int64_t x)
Definition at line 602 of file IRMatch.h.
assert_is_lvalue_if_expr()
template<typename T > HALIDE_ALWAYS_INLINE void Halide::Internal::IRMatcher::assert_is_lvalue_if_expr ()
Definition at line 607 of file IRMatch.h.
pattern_arg() [3/3]
HALIDE_ALWAYS_INLINE SpecificExpr Halide::Internal::IRMatcher::pattern_arg (const Expr & e)
Definition at line 612 of file IRMatch.h.
References Halide::Expr::get().
unwrap() [2/3]
template<typename T , typename = typename std::decay<T>::type::pattern_tag, typename = typename std::enable_if<!std::is_same<typename std::decay<T>::type, SpecificExpr>::value>::type> HALIDE_ALWAYS_INLINE T Halide::Internal::IRMatcher::unwrap (T t)
Definition at line 623 of file IRMatch.h.
unwrap() [3/3]
HALIDE_ALWAYS_INLINE const BaseExprNode& Halide::Internal::IRMatcher::unwrap (const SpecificExpr & e)
Definition at line 628 of file IRMatch.h.
References Halide::Internal::IRMatcher::SpecificExpr::expr.
operator<<() [7/39]
std::ostream& Halide::Internal::IRMatcher::operator<< (std::ostream & s, const IntLiteral & op) inline
Definition at line 632 of file IRMatch.h.
References Halide::Internal::IRMatcher::IntLiteral::v.
constant_fold_bin_op() [1/3]
template<typename Op > int64_t Halide::Internal::IRMatcher::constant_fold_bin_op (halide_type_t & , int64_t , int64_t) noexcept
constant_fold_bin_op() [2/3]
template<typename Op > uint64_t Halide::Internal::IRMatcher::constant_fold_bin_op (halide_type_t & , uint64_t , uint64_t) noexcept
constant_fold_bin_op() [3/3]
template<typename Op > double Halide::Internal::IRMatcher::constant_fold_bin_op (halide_type_t & , double , double) noexcept
commutative()
constexpr bool Halide::Internal::IRMatcher::commutative (IRNodeType t) constexpr
Definition at line 646 of file IRMatch.h.
References Halide::Internal::Add, Halide::Internal::And, Halide::Internal::EQ, Halide::Internal::Max, Halide::Internal::Min, Halide::Internal::Mul, Halide::Internal::NE, and Halide::Internal::Or.
constant_fold_cmp_op() [1/3]
template<typename Op > uint64_t Halide::Internal::IRMatcher::constant_fold_cmp_op (int64_t , int64_t) noexcept
constant_fold_cmp_op() [2/3]
template<typename Op > uint64_t Halide::Internal::IRMatcher::constant_fold_cmp_op (uint64_t , uint64_t) noexcept
constant_fold_cmp_op() [3/3]
template<typename Op > uint64_t Halide::Internal::IRMatcher::constant_fold_cmp_op (double , double) noexcept
operator<<() [8/39]
template<typename A , typename B > std::ostream& Halide::Internal::IRMatcher::operator<< (std::ostream & s, const BinOp< Add, A, B > & op)
Definition at line 862 of file IRMatch.h.
References Halide::Internal::IRMatcher::BinOp< Op, A, B >::a, and Halide::Internal::IRMatcher::BinOp< Op, A, B >::b.
operator<<() [9/39]
template<typename A , typename B > std::ostream& Halide::Internal::IRMatcher::operator<< (std::ostream & s, const BinOp< Sub, A, B > & op)
Definition at line 868 of file IRMatch.h.
References Halide::Internal::IRMatcher::BinOp< Op, A, B >::a, and Halide::Internal::IRMatcher::BinOp< Op, A, B >::b.
operator<<() [10/39]
template<typename A , typename B > std::ostream& Halide::Internal::IRMatcher::operator<< (std::ostream & s, const BinOp< Mul, A, B > & op)
Definition at line 874 of file IRMatch.h.
References Halide::Internal::IRMatcher::BinOp< Op, A, B >::a, and Halide::Internal::IRMatcher::BinOp< Op, A, B >::b.
operator<<() [11/39]
template<typename A , typename B > std::ostream& Halide::Internal::IRMatcher::operator<< (std::ostream & s, const BinOp< Div, A, B > & op)
Definition at line 880 of file IRMatch.h.
References Halide::Internal::IRMatcher::BinOp< Op, A, B >::a, and Halide::Internal::IRMatcher::BinOp< Op, A, B >::b.
operator<<() [12/39]
template<typename A , typename B > std::ostream& Halide::Internal::IRMatcher::operator<< (std::ostream & s, const BinOp< And, A, B > & op)
Definition at line 886 of file IRMatch.h.
References Halide::Internal::IRMatcher::BinOp< Op, A, B >::a, and Halide::Internal::IRMatcher::BinOp< Op, A, B >::b.
operator<<() [13/39]
template<typename A , typename B > std::ostream& Halide::Internal::IRMatcher::operator<< (std::ostream & s, const BinOp< Or, A, B > & op)
Definition at line 892 of file IRMatch.h.
References Halide::Internal::IRMatcher::BinOp< Op, A, B >::a, and Halide::Internal::IRMatcher::BinOp< Op, A, B >::b.
operator<<() [14/39]
template<typename A , typename B > std::ostream& Halide::Internal::IRMatcher::operator<< (std::ostream & s, const BinOp< Min, A, B > & op)
Definition at line 898 of file IRMatch.h.
References Halide::Internal::IRMatcher::BinOp< Op, A, B >::a, and Halide::Internal::IRMatcher::BinOp< Op, A, B >::b.
operator<<() [15/39]
template<typename A , typename B > std::ostream& Halide::Internal::IRMatcher::operator<< (std::ostream & s, const BinOp< Max, A, B > & op)
Definition at line 904 of file IRMatch.h.
References Halide::Internal::IRMatcher::BinOp< Op, A, B >::a, and Halide::Internal::IRMatcher::BinOp< Op, A, B >::b.
operator<<() [16/39]
template<typename A , typename B > std::ostream& Halide::Internal::IRMatcher::operator<< (std::ostream & s, const CmpOp< LE, A, B > & op)
Definition at line 910 of file IRMatch.h.
References Halide::Internal::IRMatcher::CmpOp< Op, A, B >::a, and Halide::Internal::IRMatcher::CmpOp< Op, A, B >::b.
operator<<() [17/39]
template<typename A , typename B > std::ostream& Halide::Internal::IRMatcher::operator<< (std::ostream & s, const CmpOp< LT, A, B > & op)
Definition at line 916 of file IRMatch.h.
References Halide::Internal::IRMatcher::CmpOp< Op, A, B >::a, and Halide::Internal::IRMatcher::CmpOp< Op, A, B >::b.
operator<<() [18/39]
template<typename A , typename B > std::ostream& Halide::Internal::IRMatcher::operator<< (std::ostream & s, const CmpOp< GE, A, B > & op)
Definition at line 922 of file IRMatch.h.
References Halide::Internal::IRMatcher::CmpOp< Op, A, B >::a, and Halide::Internal::IRMatcher::CmpOp< Op, A, B >::b.
operator<<() [19/39]
template<typename A , typename B > std::ostream& Halide::Internal::IRMatcher::operator<< (std::ostream & s, const CmpOp< GT, A, B > & op)
Definition at line 928 of file IRMatch.h.
References Halide::Internal::IRMatcher::CmpOp< Op, A, B >::a, and Halide::Internal::IRMatcher::CmpOp< Op, A, B >::b.
operator<<() [20/39]
template<typename A , typename B > std::ostream& Halide::Internal::IRMatcher::operator<< (std::ostream & s, const CmpOp< EQ, A, B > & op)
Definition at line 934 of file IRMatch.h.
References Halide::Internal::IRMatcher::CmpOp< Op, A, B >::a, and Halide::Internal::IRMatcher::CmpOp< Op, A, B >::b.
operator<<() [21/39]
template<typename A , typename B > std::ostream& Halide::Internal::IRMatcher::operator<< (std::ostream & s, const CmpOp< NE, A, B > & op)
Definition at line 940 of file IRMatch.h.
References Halide::Internal::IRMatcher::CmpOp< Op, A, B >::a, and Halide::Internal::IRMatcher::CmpOp< Op, A, B >::b.
operator<<() [22/39]
template<typename A , typename B > std::ostream& Halide::Internal::IRMatcher::operator<< (std::ostream & s, const BinOp< Mod, A, B > & op)
Definition at line 946 of file IRMatch.h.
References Halide::Internal::IRMatcher::BinOp< Op, A, B >::a, and Halide::Internal::IRMatcher::BinOp< Op, A, B >::b.
operator+()
template<typename A , typename B > HALIDE_ALWAYS_INLINE auto Halide::Internal::IRMatcher::operator+ (A && a, B && b) -> BinOp<Add, decltype(pattern_arg(a)), decltype(pattern_arg(b))> noexcept
Definition at line 952 of file IRMatch.h.
References pattern_arg().
Referenced by add().
add()
template<typename A , typename B > HALIDE_ALWAYS_INLINE auto Halide::Internal::IRMatcher::add (A && a, B && b) -> decltype(IRMatcher::operator+(a, b))
Definition at line 959 of file IRMatch.h.
References operator+().
constant_fold_bin_op< Add >() [1/3]
template<> HALIDE_ALWAYS_INLINE int64_t Halide::Internal::IRMatcher::constant_fold_bin_op< Add > (halide_type_t & t, int64_t a, int64_t b) noexcept
Definition at line 966 of file IRMatch.h.
References Halide::Internal::add_would_overflow(), and Halide::Internal::IRMatcher::MatcherState::signed_integer_overflow.
Referenced by fuzz_test_rule().
constant_fold_bin_op< Add >() [2/3]
template<> HALIDE_ALWAYS_INLINE uint64_t Halide::Internal::IRMatcher::constant_fold_bin_op< Add > (halide_type_t & t, uint64_t a, uint64_t b) noexcept
Definition at line 974 of file IRMatch.h.
constant_fold_bin_op< Add >() [3/3]
template<> HALIDE_ALWAYS_INLINE double Halide::Internal::IRMatcher::constant_fold_bin_op< Add > (halide_type_t & t, double a, double b) noexcept
Definition at line 980 of file IRMatch.h.
operator-() [1/2]
template<typename A , typename B > HALIDE_ALWAYS_INLINE auto Halide::Internal::IRMatcher::operator- (A && a, B && b) -> BinOp<Sub, decltype(pattern_arg(a)), decltype(pattern_arg(b))> noexcept
Definition at line 985 of file IRMatch.h.
References pattern_arg().
Referenced by negate(), and sub().
sub()
template<typename A , typename B > HALIDE_ALWAYS_INLINE auto Halide::Internal::IRMatcher::sub (A && a, B && b) -> decltype(IRMatcher::operator-(a, b))
Definition at line 992 of file IRMatch.h.
References operator-().
constant_fold_bin_op< Sub >() [1/3]
template<> HALIDE_ALWAYS_INLINE int64_t Halide::Internal::IRMatcher::constant_fold_bin_op< Sub > (halide_type_t & t, int64_t a, int64_t b) noexcept
Definition at line 999 of file IRMatch.h.
References Halide::Internal::IRMatcher::MatcherState::signed_integer_overflow, and Halide::Internal::sub_would_overflow().
constant_fold_bin_op< Sub >() [2/3]
template<> HALIDE_ALWAYS_INLINE uint64_t Halide::Internal::IRMatcher::constant_fold_bin_op< Sub > (halide_type_t & t, uint64_t a, uint64_t b) noexcept
Definition at line 1007 of file IRMatch.h.
constant_fold_bin_op< Sub >() [3/3]
template<> HALIDE_ALWAYS_INLINE double Halide::Internal::IRMatcher::constant_fold_bin_op< Sub > (halide_type_t & t, double a, double b) noexcept
Definition at line 1013 of file IRMatch.h.
operator*()
template<typename A , typename B > HALIDE_ALWAYS_INLINE auto Halide::Internal::IRMatcher::operator* (A && a, B && b) -> BinOp<Mul, decltype(pattern_arg(a)), decltype(pattern_arg(b))> noexcept
Definition at line 1018 of file IRMatch.h.
References pattern_arg().
Referenced by mul().
mul()
template<typename A , typename B > HALIDE_ALWAYS_INLINE auto Halide::Internal::IRMatcher::mul (A && a, B && b) -> decltype(IRMatcher::operator*(a, b))
Definition at line 1025 of file IRMatch.h.
References operator*().
constant_fold_bin_op< Mul >() [1/3]
template<> HALIDE_ALWAYS_INLINE int64_t Halide::Internal::IRMatcher::constant_fold_bin_op< Mul > (halide_type_t & t, int64_t a, int64_t b) noexcept
Definition at line 1032 of file IRMatch.h.
References Halide::Internal::mul_would_overflow(), and Halide::Internal::IRMatcher::MatcherState::signed_integer_overflow.
constant_fold_bin_op< Mul >() [2/3]
template<> HALIDE_ALWAYS_INLINE uint64_t Halide::Internal::IRMatcher::constant_fold_bin_op< Mul > (halide_type_t & t, uint64_t a, uint64_t b) noexcept
Definition at line 1040 of file IRMatch.h.
constant_fold_bin_op< Mul >() [3/3]
template<> HALIDE_ALWAYS_INLINE double Halide::Internal::IRMatcher::constant_fold_bin_op< Mul > (halide_type_t & t, double a, double b) noexcept
Definition at line 1046 of file IRMatch.h.
operator/()
template<typename A , typename B > HALIDE_ALWAYS_INLINE auto Halide::Internal::IRMatcher::operator/ (A && a, B && b) -> BinOp<Div, decltype(pattern_arg(a)), decltype(pattern_arg(b))> noexcept
Definition at line 1051 of file IRMatch.h.
References pattern_arg().
Referenced by div().
div()
template<typename A , typename B > HALIDE_ALWAYS_INLINE auto Halide::Internal::IRMatcher::div (A && a, B && b) -> decltype(IRMatcher::operator/(a, b))
Definition at line 1058 of file IRMatch.h.
References operator/().
constant_fold_bin_op< Div >() [1/3]
template<> HALIDE_ALWAYS_INLINE int64_t Halide::Internal::IRMatcher::constant_fold_bin_op< Div > (halide_type_t & t, int64_t a, int64_t b) noexcept
Definition at line 1063 of file IRMatch.h.
References Halide::Internal::div_imp().
constant_fold_bin_op< Div >() [2/3]
template<> HALIDE_ALWAYS_INLINE uint64_t Halide::Internal::IRMatcher::constant_fold_bin_op< Div > (halide_type_t & t, uint64_t a, uint64_t b) noexcept
Definition at line 1068 of file IRMatch.h.
References Halide::Internal::div_imp().
constant_fold_bin_op< Div >() [3/3]
template<> HALIDE_ALWAYS_INLINE double Halide::Internal::IRMatcher::constant_fold_bin_op< Div > (halide_type_t & t, double a, double b) noexcept
Definition at line 1073 of file IRMatch.h.
References Halide::Internal::div_imp().
operator%()
template<typename A , typename B > HALIDE_ALWAYS_INLINE auto Halide::Internal::IRMatcher::operator% (A && a, B && b) -> BinOp<Mod, decltype(pattern_arg(a)), decltype(pattern_arg(b))> noexcept
Definition at line 1078 of file IRMatch.h.
References pattern_arg().
Referenced by mod().
mod()
template<typename A , typename B > HALIDE_ALWAYS_INLINE auto Halide::Internal::IRMatcher::mod (A && a, B && b) -> decltype(IRMatcher::operator%(a, b))
Definition at line 1085 of file IRMatch.h.
References operator%().
Referenced by Halide::Internal::GPUCompilationCache< ContextT, ModuleStateT >::kernel_state_setup(), and Halide::Internal::GPUCompilationCache< ContextT, ModuleStateT >::release_hold().
constant_fold_bin_op< Mod >() [1/3]
template<> HALIDE_ALWAYS_INLINE int64_t Halide::Internal::IRMatcher::constant_fold_bin_op< Mod > (halide_type_t & t, int64_t a, int64_t b) noexcept
Definition at line 1092 of file IRMatch.h.
References Halide::Internal::mod_imp().
constant_fold_bin_op< Mod >() [2/3]
template<> HALIDE_ALWAYS_INLINE uint64_t Halide::Internal::IRMatcher::constant_fold_bin_op< Mod > (halide_type_t & t, uint64_t a, uint64_t b) noexcept
Definition at line 1097 of file IRMatch.h.
References Halide::Internal::mod_imp().
constant_fold_bin_op< Mod >() [3/3]
template<> HALIDE_ALWAYS_INLINE double Halide::Internal::IRMatcher::constant_fold_bin_op< Mod > (halide_type_t & t, double a, double b) noexcept
Definition at line 1102 of file IRMatch.h.
References Halide::Internal::mod_imp().
min()
template<typename A , typename B > HALIDE_ALWAYS_INLINE auto Halide::Internal::IRMatcher::min (A && a, B && b) -> BinOp<Min, decltype(pattern_arg(a)), decltype(pattern_arg(b))> noexcept
Definition at line 1107 of file IRMatch.h.
References pattern_arg().
Referenced by constant_fold_bin_op< Min >().
constant_fold_bin_op< Min >() [1/3]
template<> HALIDE_ALWAYS_INLINE int64_t Halide::Internal::IRMatcher::constant_fold_bin_op< Min > (halide_type_t & t, int64_t a, int64_t b) noexcept
Definition at line 1114 of file IRMatch.h.
References min().
constant_fold_bin_op< Min >() [2/3]
template<> HALIDE_ALWAYS_INLINE uint64_t Halide::Internal::IRMatcher::constant_fold_bin_op< Min > (halide_type_t & t, uint64_t a, uint64_t b) noexcept
Definition at line 1119 of file IRMatch.h.
References min().
constant_fold_bin_op< Min >() [3/3]
template<> HALIDE_ALWAYS_INLINE double Halide::Internal::IRMatcher::constant_fold_bin_op< Min > (halide_type_t & t, double a, double b) noexcept
Definition at line 1124 of file IRMatch.h.
References min().
max()
template<typename A , typename B > HALIDE_ALWAYS_INLINE auto Halide::Internal::IRMatcher::max (A && a, B && b) -> BinOp<Max, decltype(pattern_arg(a)), decltype(pattern_arg(b))> noexcept
Definition at line 1129 of file IRMatch.h.
References pattern_arg().
Referenced by constant_fold_bin_op< Max >().
constant_fold_bin_op< Max >() [1/3]
template<> HALIDE_ALWAYS_INLINE int64_t Halide::Internal::IRMatcher::constant_fold_bin_op< Max > (halide_type_t & t, int64_t a, int64_t b) noexcept
Definition at line 1136 of file IRMatch.h.
References max().
constant_fold_bin_op< Max >() [2/3]
template<> HALIDE_ALWAYS_INLINE uint64_t Halide::Internal::IRMatcher::constant_fold_bin_op< Max > (halide_type_t & t, uint64_t a, uint64_t b) noexcept
Definition at line 1141 of file IRMatch.h.
References max().
constant_fold_bin_op< Max >() [3/3]
template<> HALIDE_ALWAYS_INLINE double Halide::Internal::IRMatcher::constant_fold_bin_op< Max > (halide_type_t & t, double a, double b) noexcept
Definition at line 1146 of file IRMatch.h.
References max().
operator<()
template<typename A , typename B > HALIDE_ALWAYS_INLINE auto Halide::Internal::IRMatcher::operator< (A && a, B && b) -> CmpOp<LT, decltype(pattern_arg(a)), decltype(pattern_arg(b))> noexcept
Definition at line 1151 of file IRMatch.h.
References pattern_arg().
Referenced by lt().
lt()
template<typename A , typename B > HALIDE_ALWAYS_INLINE auto Halide::Internal::IRMatcher::lt (A && a, B && b) -> decltype(IRMatcher::operator<(a, b))
Definition at line 1156 of file IRMatch.h.
References operator<().
constant_fold_cmp_op< LT >() [1/3]
template<> HALIDE_ALWAYS_INLINE uint64_t Halide::Internal::IRMatcher::constant_fold_cmp_op< LT > (int64_t a, int64_t b) noexcept
Definition at line 1161 of file IRMatch.h.
constant_fold_cmp_op< LT >() [2/3]
template<> HALIDE_ALWAYS_INLINE uint64_t Halide::Internal::IRMatcher::constant_fold_cmp_op< LT > (uint64_t a, uint64_t b) noexcept
Definition at line 1166 of file IRMatch.h.
constant_fold_cmp_op< LT >() [3/3]
template<> HALIDE_ALWAYS_INLINE uint64_t Halide::Internal::IRMatcher::constant_fold_cmp_op< LT > (double a, double b) noexcept
Definition at line 1171 of file IRMatch.h.
operator>()
template<typename A , typename B > HALIDE_ALWAYS_INLINE auto Halide::Internal::IRMatcher::operator> (A && a, B && b) -> CmpOp<GT, decltype(pattern_arg(a)), decltype(pattern_arg(b))> noexcept
Definition at line 1176 of file IRMatch.h.
References pattern_arg().
Referenced by gt().
gt()
template<typename A , typename B > HALIDE_ALWAYS_INLINE auto Halide::Internal::IRMatcher::gt (A && a, B && b) -> decltype(IRMatcher::operator>(a, b))
Definition at line 1181 of file IRMatch.h.
References operator>().
constant_fold_cmp_op< GT >() [1/3]
template<> HALIDE_ALWAYS_INLINE uint64_t Halide::Internal::IRMatcher::constant_fold_cmp_op< GT > (int64_t a, int64_t b) noexcept
Definition at line 1186 of file IRMatch.h.
constant_fold_cmp_op< GT >() [2/3]
template<> HALIDE_ALWAYS_INLINE uint64_t Halide::Internal::IRMatcher::constant_fold_cmp_op< GT > (uint64_t a, uint64_t b) noexcept
Definition at line 1191 of file IRMatch.h.
constant_fold_cmp_op< GT >() [3/3]
template<> HALIDE_ALWAYS_INLINE uint64_t Halide::Internal::IRMatcher::constant_fold_cmp_op< GT > (double a, double b) noexcept
Definition at line 1196 of file IRMatch.h.
operator<=()
template<typename A , typename B > HALIDE_ALWAYS_INLINE auto Halide::Internal::IRMatcher::operator<= (A && a, B && b) -> CmpOp<LE, decltype(pattern_arg(a)), decltype(pattern_arg(b))> noexcept
Definition at line 1201 of file IRMatch.h.
References pattern_arg().
Referenced by le().
le()
template<typename A , typename B > HALIDE_ALWAYS_INLINE auto Halide::Internal::IRMatcher::le (A && a, B && b) -> decltype(IRMatcher::operator<=(a, b))
Definition at line 1206 of file IRMatch.h.
References operator<=().
constant_fold_cmp_op< LE >() [1/3]
template<> HALIDE_ALWAYS_INLINE uint64_t Halide::Internal::IRMatcher::constant_fold_cmp_op< LE > (int64_t a, int64_t b) noexcept
Definition at line 1211 of file IRMatch.h.
constant_fold_cmp_op< LE >() [2/3]
template<> HALIDE_ALWAYS_INLINE uint64_t Halide::Internal::IRMatcher::constant_fold_cmp_op< LE > (uint64_t a, uint64_t b) noexcept
Definition at line 1216 of file IRMatch.h.
constant_fold_cmp_op< LE >() [3/3]
template<> HALIDE_ALWAYS_INLINE uint64_t Halide::Internal::IRMatcher::constant_fold_cmp_op< LE > (double a, double b) noexcept
Definition at line 1221 of file IRMatch.h.
operator>=()
template<typename A , typename B > HALIDE_ALWAYS_INLINE auto Halide::Internal::IRMatcher::operator>= (A && a, B && b) -> CmpOp<GE, decltype(pattern_arg(a)), decltype(pattern_arg(b))> noexcept
Definition at line 1226 of file IRMatch.h.
References pattern_arg().
Referenced by ge().
ge()
template<typename A , typename B > HALIDE_ALWAYS_INLINE auto Halide::Internal::IRMatcher::ge (A && a, B && b) -> decltype(IRMatcher::operator>=(a, b))
Definition at line 1231 of file IRMatch.h.
References operator>=().
constant_fold_cmp_op< GE >() [1/3]
template<> HALIDE_ALWAYS_INLINE uint64_t Halide::Internal::IRMatcher::constant_fold_cmp_op< GE > (int64_t a, int64_t b) noexcept
Definition at line 1236 of file IRMatch.h.
constant_fold_cmp_op< GE >() [2/3]
template<> HALIDE_ALWAYS_INLINE uint64_t Halide::Internal::IRMatcher::constant_fold_cmp_op< GE > (uint64_t a, uint64_t b) noexcept
Definition at line 1241 of file IRMatch.h.
constant_fold_cmp_op< GE >() [3/3]
template<> HALIDE_ALWAYS_INLINE uint64_t Halide::Internal::IRMatcher::constant_fold_cmp_op< GE > (double a, double b) noexcept
Definition at line 1246 of file IRMatch.h.
operator==()
template<typename A , typename B > HALIDE_ALWAYS_INLINE auto Halide::Internal::IRMatcher::operator== (A && a, B && b) -> CmpOp<EQ, decltype(pattern_arg(a)), decltype(pattern_arg(b))> noexcept
Definition at line 1251 of file IRMatch.h.
References pattern_arg().
Referenced by eq().
eq()
template<typename A , typename B > HALIDE_ALWAYS_INLINE auto Halide::Internal::IRMatcher::eq (A && a, B && b) -> decltype(IRMatcher::operator==(a, b))
Definition at line 1256 of file IRMatch.h.
References operator==().
constant_fold_cmp_op< EQ >() [1/3]
template<> HALIDE_ALWAYS_INLINE uint64_t Halide::Internal::IRMatcher::constant_fold_cmp_op< EQ > (int64_t a, int64_t b) noexcept
Definition at line 1261 of file IRMatch.h.
constant_fold_cmp_op< EQ >() [2/3]
template<> HALIDE_ALWAYS_INLINE uint64_t Halide::Internal::IRMatcher::constant_fold_cmp_op< EQ > (uint64_t a, uint64_t b) noexcept
Definition at line 1266 of file IRMatch.h.
constant_fold_cmp_op< EQ >() [3/3]
template<> HALIDE_ALWAYS_INLINE uint64_t Halide::Internal::IRMatcher::constant_fold_cmp_op< EQ > (double a, double b) noexcept
Definition at line 1271 of file IRMatch.h.
operator!=()
template<typename A , typename B > HALIDE_ALWAYS_INLINE auto Halide::Internal::IRMatcher::operator!= (A && a, B && b) -> CmpOp<NE, decltype(pattern_arg(a)), decltype(pattern_arg(b))> noexcept
Definition at line 1276 of file IRMatch.h.
References pattern_arg().
Referenced by ne().
ne()
template<typename A , typename B > HALIDE_ALWAYS_INLINE auto Halide::Internal::IRMatcher::ne (A && a, B && b) -> decltype(IRMatcher::operator!=(a, b))
Definition at line 1281 of file IRMatch.h.
References operator!=().
constant_fold_cmp_op< NE >() [1/3]
template<> HALIDE_ALWAYS_INLINE uint64_t Halide::Internal::IRMatcher::constant_fold_cmp_op< NE > (int64_t a, int64_t b) noexcept
Definition at line 1286 of file IRMatch.h.
constant_fold_cmp_op< NE >() [2/3]
template<> HALIDE_ALWAYS_INLINE uint64_t Halide::Internal::IRMatcher::constant_fold_cmp_op< NE > (uint64_t a, uint64_t b) noexcept
Definition at line 1291 of file IRMatch.h.
constant_fold_cmp_op< NE >() [3/3]
template<> HALIDE_ALWAYS_INLINE uint64_t Halide::Internal::IRMatcher::constant_fold_cmp_op< NE > (double a, double b) noexcept
Definition at line 1296 of file IRMatch.h.
operator||()
template<typename A , typename B > HALIDE_ALWAYS_INLINE auto Halide::Internal::IRMatcher::operator|| (A && a, B && b) -> BinOp<Or, decltype(pattern_arg(a)), decltype(pattern_arg(b))> noexcept
Definition at line 1301 of file IRMatch.h.
References pattern_arg().
Referenced by or_op().
or_op()
template<typename A , typename B > HALIDE_ALWAYS_INLINE auto Halide::Internal::IRMatcher::or_op (A && a, B && b) -> decltype(IRMatcher::operator||(a, b))
Definition at line 1306 of file IRMatch.h.
References operator||().
constant_fold_bin_op< Or >() [1/3]
template<> HALIDE_ALWAYS_INLINE int64_t Halide::Internal::IRMatcher::constant_fold_bin_op< Or > (halide_type_t & t, int64_t a, int64_t b) noexcept
Definition at line 1311 of file IRMatch.h.
constant_fold_bin_op< Or >() [2/3]
template<> HALIDE_ALWAYS_INLINE uint64_t Halide::Internal::IRMatcher::constant_fold_bin_op< Or > (halide_type_t & t, uint64_t a, uint64_t b) noexcept
Definition at line 1316 of file IRMatch.h.
constant_fold_bin_op< Or >() [3/3]
template<> HALIDE_ALWAYS_INLINE double Halide::Internal::IRMatcher::constant_fold_bin_op< Or > (halide_type_t & t, double a, double b) noexcept
Definition at line 1321 of file IRMatch.h.
operator&&()
template<typename A , typename B > HALIDE_ALWAYS_INLINE auto Halide::Internal::IRMatcher::operator&& (A && a, B && b) -> BinOp<And, decltype(pattern_arg(a)), decltype(pattern_arg(b))> noexcept
Definition at line 1327 of file IRMatch.h.
References pattern_arg().
Referenced by and_op().
and_op()
template<typename A , typename B > HALIDE_ALWAYS_INLINE auto Halide::Internal::IRMatcher::and_op (A && a, B && b) -> decltype(IRMatcher::operator&&(a, b))
Definition at line 1332 of file IRMatch.h.
References operator&&().
constant_fold_bin_op< And >() [1/3]
template<> HALIDE_ALWAYS_INLINE int64_t Halide::Internal::IRMatcher::constant_fold_bin_op< And > (halide_type_t & t, int64_t a, int64_t b) noexcept
Definition at line 1337 of file IRMatch.h.
constant_fold_bin_op< And >() [2/3]
template<> HALIDE_ALWAYS_INLINE uint64_t Halide::Internal::IRMatcher::constant_fold_bin_op< And > (halide_type_t & t, uint64_t a, uint64_t b) noexcept
Definition at line 1342 of file IRMatch.h.
constant_fold_bin_op< And >() [3/3]
template<> HALIDE_ALWAYS_INLINE double Halide::Internal::IRMatcher::constant_fold_bin_op< And > (halide_type_t & t, double a, double b) noexcept
Definition at line 1347 of file IRMatch.h.
bitwise_or_reduce() [1/2]
constexpr uint32_t Halide::Internal::IRMatcher::bitwise_or_reduce () inline constexpr
Definition at line 1352 of file IRMatch.h.
Referenced by bitwise_or_reduce().
bitwise_or_reduce() [2/2]
template<typename... Args> constexpr uint32_t Halide::Internal::IRMatcher::bitwise_or_reduce (uint32_t first, Args... rest) constexpr
Definition at line 1357 of file IRMatch.h.
References bitwise_or_reduce().
and_reduce() [1/2]
constexpr bool Halide::Internal::IRMatcher::and_reduce () inline constexpr
Definition at line 1361 of file IRMatch.h.
Referenced by and_reduce().
and_reduce() [2/2]
template<typename... Args> constexpr bool Halide::Internal::IRMatcher::and_reduce (bool first, Args... rest) constexpr
Definition at line 1366 of file IRMatch.h.
References and_reduce().
const_min()
constexpr int Halide::Internal::IRMatcher::const_min (int a, int b) constexpr
Definition at line 1371 of file IRMatch.h.
Referenced by Halide::Internal::IRMatcher::Intrin< Args >::make().
operator<<() [23/39]
template<typename... Args> std::ostream& Halide::Internal::IRMatcher::operator<< (std::ostream & s, const Intrin< Args... > & op)
Definition at line 1484 of file IRMatch.h.
References Halide::Internal::IRMatcher::Intrin< Args >::intrin, and Halide::Internal::IRMatcher::Intrin< Args >::print_args().
intrin()
template<typename... Args> HALIDE_ALWAYS_INLINE auto Halide::Internal::IRMatcher::intrin (Call::IntrinsicOp intrinsic_op, Args... args) -> Intrin<decltype(pattern_arg(args))...> noexcept
Definition at line 1492 of file IRMatch.h.
References pattern_arg().
widening_add()
template<typename A , typename B > auto Halide::Internal::IRMatcher::widening_add (A && a, B && b) -> Intrin<decltype(pattern_arg(a)), decltype(pattern_arg(b))> noexcept
Definition at line 1497 of file IRMatch.h.
References pattern_arg(), and Halide::Internal::Call::widening_add.
Referenced by Halide::Internal::IRMatcher::Intrin< Args >::make().
widening_sub()
template<typename A , typename B > auto Halide::Internal::IRMatcher::widening_sub (A && a, B && b) -> Intrin<decltype(pattern_arg(a)), decltype(pattern_arg(b))> noexcept
Definition at line 1501 of file IRMatch.h.
References pattern_arg(), and Halide::Internal::Call::widening_sub.
Referenced by Halide::Internal::IRMatcher::Intrin< Args >::make().
widening_mul()
template<typename A , typename B > auto Halide::Internal::IRMatcher::widening_mul (A && a, B && b) -> Intrin<decltype(pattern_arg(a)), decltype(pattern_arg(b))> noexcept
Definition at line 1505 of file IRMatch.h.
References pattern_arg(), and Halide::Internal::Call::widening_mul.
Referenced by Halide::Internal::IRMatcher::Intrin< Args >::make().
saturating_add()
template<typename A , typename B > auto Halide::Internal::IRMatcher::saturating_add (A && a, B && b) -> Intrin<decltype(pattern_arg(a)), decltype(pattern_arg(b))> noexcept
Definition at line 1509 of file IRMatch.h.
References pattern_arg(), and Halide::Internal::Call::saturating_add.
Referenced by Halide::Internal::IRMatcher::Intrin< Args >::make().
saturating_sub()
template<typename A , typename B > auto Halide::Internal::IRMatcher::saturating_sub (A && a, B && b) -> Intrin<decltype(pattern_arg(a)), decltype(pattern_arg(b))> noexcept
Definition at line 1513 of file IRMatch.h.
References pattern_arg(), and Halide::Internal::Call::saturating_sub.
Referenced by Halide::Internal::IRMatcher::Intrin< Args >::make().
halving_add()
template<typename A , typename B > auto Halide::Internal::IRMatcher::halving_add (A && a, B && b) -> Intrin<decltype(pattern_arg(a)), decltype(pattern_arg(b))> noexcept
Definition at line 1517 of file IRMatch.h.
References Halide::Internal::Call::halving_add, and pattern_arg().
Referenced by Halide::Internal::IRMatcher::Intrin< Args >::make().
halving_sub()
template<typename A , typename B > auto Halide::Internal::IRMatcher::halving_sub (A && a, B && b) -> Intrin<decltype(pattern_arg(a)), decltype(pattern_arg(b))> noexcept
Definition at line 1521 of file IRMatch.h.
References Halide::Internal::Call::halving_sub, and pattern_arg().
Referenced by Halide::Internal::IRMatcher::Intrin< Args >::make().
rounding_halving_add()
template<typename A , typename B > auto Halide::Internal::IRMatcher::rounding_halving_add (A && a, B && b) -> Intrin<decltype(pattern_arg(a)), decltype(pattern_arg(b))> noexcept
Definition at line 1525 of file IRMatch.h.
References pattern_arg(), and Halide::Internal::Call::rounding_halving_add.
Referenced by Halide::Internal::IRMatcher::Intrin< Args >::make().
rounding_halving_sub()
template<typename A , typename B > auto Halide::Internal::IRMatcher::rounding_halving_sub (A && a, B && b) -> Intrin<decltype(pattern_arg(a)), decltype(pattern_arg(b))> noexcept
Definition at line 1529 of file IRMatch.h.
References pattern_arg(), and Halide::Internal::Call::rounding_halving_sub.
Referenced by Halide::Internal::IRMatcher::Intrin< Args >::make().
shift_left()
template<typename A , typename B > auto Halide::Internal::IRMatcher::shift_left (A && a, B && b) -> Intrin<decltype(pattern_arg(a)), decltype(pattern_arg(b))> noexcept
Definition at line 1533 of file IRMatch.h.
References pattern_arg(), and Halide::Internal::Call::shift_left.
shift_right()
template<typename A , typename B > auto Halide::Internal::IRMatcher::shift_right (A && a, B && b) -> Intrin<decltype(pattern_arg(a)), decltype(pattern_arg(b))> noexcept
Definition at line 1537 of file IRMatch.h.
References pattern_arg(), and Halide::Internal::Call::shift_right.
rounding_shift_left()
template<typename A , typename B > auto Halide::Internal::IRMatcher::rounding_shift_left (A && a, B && b) -> Intrin<decltype(pattern_arg(a)), decltype(pattern_arg(b))> noexcept
Definition at line 1541 of file IRMatch.h.
References pattern_arg(), and Halide::Internal::Call::rounding_shift_left.
Referenced by Halide::Internal::IRMatcher::Intrin< Args >::make().
rounding_shift_right()
template<typename A , typename B > auto Halide::Internal::IRMatcher::rounding_shift_right (A && a, B && b) -> Intrin<decltype(pattern_arg(a)), decltype(pattern_arg(b))> noexcept
Definition at line 1545 of file IRMatch.h.
References pattern_arg(), and Halide::Internal::Call::rounding_shift_right.
Referenced by Halide::Internal::IRMatcher::Intrin< Args >::make().
operator!()
template<typename A > HALIDE_ALWAYS_INLINE auto Halide::Internal::IRMatcher::operator! (A && a) -> NotOp<decltype(pattern_arg(a))> noexcept
Definition at line 1590 of file IRMatch.h.
References pattern_arg().
Referenced by not_op().
not_op()
template<typename A > HALIDE_ALWAYS_INLINE auto Halide::Internal::IRMatcher::not_op (A && a) -> decltype(IRMatcher::operator!(a))
Definition at line 1596 of file IRMatch.h.
References operator!().
operator<<() [24/39]
template<typename A > std::ostream& Halide::Internal::IRMatcher::operator<< (std::ostream & s, const NotOp< A > & op) inline
Definition at line 1602 of file IRMatch.h.
References Halide::Internal::IRMatcher::NotOp< A >::a.
operator<<() [25/39]
template<typename C , typename T , typename F > std::ostream& Halide::Internal::IRMatcher::operator<< (std::ostream & s, const SelectOp< C, T, F > & op)
Definition at line 1660 of file IRMatch.h.
References Halide::Internal::IRMatcher::SelectOp< C, T, F >::c, Halide::Internal::IRMatcher::SelectOp< C, T, F >::f, and Halide::Internal::IRMatcher::SelectOp< C, T, F >::t.
select()
template<typename C , typename T , typename F > HALIDE_ALWAYS_INLINE auto Halide::Internal::IRMatcher::select (C && c, T && t, F && f) -> SelectOp<decltype(pattern_arg(c)), decltype(pattern_arg(t)), decltype(pattern_arg(f))> noexcept
Definition at line 1666 of file IRMatch.h.
References pattern_arg().
operator<<() [26/39]
template<typename A , typename B > std::ostream& Halide::Internal::IRMatcher::operator<< (std::ostream & s, const BroadcastOp< A, B > & op) inline
Definition at line 1733 of file IRMatch.h.
References Halide::Internal::IRMatcher::BroadcastOp< A, B >::a, and Halide::Internal::IRMatcher::BroadcastOp< A, B >::lanes.
broadcast()
template<typename A , typename B > HALIDE_ALWAYS_INLINE auto Halide::Internal::IRMatcher::broadcast (A && a, B lanes) -> BroadcastOp<decltype(pattern_arg(a)), decltype(pattern_arg(lanes))> noexcept
Definition at line 1739 of file IRMatch.h.
References pattern_arg().
operator<<() [27/39]
template<typename A , typename B , typename C > std::ostream& Halide::Internal::IRMatcher::operator<< (std::ostream & s, const RampOp< A, B, C > & op)
Definition at line 1797 of file IRMatch.h.
References Halide::Internal::IRMatcher::RampOp< A, B, C >::a, Halide::Internal::IRMatcher::RampOp< A, B, C >::b, and Halide::Internal::IRMatcher::RampOp< A, B, C >::lanes.
ramp()
template<typename A , typename B , typename C > HALIDE_ALWAYS_INLINE auto Halide::Internal::IRMatcher::ramp (A && a, B && b, C && c) -> RampOp<decltype(pattern_arg(a)), decltype(pattern_arg(b)), decltype(pattern_arg(c))> noexcept
Definition at line 1803 of file IRMatch.h.
References pattern_arg().
Referenced by Halide::Internal::HexagonAlignmentAnalyzer::is_aligned_impl().
operator<<() [28/39]
template<typename A , typename B , VectorReduce::Operator reduce_op> std::ostream& Halide::Internal::IRMatcher::operator<< (std::ostream & s, const VectorReduceOp< A, B, reduce_op > & op) inline
Definition at line 1855 of file IRMatch.h.
References Halide::Internal::IRMatcher::VectorReduceOp< A, B, reduce_op >::a, and Halide::Internal::IRMatcher::VectorReduceOp< A, B, reduce_op >::lanes.
h_add()
template<typename A , typename B > HALIDE_ALWAYS_INLINE auto Halide::Internal::IRMatcher::h_add (A && a, B lanes) -> VectorReduceOp<decltype(pattern_arg(a)), decltype(pattern_arg(lanes)), VectorReduce::Add> noexcept
Definition at line 1861 of file IRMatch.h.
References pattern_arg().
h_min()
template<typename A , typename B > HALIDE_ALWAYS_INLINE auto Halide::Internal::IRMatcher::h_min (A && a, B lanes) -> VectorReduceOp<decltype(pattern_arg(a)), decltype(pattern_arg(lanes)), VectorReduce::Min> noexcept
Definition at line 1867 of file IRMatch.h.
References pattern_arg().
h_max()
template<typename A , typename B > HALIDE_ALWAYS_INLINE auto Halide::Internal::IRMatcher::h_max (A && a, B lanes) -> VectorReduceOp<decltype(pattern_arg(a)), decltype(pattern_arg(lanes)), VectorReduce::Max> noexcept
Definition at line 1873 of file IRMatch.h.
References pattern_arg().
h_and()
template<typename A , typename B > HALIDE_ALWAYS_INLINE auto Halide::Internal::IRMatcher::h_and (A && a, B lanes) -> VectorReduceOp<decltype(pattern_arg(a)), decltype(pattern_arg(lanes)), VectorReduce::And> noexcept
Definition at line 1879 of file IRMatch.h.
References pattern_arg().
h_or()
template<typename A , typename B > HALIDE_ALWAYS_INLINE auto Halide::Internal::IRMatcher::h_or (A && a, B lanes) -> VectorReduceOp<decltype(pattern_arg(a)), decltype(pattern_arg(lanes)), VectorReduce::Or> noexcept
Definition at line 1885 of file IRMatch.h.
References pattern_arg().
operator<<() [29/39]
template<typename A > std::ostream& Halide::Internal::IRMatcher::operator<< (std::ostream & s, const NegateOp< A > & op)
Definition at line 1955 of file IRMatch.h.
References Halide::Internal::IRMatcher::NegateOp< A >::a.
operator-() [2/2]
template<typename A > HALIDE_ALWAYS_INLINE auto Halide::Internal::IRMatcher::operator- (A && a) -> NegateOp<decltype(pattern_arg(a))> noexcept
Definition at line 1961 of file IRMatch.h.
References pattern_arg().
negate()
template<typename A > HALIDE_ALWAYS_INLINE auto Halide::Internal::IRMatcher::negate (A && a) -> decltype(IRMatcher::operator-(a))
Definition at line 1967 of file IRMatch.h.
References operator-().
operator<<() [30/39]
template<typename A > std::ostream& Halide::Internal::IRMatcher::operator<< (std::ostream & s, const CastOp< A > & op)
Definition at line 2007 of file IRMatch.h.
References Halide::Internal::IRMatcher::CastOp< A >::a, and Halide::Internal::IRMatcher::CastOp< A >::t.
cast()
template<typename A > HALIDE_ALWAYS_INLINE auto Halide::Internal::IRMatcher::cast (halide_type_t t, A && a) -> CastOp<decltype(pattern_arg(a))> noexcept
Definition at line 2013 of file IRMatch.h.
References pattern_arg().
Referenced by cmdline::detail::lexical_cast(), and Halide::Internal::IRMatcher::CastOp< A >::make().
fold()
template<typename A > HALIDE_ALWAYS_INLINE auto Halide::Internal::IRMatcher::fold (A && a) -> Fold<decltype(pattern_arg(a))> noexcept
Definition at line 2062 of file IRMatch.h.
References pattern_arg().
operator<<() [31/39]
template<typename A > std::ostream& Halide::Internal::IRMatcher::operator<< (std::ostream & s, const Fold< A > & op)
Definition at line 2068 of file IRMatch.h.
References Halide::Internal::IRMatcher::Fold< A >::a.
overflows()
template<typename A > HALIDE_ALWAYS_INLINE auto Halide::Internal::IRMatcher::overflows (A && a) -> Overflows<decltype(pattern_arg(a))> noexcept
Definition at line 2099 of file IRMatch.h.
References pattern_arg().
operator<<() [32/39]
template<typename A > std::ostream& Halide::Internal::IRMatcher::operator<< (std::ostream & s, const Overflows< A > & op)
Definition at line 2105 of file IRMatch.h.
References Halide::Internal::IRMatcher::Overflows< A >::a.
operator<<() [33/39]
std::ostream& Halide::Internal::IRMatcher::operator<< (std::ostream & s, const Overflow & op) inline
Definition at line 2144 of file IRMatch.h.
is_const()
template<typename A > HALIDE_ALWAYS_INLINE auto Halide::Internal::IRMatcher::is_const (A && a) -> IsConst<decltype(pattern_arg(a))> noexcept
Definition at line 2175 of file IRMatch.h.
References pattern_arg().
Referenced by halide_handle_cplusplus_type::make(), and Halide::Internal::IRMatcher::IsConst< A >::make_folded_const().
operator<<() [34/39]
template<typename A > std::ostream& Halide::Internal::IRMatcher::operator<< (std::ostream & s, const IsConst< A > & op)
Definition at line 2181 of file IRMatch.h.
References Halide::Internal::IRMatcher::IsConst< A >::a.
can_prove()
template<typename A , typename Prover > HALIDE_ALWAYS_INLINE auto Halide::Internal::IRMatcher::can_prove (A && a, Prover * p) -> CanProve<decltype(pattern_arg(a)), Prover> noexcept
Definition at line 2213 of file IRMatch.h.
References pattern_arg().
operator<<() [35/39]
template<typename A , typename Prover > std::ostream& Halide::Internal::IRMatcher::operator<< (std::ostream & s, const CanProve< A, Prover > & op)
Definition at line 2219 of file IRMatch.h.
References Halide::Internal::IRMatcher::CanProve< A, Prover >::a.
is_float()
template<typename A > HALIDE_ALWAYS_INLINE auto Halide::Internal::IRMatcher::is_float (A && a) -> IsFloat<decltype(pattern_arg(a))> noexcept
Definition at line 2250 of file IRMatch.h.
References pattern_arg().
operator<<() [36/39]
template<typename A > std::ostream& Halide::Internal::IRMatcher::operator<< (std::ostream & s, const IsFloat< A > & op)
Definition at line 2256 of file IRMatch.h.
References Halide::Internal::IRMatcher::IsFloat< A >::a.
is_int()
template<typename A > HALIDE_ALWAYS_INLINE auto Halide::Internal::IRMatcher::is_int (A && a, int bits = 0) -> IsInt<decltype(pattern_arg(a))> noexcept
Examples
tutorial/lesson_14_types.cpp.
Definition at line 2288 of file IRMatch.h.
References pattern_arg().
operator<<() [37/39]
template<typename A > std::ostream& Halide::Internal::IRMatcher::operator<< (std::ostream & s, const IsInt< A > & op)
Definition at line 2294 of file IRMatch.h.
References Halide::Internal::IRMatcher::IsInt< A >::a, and Halide::Internal::IRMatcher::IsInt< A >::bits.
is_uint()
template<typename A > HALIDE_ALWAYS_INLINE auto Halide::Internal::IRMatcher::is_uint (A && a, int bits = 0) -> IsUInt<decltype(pattern_arg(a))> noexcept
Definition at line 2330 of file IRMatch.h.
References pattern_arg().
operator<<() [38/39]
template<typename A > std::ostream& Halide::Internal::IRMatcher::operator<< (std::ostream & s, const IsUInt< A > & op)
Definition at line 2336 of file IRMatch.h.
References Halide::Internal::IRMatcher::IsUInt< A >::a, and Halide::Internal::IRMatcher::IsUInt< A >::bits.
is_scalar()
template<typename A > HALIDE_ALWAYS_INLINE auto Halide::Internal::IRMatcher::is_scalar (A && a) -> IsScalar<decltype(pattern_arg(a))> noexcept
Definition at line 2371 of file IRMatch.h.
References pattern_arg().
is_max_value()
template<typename A > HALIDE_ALWAYS_INLINE auto Halide::Internal::IRMatcher::is_max_value (A && a) -> IsMaxValue<decltype(pattern_arg(a))> noexcept
Definition at line 2406 of file IRMatch.h.
References pattern_arg().
is_min_value()
template<typename A > HALIDE_ALWAYS_INLINE auto Halide::Internal::IRMatcher::is_min_value (A && a) -> IsMinValue<decltype(pattern_arg(a))> noexcept
Definition at line 2443 of file IRMatch.h.
References pattern_arg().
operator<<() [39/39]
template<typename A > std::ostream& Halide::Internal::IRMatcher::operator<< (std::ostream & s, const IsScalar< A > & op)
Definition at line 2449 of file IRMatch.h.
References Halide::Internal::IRMatcher::IsScalar< A >::a.
fuzz_test_rule() [1/2]
template<typename Before , typename After , typename Predicate , typename = typename std::enable_if<std::decay<Before>::type::foldable && std::decay<After>::type::foldable>::type> HALIDE_NEVER_INLINE void Halide::Internal::IRMatcher::fuzz_test_rule (Before && before, After && after, Predicate && pred, halide_type_t wildcard_type, halide_type_t output_type) noexcept
Definition at line 2460 of file IRMatch.h.
References Halide::abs(), constant_fold_bin_op< Add >(), evaluate_predicate(), halide_scalar_value_t::f64, Halide::Internal::IRMatcher::MatcherState::get_binding(), Halide::Internal::IRMatcher::MatcherState::get_bound_const(), halide_type_bfloat, halide_type_float, halide_type_int, halide_type_uint, halide_scalar_value_t::i64, internal_error, halide_type_t::lanes, Halide::Internal::make_const(), make_const_expr(), max_wild, Halide::Internal::IRMatcher::MatcherState::set_binding(), Halide::Internal::IRMatcher::MatcherState::set_bound_const(), Halide::Internal::IRMatcher::MatcherState::special_values_mask, halide_scalar_value_t::u, and halide_scalar_value_t::u64.
Referenced by Halide::Internal::IRMatcher::Rewriter< Instance >::operator()().
fuzz_test_rule() [2/2]
template<typename Before , typename After , typename Predicate , typename = typename std::enable_if<!(std::decay<Before>::type::foldable && std::decay<After>::type::foldable)>::type> HALIDE_ALWAYS_INLINE void Halide::Internal::IRMatcher::fuzz_test_rule (Before && before, After && after, Predicate && pred, halide_type_t , halide_type_t , int dummy = 0) noexcept
Definition at line 2585 of file IRMatch.h.
evaluate_predicate() [1/2]
HALIDE_ALWAYS_INLINE bool Halide::Internal::IRMatcher::evaluate_predicate (bool x, MatcherState &) noexcept
Definition at line 2591 of file IRMatch.h.
Referenced by fuzz_test_rule(), and Halide::Internal::IRMatcher::Rewriter< Instance >::operator()().
evaluate_predicate() [2/2]
template<typename Pattern , typename = typename enable_if_pattern<Pattern>::type> HALIDE_ALWAYS_INLINE bool Halide::Internal::IRMatcher::evaluate_predicate (Pattern p, MatcherState & state)
Definition at line 2597 of file IRMatch.h.
References halide_type_t::lanes, Halide::Internal::IRMatcher::MatcherState::special_values_mask, halide_scalar_value_t::u, and halide_scalar_value_t::u64.
rewriter() [1/4]
template<typename Instance , typename = typename enable_if_pattern<Instance>::type> HALIDE_ALWAYS_INLINE auto Halide::Internal::IRMatcher::rewriter (Instance instance, halide_type_t output_type, halide_type_t wildcard_type) -> Rewriter<decltype(pattern_arg(instance))> noexcept
Construct a rewriter for the given instance, which may be a pattern with concrete expressions as leaves, or just an expression.
The second optional argument (wildcard_type) is a hint as to what the type of the wildcards is likely to be. If omitted it uses the same type as the expression itself. They are not required to be this type, but the rule will only be tested for wildcards of that type when testing is enabled.
The rewriter can be used to check to see if the instance is one of some number of patterns and if so rewrite it into another form, using its operator() method. See Simplify.cpp for a bunch of example usage.
Important: Any Exprs in patterns are captured by reference, not by value, so ensure they outlive the rewriter.
Definition at line 2798 of file IRMatch.h.
References pattern_arg().
rewriter() [2/4]
template<typename Instance , typename = typename enable_if_pattern<Instance>::type> HALIDE_ALWAYS_INLINE auto Halide::Internal::IRMatcher::rewriter (Instance instance, halide_type_t output_type) -> Rewriter<decltype(pattern_arg(instance))> noexcept
Definition at line 2804 of file IRMatch.h.
References pattern_arg().
rewriter() [3/4]
HALIDE_ALWAYS_INLINE auto Halide::Internal::IRMatcher::rewriter (const Expr & e, halide_type_t wildcard_type) -> Rewriter<decltype(pattern_arg(e))> noexcept
Definition at line 2809 of file IRMatch.h.
References pattern_arg().
rewriter() [4/4]
HALIDE_ALWAYS_INLINE auto Halide::Internal::IRMatcher::rewriter (const Expr & e) -> Rewriter<decltype(pattern_arg(e))> noexcept
Definition at line 2814 of file IRMatch.h.
References pattern_arg().
Variable Documentation
max_wild
constexpr int Halide::Internal::IRMatcher::max_wild = 6 constexpr
Definition at line 70 of file IRMatch.h.
Referenced by fuzz_test_rule(), Halide::Internal::IRMatcher::WildConstInt< i >::match(), Halide::Internal::IRMatcher::WildConstUInt< i >::match(), Halide::Internal::IRMatcher::WildConstFloat< i >::match(), and Halide::Internal::IRMatcher::WildConst< i >::match().