Halide: Halide::Internal::IRMatcher::WildConstInt< i > Struct Template Reference
Halide::Internal::IRMatcher::WildConstInt< i > Struct Template Reference
#include <IRMatch.h>
Classes
struct pattern_tag
Public Member Functions
template<uint32_t bound>
HALIDE_ALWAYS_INLINE bool match (const BaseExprNode &e, MatcherState &state) const noexcept
template<uint32_t bound>
HALIDE_ALWAYS_INLINE bool match (int64_t value, MatcherState &state) const noexcept
HALIDE_ALWAYS_INLINE Expr make (MatcherState &state, halide_type_t type_hint) const
HALIDE_ALWAYS_INLINE void make_folded_const (halide_scalar_value_t &val, halide_type_t &ty, MatcherState &state) const
Static Public Attributes
constexpr static uint32_t binds = 1 << i
constexpr static IRNodeType min_node_type = IRNodeType::IntImm
constexpr static IRNodeType max_node_type = IRNodeType::IntImm
constexpr static bool canonical = true
constexpr static bool foldable = true
Detailed Description
template<int i>
struct Halide::Internal::IRMatcher::WildConstInt< i >
Definition at line 231 of file IRMatch.h.
Member Function Documentation
match() [1/2]
template<int i> template<uint32_t bound> HALIDE_ALWAYS_INLINE bool Halide::Internal::IRMatcher::WildConstInt< i >::match (const BaseExprNode & e, MatcherState & state) const inline noexcept
Definition at line 241 of file IRMatch.h.
References Halide::Internal::IRMatcher::WildConstInt< i >::binds, Halide::Internal::Broadcast, halide_scalar_value_t::i64, Halide::Internal::IntImm, Halide::Internal::IRMatcher::max_wild, Halide::Internal::IRNode::node_type, and halide_scalar_value_t::u.
match() [2/2]
template<int i> template<uint32_t bound> HALIDE_ALWAYS_INLINE bool Halide::Internal::IRMatcher::WildConstInt< i >::match (int64_t value, MatcherState & state) const inline noexcept
Definition at line 262 of file IRMatch.h.
References Halide::Internal::IRMatcher::WildConstInt< i >::binds, halide_scalar_value_t::i64, Halide::Internal::IRMatcher::max_wild, and halide_scalar_value_t::u.
make()
template<int i> HALIDE_ALWAYS_INLINE Expr Halide::Internal::IRMatcher::WildConstInt< i >::make (MatcherState & state, halide_type_t type_hint) const inline
Definition at line 275 of file IRMatch.h.
References Halide::Internal::IRMatcher::MatcherState::get_bound_const(), and Halide::Internal::IRMatcher::make_const_expr().
make_folded_const()
template<int i> HALIDE_ALWAYS_INLINE void Halide::Internal::IRMatcher::WildConstInt< i >::make_folded_const (halide_scalar_value_t & val, halide_type_t & ty, MatcherState & state) const inline
Definition at line 285 of file IRMatch.h.
References Halide::Internal::IRMatcher::MatcherState::get_bound_const().
Member Data Documentation
binds
template<int i> constexpr static uint32_t Halide::Internal::IRMatcher::WildConstInt< i >::binds = 1 << i static constexpr
Definition at line 234 of file IRMatch.h.
Referenced by Halide::Internal::IRMatcher::WildConstInt< i >::match().
min_node_type
template<int i> constexpr static IRNodeType Halide::Internal::IRMatcher::WildConstInt< i >::min_node_type = IRNodeType::IntImm static constexpr
Definition at line 236 of file IRMatch.h.
max_node_type
template<int i> constexpr static IRNodeType Halide::Internal::IRMatcher::WildConstInt< i >::max_node_type = IRNodeType::IntImm static constexpr
Definition at line 237 of file IRMatch.h.
canonical
template<int i> constexpr static bool Halide::Internal::IRMatcher::WildConstInt< i >::canonical = true static constexpr
Definition at line 238 of file IRMatch.h.
foldable
template<int i> constexpr static bool Halide::Internal::IRMatcher::WildConstInt< i >::foldable = true static constexpr
Definition at line 282 of file IRMatch.h.
The documentation for this struct was generated from the following file:
/Users/halidenightly/build_bot_new/worker/halide-main-llvm13-x86-64-osx-cmake/halide-source/src/IRMatch.h