Halide: Halide::Internal::IRMatcher::CanProve< A, Prover > Struct Template Reference
Halide::Internal::IRMatcher::CanProve< A, Prover > Struct Template Reference
#include <IRMatch.h>
Classes
struct pattern_tag
Public Member Functions
HALIDE_NEVER_INLINE void make_folded_const (halide_scalar_value_t &val, halide_type_t &ty, MatcherState &state) const
Public Attributes
A a
Prover * prover
Static Public Attributes
constexpr static uint32_t binds = bindings<A>::mask
constexpr static IRNodeType min_node_type = IRNodeType::UIntImm
constexpr static IRNodeType max_node_type = IRNodeType::UIntImm
constexpr static bool canonical = true
constexpr static bool foldable = true
Detailed Description
template<typename A, typename Prover>
struct Halide::Internal::IRMatcher::CanProve< A, Prover >
Definition at line 2187 of file IRMatch.h.
Member Function Documentation
make_folded_const()
template<typename A , typename Prover > HALIDE_NEVER_INLINE void Halide::Internal::IRMatcher::CanProve< A, Prover >::make_folded_const (halide_scalar_value_t & val, halide_type_t & ty, MatcherState & state) const inline
Definition at line 2202 of file IRMatch.h.
References Halide::Internal::IRMatcher::CanProve< A, Prover >::a, halide_type_t::bits, halide_type_t::code, halide_type_uint, Halide::Internal::is_const_one(), halide_type_t::lanes, Halide::Type::lanes(), Halide::Internal::IRMatcher::CanProve< A, Prover >::prover, Halide::Expr::type(), halide_scalar_value_t::u, and halide_scalar_value_t::u64.
Member Data Documentation
a
template<typename A , typename Prover > A Halide::Internal::IRMatcher::CanProve< A, Prover >::a
Definition at line 2189 of file IRMatch.h.
Referenced by Halide::Internal::IRMatcher::CanProve< A, Prover >::make_folded_const(), and Halide::Internal::IRMatcher::operator<<().
prover
template<typename A , typename Prover > Prover* Halide::Internal::IRMatcher::CanProve< A, Prover >::prover
Definition at line 2190 of file IRMatch.h.
Referenced by Halide::Internal::IRMatcher::CanProve< A, Prover >::make_folded_const().
binds
template<typename A , typename Prover > constexpr static uint32_t Halide::Internal::IRMatcher::CanProve< A, Prover >::binds = bindings<A>::mask static constexpr
Definition at line 2192 of file IRMatch.h.
min_node_type
template<typename A , typename Prover > constexpr static IRNodeType Halide::Internal::IRMatcher::CanProve< A, Prover >::min_node_type = IRNodeType::UIntImm static constexpr
Definition at line 2195 of file IRMatch.h.
max_node_type
template<typename A , typename Prover > constexpr static IRNodeType Halide::Internal::IRMatcher::CanProve< A, Prover >::max_node_type = IRNodeType::UIntImm static constexpr
Definition at line 2196 of file IRMatch.h.
canonical
template<typename A , typename Prover > constexpr static bool Halide::Internal::IRMatcher::CanProve< A, Prover >::canonical = true static constexpr
Definition at line 2197 of file IRMatch.h.
foldable
template<typename A , typename Prover > constexpr static bool Halide::Internal::IRMatcher::CanProve< A, Prover >::foldable = true static constexpr
Definition at line 2199 of file IRMatch.h.
The documentation for this struct was generated from the following file:
/Users/halidenightly/build_bot_new/worker/halide-main-llvm13-x86-64-osx-cmake/halide-source/src/IRMatch.h