Halide: Halide::Internal::PipelineFeatures Struct Reference
Halide::Internal::PipelineFeatures Struct Reference
#include <Featurization.h>
Public Types
enum class OpType {
Const , Cast , Variable , Param ,
Add , Sub , Mod , Mul ,
Div , Min , Max , EQ ,
NE , LT , LE , And ,
Or , Not , Select , ImageCall ,
FuncCall , SelfCall , ExternCall , Let ,
NumOpTypes
}
enum class ScalarType {
Bool , UInt8 , UInt16 , UInt32 ,
UInt64 , Float , Double , NumScalarTypes
}
enum class AccessType {
LoadFunc , LoadSelf , LoadImage , Store ,
NumAccessTypes
}
Public Member Functions
int & operator[] (int idx)
int operator[] (int idx) const
template<typename OS >
void dump (OS &os) const
void dump () const
Static Public Member Functions
static constexpr size_t num_features ()
static constexpr uint32_t version ()
Public Attributes
int types_in_use [(int) ScalarType::NumScalarTypes] = {}
int op_histogram [(int) OpType::NumOpTypes][(int) ScalarType::NumScalarTypes] = {}
int pointwise_accesses [(int) AccessType::NumAccessTypes][(int) ScalarType::NumScalarTypes] = {}
int transpose_accesses [(int) AccessType::NumAccessTypes][(int) ScalarType::NumScalarTypes] = {}
int broadcast_accesses [(int) AccessType::NumAccessTypes][(int) ScalarType::NumScalarTypes] = {}
int slice_accesses [(int) AccessType::NumAccessTypes][(int) ScalarType::NumScalarTypes] = {}
Detailed Description
Definition at line 15 of file Featurization.h.
Member Enumeration Documentation
OpType
enum Halide::Internal::PipelineFeatures::OpType strong
Enumerator
Const
Cast
Variable
Param
Add
Sub
Mod
Mul
Div
Min
Max
EQ
NE
LT
LE
And
Or
Not
Select
ImageCall
FuncCall
SelfCall
ExternCall
Let
NumOpTypes
Definition at line 33 of file Featurization.h.
ScalarType
enum Halide::Internal::PipelineFeatures::ScalarType strong
Enumerator
Bool
UInt8
UInt16
UInt32
UInt64
Float
Double
NumScalarTypes
Definition at line 61 of file Featurization.h.
AccessType
enum Halide::Internal::PipelineFeatures::AccessType strong
Enumerator
LoadFunc
LoadSelf
LoadImage
Store
NumAccessTypes
Definition at line 77 of file Featurization.h.
Member Function Documentation
num_features()
static constexpr size_t Halide::Internal::PipelineFeatures::num_features () inline static constexpr
Definition at line 16 of file Featurization.h.
version()
static constexpr uint32_t Halide::Internal::PipelineFeatures::version () inline static constexpr
Definition at line 20 of file Featurization.h.
operator[]() [1/2]
int& Halide::Internal::PipelineFeatures::operator[] (int idx) inline
Definition at line 25 of file Featurization.h.
operator[]() [2/2]
int Halide::Internal::PipelineFeatures::operator[] (int idx) const inline
Definition at line 29 of file Featurization.h.
dump() [1/2]
template<typename OS > void Halide::Internal::PipelineFeatures::dump (OS & os) const inline
Definition at line 103 of file Featurization.h.
References Add, And, broadcast_accesses, Cast, Const, Div, EQ, ExternCall, FuncCall, ImageCall, LE, Let, LT, Max, Min, Mod, Mul, NE, Not, NumScalarTypes, op_histogram, Or, Param, pointwise_accesses, Select, SelfCall, slice_accesses, Sub, transpose_accesses, types_in_use, and Variable.
dump() [2/2]
void Halide::Internal::PipelineFeatures::dump () const inline
Definition at line 160 of file Featurization.h.
Member Data Documentation
types_in_use
int Halide::Internal::PipelineFeatures::types_in_use[(int) ScalarType::NumScalarTypes] = {}
Definition at line 73 of file Featurization.h.
Referenced by dump().
op_histogram
int Halide::Internal::PipelineFeatures::op_histogram[(int) OpType::NumOpTypes][(int) ScalarType::NumScalarTypes] = {}
Definition at line 75 of file Featurization.h.
Referenced by dump().
pointwise_accesses
int Halide::Internal::PipelineFeatures::pointwise_accesses[(int) AccessType::NumAccessTypes][(int) ScalarType::NumScalarTypes] = {}
Definition at line 94 of file Featurization.h.
Referenced by dump().
transpose_accesses
int Halide::Internal::PipelineFeatures::transpose_accesses[(int) AccessType::NumAccessTypes][(int) ScalarType::NumScalarTypes] = {}
Definition at line 96 of file Featurization.h.
Referenced by dump().
broadcast_accesses
int Halide::Internal::PipelineFeatures::broadcast_accesses[(int) AccessType::NumAccessTypes][(int) ScalarType::NumScalarTypes] = {}
Definition at line 98 of file Featurization.h.
Referenced by dump().
slice_accesses
int Halide::Internal::PipelineFeatures::slice_accesses[(int) AccessType::NumAccessTypes][(int) ScalarType::NumScalarTypes] = {}
Definition at line 100 of file Featurization.h.
Referenced by dump().
The documentation for this struct was generated from the following file:
/Users/halidenightly/build_bot_new/worker/halide-main-llvm13-x86-64-osx-cmake/halide-source/src/autoschedulers/adams2019/Featurization.h