Halide: Halide::Internal::IRMatcher::NotOp< A > Struct Template Reference
Halide::Internal::IRMatcher::NotOp< A > Struct Template Reference
#include <IRMatch.h>
Classes
struct pattern_tag
Public Member Functions
template<uint32_t bound>
HALIDE_ALWAYS_INLINE bool match (const BaseExprNode &e, MatcherState &state) const noexcept
template<uint32_t bound, typename A2 >
HALIDE_ALWAYS_INLINE bool match (const NotOp< A2 > &op, MatcherState &state) const noexcept
HALIDE_ALWAYS_INLINE Expr make (MatcherState &state, halide_type_t type_hint) const
template<typename A1 = A>
HALIDE_ALWAYS_INLINE void make_folded_const (halide_scalar_value_t &val, halide_type_t &ty, MatcherState &state) const noexcept
Public Attributes
A a
Static Public Attributes
constexpr static uint32_t binds = bindings<A>::mask
constexpr static IRNodeType min_node_type = IRNodeType::Not
constexpr static IRNodeType max_node_type = IRNodeType::Not
constexpr static bool canonical = A::canonical
constexpr static bool foldable = A::foldable
Detailed Description
template<typename A>
struct Halide::Internal::IRMatcher::NotOp< A >
Definition at line 1550 of file IRMatch.h.
Member Function Documentation
match() [1/2]
template<typename A > template<uint32_t bound> HALIDE_ALWAYS_INLINE bool Halide::Internal::IRMatcher::NotOp< A >::match (const BaseExprNode & e, MatcherState & state) const inline noexcept
Definition at line 1561 of file IRMatch.h.
References Halide::Internal::Not::a, Halide::Internal::IRMatcher::NotOp< A >::a, Halide::Expr::get(), and Halide::Internal::Not.
match() [2/2]
template<typename A > template<uint32_t bound, typename A2 > HALIDE_ALWAYS_INLINE bool Halide::Internal::IRMatcher::NotOp< A >::match (const NotOp< A2 > & op, MatcherState & state) const inline noexcept
Definition at line 1570 of file IRMatch.h.
References Halide::Internal::IRMatcher::NotOp< A >::a, and Halide::Internal::IRMatcher::unwrap().
make()
template<typename A > HALIDE_ALWAYS_INLINE Expr Halide::Internal::IRMatcher::NotOp< A >::make (MatcherState & state, halide_type_t type_hint) const inline
Definition at line 1575 of file IRMatch.h.
References Halide::Internal::IRMatcher::NotOp< A >::a, and Halide::Internal::Not::make().
make_folded_const()
template<typename A > template<typename A1 = A> HALIDE_ALWAYS_INLINE void Halide::Internal::IRMatcher::NotOp< A >::make_folded_const (halide_scalar_value_t & val, halide_type_t & ty, MatcherState & state) const inline noexcept
Definition at line 1582 of file IRMatch.h.
References Halide::Internal::IRMatcher::NotOp< A >::a.
Member Data Documentation
a
template<typename A > A Halide::Internal::IRMatcher::NotOp< A >::a
Definition at line 1552 of file IRMatch.h.
Referenced by Halide::Internal::IRMatcher::NotOp< A >::make(), Halide::Internal::IRMatcher::NotOp< A >::make_folded_const(), Halide::Internal::IRMatcher::NotOp< A >::match(), and Halide::Internal::IRMatcher::operator<<().
binds
template<typename A > constexpr static uint32_t Halide::Internal::IRMatcher::NotOp< A >::binds = bindings<A>::mask static constexpr
Definition at line 1554 of file IRMatch.h.
min_node_type
template<typename A > constexpr static IRNodeType Halide::Internal::IRMatcher::NotOp< A >::min_node_type = IRNodeType::Not static constexpr
Definition at line 1556 of file IRMatch.h.
max_node_type
template<typename A > constexpr static IRNodeType Halide::Internal::IRMatcher::NotOp< A >::max_node_type = IRNodeType::Not static constexpr
Definition at line 1557 of file IRMatch.h.
canonical
template<typename A > constexpr static bool Halide::Internal::IRMatcher::NotOp< A >::canonical = A::canonical static constexpr
Definition at line 1558 of file IRMatch.h.
foldable
template<typename A > constexpr static bool Halide::Internal::IRMatcher::NotOp< A >::foldable = A::foldable static constexpr
Definition at line 1579 of file IRMatch.h.
The documentation for this struct was generated from the following file:
/Users/halidenightly/build_bot_new/worker/halide-main-llvm13-x86-64-osx-cmake/halide-source/src/IRMatch.h