Halide: Halide::Internal::Simplify::ExprInfo Struct Reference
Halide::Internal::Simplify::ExprInfo Struct Reference
#include <Simplify_Internal.h>
Public Member Functions
void trim_bounds_using_alignment ()
void intersect (const ExprInfo &other)
Public Attributes
int64_t min = 0
int64_t max = 0
bool min_defined = false
bool max_defined = false
ModulusRemainder alignment
Detailed Description
Definition at line 37 of file Simplify_Internal.h.
Member Function Documentation
trim_bounds_using_alignment()
void Halide::Internal::Simplify::ExprInfo::trim_bounds_using_alignment () inline
Definition at line 44 of file Simplify_Internal.h.
References alignment, max, max_defined, min, min_defined, Halide::Internal::mod_imp(), Halide::Internal::ModulusRemainder::modulus, and Halide::Internal::ModulusRemainder::remainder.
Referenced by intersect().
intersect()
void Halide::Internal::Simplify::ExprInfo::intersect (const ExprInfo & other) inline
Definition at line 72 of file Simplify_Internal.h.
References alignment, Halide::Internal::ModulusRemainder::intersect(), Halide::max(), max, max_defined, Halide::min(), min, min_defined, and trim_bounds_using_alignment().
Member Data Documentation
min
int64_t Halide::Internal::Simplify::ExprInfo::min = 0
Definition at line 39 of file Simplify_Internal.h.
Referenced by intersect(), and trim_bounds_using_alignment().
max
int64_t Halide::Internal::Simplify::ExprInfo::max = 0
Definition at line 39 of file Simplify_Internal.h.
Referenced by intersect(), and trim_bounds_using_alignment().
min_defined
bool Halide::Internal::Simplify::ExprInfo::min_defined = false
Definition at line 40 of file Simplify_Internal.h.
Referenced by intersect(), and trim_bounds_using_alignment().
max_defined
bool Halide::Internal::Simplify::ExprInfo::max_defined = false
Definition at line 40 of file Simplify_Internal.h.
Referenced by intersect(), and trim_bounds_using_alignment().
alignment
ModulusRemainder Halide::Internal::Simplify::ExprInfo::alignment
Definition at line 42 of file Simplify_Internal.h.
Referenced by intersect(), and trim_bounds_using_alignment().
The documentation for this struct was generated from the following file:
/Users/halidenightly/build_bot_new/worker/halide-main-llvm13-x86-64-osx-cmake/halide-source/src/Simplify_Internal.h