Halide: /Users/halidenightly/build_bot_new/worker/halide-main-llvm13-x86-64-osx-cmake/halide-source/src/runtime/synchronization_common.h File Reference
synchronization_common.h File Reference
#include "HalideRuntime.h"
#include "printer.h"
#include "scoped_spin_lock.h"
Classes
class Halide::Runtime::Internal::Synchronization::spin_control
struct Halide::Runtime::Internal::Synchronization::word_lock_queue_data
class Halide::Runtime::Internal::Synchronization::word_lock
struct Halide::Runtime::Internal::Synchronization::queue_data
struct Halide::Runtime::Internal::Synchronization::hash_bucket
struct Halide::Runtime::Internal::Synchronization::hash_table
struct Halide::Runtime::Internal::Synchronization::bucket_pair
struct Halide::Runtime::Internal::Synchronization::validate_action
struct Halide::Runtime::Internal::Synchronization::parking_control
struct Halide::Runtime::Internal::Synchronization::mutex_parking_control
class Halide::Runtime::Internal::Synchronization::fast_mutex
struct Halide::Runtime::Internal::Synchronization::signal_parking_control
struct Halide::Runtime::Internal::Synchronization::broadcast_parking_control
struct Halide::Runtime::Internal::Synchronization::wait_parking_control
class Halide::Runtime::Internal::Synchronization::fast_cond
struct halide_mutex_array
Namespaces
Halide
This file defines the class FunctionDAG, which is our representation of a Halide pipeline, and contains methods to using Halide's bounds tools to query properties of it.
Halide::Runtime
Halide::Runtime::Internal
Halide::Runtime::Internal::Synchronization
Macros
#define TSAN_ANNOTATIONS 0
#define LOAD_FACTOR 4
#define HASH_TABLE_BITS 10
#define table (*(hash_table *)table_storage)
Functions
ALWAYS_INLINE void Halide::Runtime::Internal::Synchronization::check_hash (uintptr_t hash)
WEAK hash_bucket & Halide::Runtime::Internal::Synchronization::lock_bucket (uintptr_t addr)
WEAK bucket_pair Halide::Runtime::Internal::Synchronization::lock_bucket_pair (uintptr_t addr_from, uintptr_t addr_to)
WEAK void Halide::Runtime::Internal::Synchronization::unlock_bucket_pair (bucket_pair &buckets)
WEAK bool Halide::Runtime::Internal::Synchronization::parking_control_validate (void *control, validate_action &action)
WEAK void Halide::Runtime::Internal::Synchronization::parking_control_before_sleep (void *control)
WEAK uintptr_t Halide::Runtime::Internal::Synchronization::parking_control_unpark (void *control, int unparked, bool more_waiters)
WEAK void Halide::Runtime::Internal::Synchronization::parking_control_requeue_callback (void *control, const validate_action &action, bool one_to_wake, bool some_requeued)
WEAK uintptr_t Halide::Runtime::Internal::Synchronization::park (uintptr_t addr, parking_control &control)
WEAK uintptr_t Halide::Runtime::Internal::Synchronization::unpark_one (uintptr_t addr, parking_control &control)
WEAK uintptr_t Halide::Runtime::Internal::Synchronization::unpark_all (uintptr_t addr, uintptr_t unpark_info)
WEAK int Halide::Runtime::Internal::Synchronization::unpark_requeue (uintptr_t addr_from, uintptr_t addr_to, parking_control &control, uintptr_t unpark_info)
WEAK bool Halide::Runtime::Internal::Synchronization::mutex_parking_control_validate (void *control, validate_action &action)
WEAK uintptr_t Halide::Runtime::Internal::Synchronization::mutex_parking_control_unpark (void *control, int unparked, bool more_waiters)
WEAK uintptr_t Halide::Runtime::Internal::Synchronization::signal_parking_control_unpark (void *control, int unparked, bool more_waiters)
WEAK bool Halide::Runtime::Internal::Synchronization::broadcast_parking_control_validate (void *control, validate_action &action)
WEAK void Halide::Runtime::Internal::Synchronization::broadcast_parking_control_requeue_callback (void *control, const validate_action &action, bool one_to_wake, bool some_requeued)
WEAK bool Halide::Runtime::Internal::Synchronization::wait_parking_control_validate (void *control, validate_action &action)
WEAK void Halide::Runtime::Internal::Synchronization::wait_parking_control_before_sleep (void *control)
WEAK uintptr_t Halide::Runtime::Internal::Synchronization::wait_parking_control_unpark (void *control, int unparked, bool more_waiters)
WEAK void halide_mutex_lock (halide_mutex *mutex)
A basic set of mutex and condition variable functions, which call platform specific code for mutual exclusion.
WEAK void halide_mutex_unlock (halide_mutex *mutex)
WEAK void halide_cond_broadcast (struct halide_cond *cond)
WEAK void halide_cond_signal (struct halide_cond *cond)
WEAK void halide_cond_wait (struct halide_cond *cond, struct halide_mutex *mutex)
WEAK halide_mutex_array * halide_mutex_array_create (int sz)
WEAK void halide_mutex_array_destroy (void *user_context, void *array)
WEAK int halide_mutex_array_lock (struct halide_mutex_array *array, int entry)
WEAK int halide_mutex_array_unlock (struct halide_mutex_array *array, int entry)
Variables
WEAK char Halide::Runtime::Internal::Synchronization::table_storage [sizeof(hash_table)]
Macro Definition Documentation
TSAN_ANNOTATIONS
#define TSAN_ANNOTATIONS 0
Definition at line 32 of file synchronization_common.h.
LOAD_FACTOR
#define LOAD_FACTOR 4
Definition at line 461 of file synchronization_common.h.
HASH_TABLE_BITS
#define HASH_TABLE_BITS 10
Definition at line 474 of file synchronization_common.h.
table
#define table (*(hash_table *)table_storage)
Definition at line 479 of file synchronization_common.h.
Function Documentation
halide_mutex_lock()
WEAK void halide_mutex_lock (struct halide_mutex * mutex)
A basic set of mutex and condition variable functions, which call platform specific code for mutual exclusion.
Equivalent to posix calls.
Definition at line 1131 of file synchronization_common.h.
References Halide::Runtime::Internal::Synchronization::fast_mutex::lock().
Referenced by halide_default_do_par_for(), halide_default_do_parallel_tasks(), halide_default_semaphore_release(), halide_mutex_array_lock(), halide_set_num_threads(), halide_shutdown_thread_pool(), Halide::Runtime::Internal::ScopedMutexLock::ScopedMutexLock(), Halide::Runtime::Internal::worker_thread(), and Halide::Runtime::Internal::worker_thread_already_locked().
halide_mutex_unlock()
WEAK void halide_mutex_unlock (halide_mutex * mutex)
Definition at line 1137 of file synchronization_common.h.
References Halide::Runtime::Internal::Synchronization::fast_mutex::unlock().
Referenced by halide_default_do_par_for(), halide_default_do_parallel_tasks(), halide_default_semaphore_release(), halide_mutex_array_unlock(), halide_set_num_threads(), halide_shutdown_thread_pool(), Halide::Runtime::Internal::worker_thread(), Halide::Runtime::Internal::worker_thread_already_locked(), and Halide::Runtime::Internal::ScopedMutexLock::~ScopedMutexLock().
halide_cond_broadcast()
WEAK void halide_cond_broadcast (struct halide_cond * cond)
Definition at line 1143 of file synchronization_common.h.
References Halide::Runtime::Internal::Synchronization::fast_cond::broadcast().
Referenced by Halide::Runtime::Internal::enqueue_work_already_locked(), halide_default_semaphore_release(), halide_shutdown_thread_pool(), and Halide::Runtime::Internal::worker_thread_already_locked().
halide_cond_signal()
WEAK void halide_cond_signal (struct halide_cond * cond)
Definition at line 1149 of file synchronization_common.h.
References Halide::Runtime::Internal::Synchronization::fast_cond::signal().
halide_cond_wait()
WEAK void halide_cond_wait (struct halide_cond * cond, struct halide_mutex * mutex)
Definition at line 1155 of file synchronization_common.h.
References Halide::Runtime::Internal::Synchronization::fast_cond::wait().
Referenced by Halide::Runtime::Internal::worker_thread_already_locked().
halide_mutex_array_create()
WEAK halide_mutex_array* halide_mutex_array_create (int sz)
Definition at line 1168 of file synchronization_common.h.
References halide_mutex_array::array, halide_free(), halide_malloc(), and memset().
halide_mutex_array_destroy()
WEAK void halide_mutex_array_destroy (void * user_context, void * array)
Definition at line 1188 of file synchronization_common.h.
References halide_mutex_array::array, halide_free(), and user_context.
halide_mutex_array_lock()
WEAK int halide_mutex_array_lock (struct halide_mutex_array * array, int entry)
Definition at line 1194 of file synchronization_common.h.
References halide_mutex_array::array, and halide_mutex_lock().
halide_mutex_array_unlock()
WEAK int halide_mutex_array_unlock (struct halide_mutex_array * array, int entry)
Definition at line 1199 of file synchronization_common.h.
References halide_mutex_array::array, and halide_mutex_unlock().