Halide: Halide::Internal::GeneratorInput_Scalar< T > Class Template Reference
Halide::Internal::GeneratorInput_Scalar< T > Class Template Reference
#include <Generator.h>
Inherits Halide::Internal::GeneratorInputImpl< T, Expr >.
Inherited by Halide::Internal::GeneratorInput_Arithmetic< T >.
Public Member Functions
GeneratorInput_Scalar (const std::string &name)
GeneratorInput_Scalar (const std::string &name, const TBase &def)
GeneratorInput_Scalar (size_t array_size, const std::string &name)
GeneratorInput_Scalar (size_t array_size, const std::string &name, const TBase &def)
operator Expr () const
You can use this Input as an expression in a halide function definition.
operator ExternFuncArgument () const
Using an Input as the argument to an external stage treats it as an Expr.
template<typename T2 = T, typename std::enable_if< std::is_pointer< T2 >::value >::type * = nullptr>
void set_estimate (const TBase &value)
template<typename T2 = T, typename std::enable_if<!std::is_array< T2 >::value &&!std::is_pointer< T2 >::value >::type * = nullptr>
void set_estimate (const TBase &value)
template<typename T2 = T, typename std::enable_if< std::is_array< T2 >::value >::type * = nullptr>
void set_estimate (size_t index, const TBase &value)
Public Member Functions inherited from Halide::Internal::GeneratorInputImpl< T, Expr >
size_t size () const
const Expr & operator[] (size_t i) const
const Expr & at (size_t i) const
std::vector< Expr >::const_iterator begin () const
std::vector< Expr >::const_iterator end () const
Public Member Functions inherited from Halide::Internal::GeneratorInputBase
~GeneratorInputBase () override
Public Member Functions inherited from Halide::Internal::GIOBase
bool array_size_defined () const
size_t array_size () const
const std::string & name () const
IOKind kind () const
bool types_defined () const
const std::vector< Type > & types () const
Type type () const
bool dims_defined () const
int dims () const
const std::vector< Func > & funcs () const
const std::vector< Expr > & exprs () const
virtual ~GIOBase ()=default
GIOBase (const GIOBase &)=delete
GIOBase & operator= (const GIOBase &)=delete
GIOBase (GIOBase &&)=delete
GIOBase & operator= (GIOBase &&)=delete
Protected Types
using TBase = typename Super::TBase
Protected Types inherited from Halide::Internal::GeneratorInputImpl< T, Expr >
using TBase = typename std::remove_all_extents< T >::type
Protected Member Functions
void set_def_min_max () override
std::string get_c_type () const override
Protected Member Functions inherited from Halide::Internal::GeneratorInputImpl< T, Expr >
bool is_array () const override
GeneratorInputImpl (const std::string &name, IOKind kind, const std::vector< Type > &t, int d)
GeneratorInputImpl (const std::string &name, IOKind kind, const std::vector< Type > &t, int d)
GeneratorInputImpl (const std::string &name, IOKind kind, const std::vector< Type > &t, int d)
Protected Member Functions inherited from Halide::Internal::GeneratorInputBase
GeneratorInputBase (size_t array_size, const std::string &name, IOKind kind, const std::vector< Type > &t, int d)
GeneratorInputBase (const std::string &name, IOKind kind, const std::vector< Type > &t, int d)
Parameter parameter () const
void init_internals ()
void set_inputs (const std::vector< StubInput > &inputs)
void verify_internals () override
void check_value_writable () const override
const char * input_or_output () const override
void set_estimate_impl (const Var &var, const Expr &min, const Expr &extent)
void set_estimates_impl (const Region &estimates)
Protected Member Functions inherited from Halide::Internal::GIOBase
GIOBase (size_t array_size, const std::string &name, IOKind kind, const std::vector< Type > &types, int dims)
std::string array_name (size_t i) const
void check_matching_array_size (size_t size) const
void check_matching_types (const std::vector< Type > &t) const
void check_matching_dims (int d) const
template<typename ElemType >
const std::vector< ElemType > & get_values () const
void check_gio_access () const
template<>
const std::vector< Expr > & get_values () const
template<>
const std::vector< Func > & get_values () const
Static Protected Member Functions
template<typename TBase2 = TBase, typename std::enable_if<!std::is_pointer< TBase2 >::value >::type * = nullptr>
static Expr TBaseToExpr (const TBase2 &value)
template<typename TBase2 = TBase, typename std::enable_if< std::is_pointer< TBase2 >::value >::type * = nullptr>
static Expr TBaseToExpr (const TBase2 &value)
Protected Attributes
const TBase def_ {TBase()}
const Expr def_expr_
Protected Attributes inherited from Halide::Internal::GeneratorInputBase
std::vector< Parameter > parameters_
Protected Attributes inherited from Halide::Internal::GIOBase
int array_size_
const std::string name_
const IOKind kind_
std::vector< Type > types_
int dims_
std::vector< Func > funcs_
std::vector< Expr > exprs_
GeneratorBase * generator {nullptr}
Detailed Description
template<typename T>
class Halide::Internal::GeneratorInput_Scalar< T >
Definition at line 1921 of file Generator.h.
Member Typedef Documentation
TBase
template<typename T > using Halide::Internal::GeneratorInput_Scalar< T >::TBase = typename Super::TBase protected
Definition at line 1926 of file Generator.h.
Constructor & Destructor Documentation
GeneratorInput_Scalar() [1/4]
template<typename T > Halide::Internal::GeneratorInput_Scalar< T >::GeneratorInput_Scalar (const std::string & name) inline explicit
Definition at line 1956 of file Generator.h.
References Halide::Internal::Scalar.
GeneratorInput_Scalar() [2/4]
template<typename T > Halide::Internal::GeneratorInput_Scalar< T >::GeneratorInput_Scalar (const std::string & name, const TBase & def) inline
Definition at line 1960 of file Generator.h.
References Halide::Internal::Scalar.
GeneratorInput_Scalar() [3/4]
template<typename T > Halide::Internal::GeneratorInput_Scalar< T >::GeneratorInput_Scalar (size_t array_size, const std::string & name) inline
Definition at line 1964 of file Generator.h.
References Halide::Internal::Scalar.
GeneratorInput_Scalar() [4/4]
template<typename T > Halide::Internal::GeneratorInput_Scalar< T >::GeneratorInput_Scalar (size_t array_size, const std::string & name, const TBase & def) inline
Definition at line 1969 of file Generator.h.
References Halide::Internal::Scalar.
Member Function Documentation
set_def_min_max()
template<typename T > void Halide::Internal::GeneratorInput_Scalar< T >::set_def_min_max () inline override protected virtual
Reimplemented from Halide::Internal::GeneratorInputBase.
Reimplemented in Halide::Internal::GeneratorInput_Arithmetic< T >.
Definition at line 1931 of file Generator.h.
References Halide::Internal::GeneratorInput_Scalar< T >::def_, Halide::Internal::GeneratorInput_Scalar< T >::def_expr_, Halide::Internal::GeneratorInputBase::parameters_, Halide::Internal::Parameter::set_default_value(), and Halide::Internal::Parameter::set_scalar().
Referenced by Halide::Internal::GeneratorInput_Arithmetic< T >::set_def_min_max().
get_c_type()
template<typename T > std::string Halide::Internal::GeneratorInput_Scalar< T >::get_c_type () const inline override protected virtual
Implements Halide::Internal::GeneratorInputBase.
Definition at line 1938 of file Generator.h.
TBaseToExpr() [1/2]
template<typename T > template<typename TBase2 = TBase, typename std::enable_if<!std::is_pointer< TBase2 >::value >::type * = nullptr> static Expr Halide::Internal::GeneratorInput_Scalar< T >::TBaseToExpr (const TBase2 & value) inline static protected
Definition at line 1945 of file Generator.h.
TBaseToExpr() [2/2]
template<typename T > template<typename TBase2 = TBase, typename std::enable_if< std::is_pointer< TBase2 >::value >::type * = nullptr> static Expr Halide::Internal::GeneratorInput_Scalar< T >::TBaseToExpr (const TBase2 & value) inline static protected
Definition at line 1950 of file Generator.h.
References user_assert.
operator Expr()
template<typename T > Halide::Internal::GeneratorInput_Scalar< T >::operator Expr () const inline
You can use this Input as an expression in a halide function definition.
Definition at line 1977 of file Generator.h.
References Halide::Internal::GIOBase::check_gio_access(), and Halide::Internal::GIOBase::exprs().
operator ExternFuncArgument()
template<typename T > Halide::Internal::GeneratorInput_Scalar< T >::operator ExternFuncArgument () const inline
Using an Input as the argument to an external stage treats it as an Expr.
Definition at line 1984 of file Generator.h.
References Halide::Internal::GeneratorInputImpl< T, Expr >::at(), Halide::Internal::GIOBase::check_gio_access(), and Halide::Internal::GIOBase::exprs().
set_estimate() [1/3]
template<typename T > template<typename T2 = T, typename std::enable_if< std::is_pointer< T2 >::value >::type * = nullptr> void Halide::Internal::GeneratorInput_Scalar< T >::set_estimate (const TBase & value) inline
Definition at line 1990 of file Generator.h.
References Halide::Internal::GIOBase::check_gio_access(), Halide::Internal::GeneratorInputBase::parameters_, Halide::reinterpret(), Halide::Internal::Parameter::set_estimate(), and user_assert.
set_estimate() [2/3]
template<typename T > template<typename T2 = T, typename std::enable_if<!std::is_array< T2 >::value &&!std::is_pointer< T2 >::value >::type * = nullptr> void Halide::Internal::GeneratorInput_Scalar< T >::set_estimate (const TBase & value) inline
Definition at line 2000 of file Generator.h.
References Halide::Internal::GIOBase::check_gio_access(), Halide::Internal::GeneratorInputBase::parameters_, and Halide::Internal::Parameter::set_estimate().
set_estimate() [3/3]
template<typename T > template<typename T2 = T, typename std::enable_if< std::is_array< T2 >::value >::type * = nullptr> void Halide::Internal::GeneratorInput_Scalar< T >::set_estimate (size_t index, const TBase & value) inline
Definition at line 2012 of file Generator.h.
References Halide::Internal::GIOBase::check_gio_access(), and Halide::Internal::GeneratorInputBase::parameters_.
Member Data Documentation
def_
template<typename T > const TBase Halide::Internal::GeneratorInput_Scalar< T >::def_ {TBase()} protected
Definition at line 1928 of file Generator.h.
Referenced by Halide::Internal::GeneratorInput_Scalar< T >::set_def_min_max().
def_expr_
template<typename T > const Expr Halide::Internal::GeneratorInput_Scalar< T >::def_expr_ protected
Definition at line 1929 of file Generator.h.
Referenced by Halide::Internal::GeneratorInput_Scalar< T >::set_def_min_max().
The documentation for this class was generated from the following file:
/Users/halidenightly/build_bot_new/worker/halide-main-llvm13-x86-64-osx-cmake/halide-source/src/Generator.h