Halide: Halide::Runtime::Buffer< T, D > Class Template Reference
Halide::Runtime::Buffer< T, D > Class Template Reference
A templated Buffer class that wraps halide_buffer_t and adds functionality.
#include <HalideBuffer.h>
Classes
class Dimension
Read-only access to the shape.
Public Types
typedef T ElemType
Public Member Functions
bool owns_host_memory () const
Does this Buffer own the host memory it refers to?
HALIDE_ALWAYS_INLINE Dimension dim (int i) const
Access the shape of the buffer.
int min (int i) const
Access to the mins, strides, extents.
int extent (int i) const
int stride (int i) const
size_t number_of_elements () const
The total number of elements this buffer represents.
int dimensions () const
Get the dimensionality of the buffer.
halide_type_t type () const
Get the type of the elements.
T * begin () const
A pointer to the element with the lowest address.
T * end () const
A pointer to one beyond the element with the highest address.
size_t size_in_bytes () const
The total number of bytes spanned by the data in memory.
void reset ()
Reset the Buffer to be equivalent to a default-constructed Buffer of the same static type (if any); Buffer<void> will have its runtime type reset to uint8.
Buffer ()
Buffer (const halide_buffer_t &buf, BufferDeviceOwnership ownership=BufferDeviceOwnership::Unmanaged)
Make a Buffer from a halide_buffer_t.
Buffer (const Buffer< T, D > &other)
Copy constructor.
template<typename T2 , int D2>
Buffer (const Buffer< T2, D2 > &other)
Construct a Buffer from a Buffer of different dimensionality and type.
Buffer (Buffer< T, D > &&other) noexcept
Move constructor.
template<typename T2 , int D2>
Buffer (Buffer< T2, D2 > &&other)
Move-construct a Buffer from a Buffer of different dimensionality and type.
template<typename T2 , int D2>
Buffer< T, D > & operator= (const Buffer< T2, D2 > &other)
Assign from another Buffer of possibly-different dimensionality and type.
Buffer< T, D > & operator= (const Buffer< T, D > &other)
Standard assignment operator.
template<typename T2 , int D2>
Buffer< T, D > & operator= (Buffer< T2, D2 > &&other)
Move from another Buffer of possibly-different dimensionality and type.
Buffer< T, D > & operator= (Buffer< T, D > &&other) noexcept
Standard move-assignment operator.
void check_overflow ()
Check the product of the extents fits in memory.
void allocate (void *(*allocate_fn)(size_t)=nullptr, void(*deallocate_fn)(void *)=nullptr)
Allocate memory for this Buffer.
void deallocate ()
Drop reference to any owned host or device memory, possibly freeing it, if this buffer held the last reference to it.
void device_deallocate ()
Drop reference to any owned device memory, possibly freeing it if this buffer held the last reference to it.
template<typename... Args, typename = typename std::enable_if<AllInts<Args...>::value>::type>
Buffer (halide_type_t t, int first, Args... rest)
Allocate a new image of the given size with a runtime type.
Buffer (int first)
Allocate a new image of the given size.
template<typename... Args, typename = typename std::enable_if<AllInts<Args...>::value>::type>
Buffer (int first, int second, Args... rest)
Buffer (halide_type_t t, const std::vector< int > &sizes)
Allocate a new image of unknown type using a vector of ints as the size.
Buffer (const std::vector< int > &sizes)
Allocate a new image of known type using a vector of ints as the size.
Buffer (halide_type_t t, const std::vector< int > &sizes, const std::vector< int > &storage_order)
Allocate a new image of unknown type using a vector of ints as the size and a vector of indices indicating the storage order for each dimension.
Buffer (const std::vector< int > &sizes, const std::vector< int > &storage_order)
template<typename Array , size_t N>
Buffer (Array(&vals)[N])
Make an Buffer that refers to a statically sized array.
template<typename... Args, typename = typename std::enable_if<AllInts<Args...>::value>::type>
Buffer (halide_type_t t, add_const_if_T_is_const< void > *data, int first, Args &&...rest)
Initialize an Buffer of runtime type from a pointer and some sizes.
template<typename... Args, typename = typename std::enable_if<AllInts<Args...>::value>::type>
Buffer (T *data, int first, Args &&...rest)
Initialize an Buffer from a pointer and some sizes.
Buffer (T *data, const std::vector< int > &sizes)
Initialize an Buffer from a pointer and a vector of sizes.
Buffer (halide_type_t t, add_const_if_T_is_const< void > *data, const std::vector< int > &sizes)
Initialize an Buffer of runtime type from a pointer and a vector of sizes.
Buffer (halide_type_t t, add_const_if_T_is_const< void > *data, int d, const halide_dimension_t *shape)
Initialize an Buffer from a pointer to the min coordinate and an array describing the shape.
Buffer (halide_type_t t, add_const_if_T_is_const< void > *data, const std::vector< halide_dimension_t > &shape)
Initialize a Buffer from a pointer to the min coordinate and a vector describing the shape.
Buffer (T *data, int d, const halide_dimension_t *shape)
Initialize an Buffer from a pointer to the min coordinate and an array describing the shape.
Buffer (T *data, const std::vector< halide_dimension_t > &shape)
Initialize a Buffer from a pointer to the min coordinate and a vector describing the shape.
~Buffer ()
Destructor.
halide_buffer_t * raw_buffer ()
Get a pointer to the raw halide_buffer_t this wraps.
const halide_buffer_t * raw_buffer () const
operator halide_buffer_t * ()
Provide a cast operator to halide_buffer_t *, so that instances can be passed directly to Halide filters.
template<typename T2 , int D2 = D, typename = typename std::enable_if<(D2 <= D)>::type>
HALIDE_ALWAYS_INLINE Buffer< T2, D2 > & as () &
Return a typed reference to this Buffer.
template<typename T2 , int D2 = D, typename = typename std::enable_if<(D2 <= D)>::type>
HALIDE_ALWAYS_INLINE const Buffer< T2, D2 > & as () const &
Return a const typed reference to this Buffer.
template<typename T2 , int D2 = D>
HALIDE_ALWAYS_INLINE Buffer< T2, D2 > as () &&
Returns this rval Buffer with a different type attached.
HALIDE_ALWAYS_INLINE Buffer< typename std::add_const< T >::type, D > & as_const () &
as_const() is syntactic sugar for .as<const T>(), to avoid the need to recapitulate the type argument.
HALIDE_ALWAYS_INLINE const Buffer< typename std::add_const< T >::type, D > & as_const () const &
HALIDE_ALWAYS_INLINE Buffer< typename std::add_const< T >::type, D > as_const () &&
int width () const
Conventional names for the first three dimensions.
int height () const
int channels () const
int left () const
Conventional names for the min and max value of each dimension.
int right () const
int top () const
int bottom () const
Buffer< not_const_T, D > copy (void *(*allocate_fn)(size_t)=nullptr, void(*deallocate_fn)(void *)=nullptr) const
Make a new image which is a deep copy of this image.
Buffer< not_const_T, D > copy_to_interleaved (void *(*allocate_fn)(size_t)=nullptr, void(*deallocate_fn)(void *)=nullptr) const
Like copy(), but the copy is created in interleaved memory layout (vs.
Buffer< not_const_T, D > copy_to_planar (void *(*allocate_fn)(size_t)=nullptr, void(*deallocate_fn)(void *)=nullptr) const
Like copy(), but the copy is created in planar memory layout (vs.
Buffer< T, D > alias () const
Make a copy of the Buffer which shares the underlying host and/or device allocations as the existing Buffer.
template<typename T2 , int D2>
void copy_from (const Buffer< T2, D2 > &other)
Fill a Buffer with the values at the same coordinates in another Buffer.
Buffer< T, D > cropped (int d, int min, int extent) const
Make an image that refers to a sub-range of this image along the given dimension.
void crop (int d, int min, int extent)
Crop an image in-place along the given dimension.
Buffer< T, D > cropped (const std::vector< std::pair< int, int >> &rect) const
Make an image that refers to a sub-rectangle of this image along the first N dimensions.
void crop (const std::vector< std::pair< int, int >> &rect)
Crop an image in-place along the first N dimensions.
Buffer< T, D > translated (int d, int dx) const
Make an image which refers to the same data with using translated coordinates in the given dimension.
void translate (int d, int delta)
Translate an image in-place along one dimension by changing how it is indexed.
Buffer< T, D > translated (const std::vector< int > &delta) const
Make an image which refers to the same data translated along the first N dimensions.
void translate (const std::vector< int > &delta)
Translate an image along the first N dimensions by changing how it is indexed.
void set_min (const std::vector< int > &mins)
Set the min coordinate of an image in the first N dimensions.
template<typename... Args>
void set_min (Args... args)
bool contains (const std::vector< int > &coords) const
Test if a given coordinate is within the bounds of an image.
template<typename... Args>
bool contains (Args... args) const
Buffer< T, D > transposed (int d1, int d2) const
Make a buffer which refers to the same data in the same layout using a swapped indexing order for the dimensions given.
void transpose (int d1, int d2)
Transpose a buffer in-place by changing how it is indexed.
void transpose (const std::vector< int > &order)
A generalized transpose: instead of swapping two dimensions, pass a vector that lists each dimension index exactly once, in the desired order.
Buffer< T, D > transposed (const std::vector< int > &order) const
Make a buffer which refers to the same data in the same layout using a different ordering of the dimensions.
Buffer< T, D > sliced (int d, int pos) const
Make a lower-dimensional buffer that refers to one slice of this buffer.
Buffer< T, D > sliced (int d) const
Make a lower-dimensional buffer that refers to one slice of this buffer at the dimension's minimum.
void slice (int d, int pos)
Rewrite the buffer to refer to a single lower-dimensional slice of itself along the given dimension at the given coordinate.
void slice (int d)
Slice a buffer in-place at the dimension's minimum.
Buffer< T, D > embedded (int d, int pos=0) const
Make a new buffer that views this buffer as a single slice in a higher-dimensional space.
void embed (int d, int pos=0)
Embed a buffer in-place, increasing the dimensionality.
void add_dimension ()
Add a new dimension with a min of zero and an extent of one.
void add_dimension_with_stride (int s)
Add a new dimension with a min of zero, an extent of one, and the specified stride.
HALIDE_ALWAYS_INLINE void set_host_dirty (bool v=true)
Methods for managing any GPU allocation.
HALIDE_ALWAYS_INLINE bool device_dirty () const
bool host_dirty () const
void set_device_dirty (bool v=true)
int copy_to_host (void *ctx=nullptr)
int copy_to_device (const struct halide_device_interface_t *device_interface, void *ctx=nullptr)
int device_malloc (const struct halide_device_interface_t *device_interface, void *ctx=nullptr)
int device_free (void *ctx=nullptr)
int device_wrap_native (const struct halide_device_interface_t *device_interface, uint64_t handle, void *ctx=nullptr)
int device_detach_native (void *ctx=nullptr)
int device_and_host_malloc (const struct halide_device_interface_t *device_interface, void *ctx=nullptr)
int device_and_host_free (const struct halide_device_interface_t *device_interface, void *ctx=nullptr)
int device_sync (void *ctx=nullptr)
bool has_device_allocation () const
BufferDeviceOwnership device_ownership () const
Return the method by which the device field is managed.
T * data () const
Get a pointer to the address of the min coordinate.
template<typename... Args, typename = typename std::enable_if<AllInts<Args...>::value>::type>
HALIDE_ALWAYS_INLINE const not_void_T & operator() (int first, Args... rest) const
Access elements.
HALIDE_ALWAYS_INLINE const not_void_T & operator() () const
HALIDE_ALWAYS_INLINE const not_void_T & operator() (const int *pos) const
template<typename... Args, typename = typename std::enable_if<AllInts<Args...>::value>::type>
HALIDE_ALWAYS_INLINE not_void_T & operator() (int first, Args... rest)
HALIDE_ALWAYS_INLINE not_void_T & operator() ()
HALIDE_ALWAYS_INLINE not_void_T & operator() (const int *pos)
bool all_equal (not_void_T val) const
Tests that all values in this buffer are equal to val.
Buffer< T, D > & fill (not_void_T val)
template<typename Fn , typename... Args, int N = sizeof...(Args) + 1>
HALIDE_ALWAYS_INLINE const Buffer< T, D > & for_each_value (Fn &&f, Args &&...other_buffers) const
Call a function on every value in the buffer, and the corresponding values in some number of other buffers of the same size.
template<typename Fn , typename... Args, int N = sizeof...(Args) + 1>
HALIDE_ALWAYS_INLINE Buffer< T, D > & for_each_value (Fn &&f, Args &&...other_buffers)
template<typename Fn >
HALIDE_ALWAYS_INLINE const Buffer< T, D > & for_each_element (Fn &&f) const
Call a function at each site in a buffer.
template<typename Fn >
HALIDE_ALWAYS_INLINE Buffer< T, D > & for_each_element (Fn &&f)
template<typename Fn , typename = typename std::enable_if<!std::is_arithmetic<typename std::decay<Fn>::type>::value>::type>
Buffer< T, D > & fill (Fn &&f)
Fill a buffer by evaluating a callable at every site.
bool is_bounds_query () const
Check if an input buffer passed extern stage is a querying bounds.
void msan_check_mem_is_initialized (bool entire=false) const
Convenient check to verify that all of the interesting bytes in the Buffer are initialized under MSAN.
Static Public Member Functions
static halide_type_t static_halide_type ()
Get the Halide type of T.
template<typename T2 , int D2>
static bool can_convert_from (const Buffer< T2, D2 > &other)
Determine if if an Buffer<T, D> can be constructed from some other Buffer type.
template<typename T2 , int D2>
static void assert_can_convert_from (const Buffer< T2, D2 > &other)
Fail an assertion at runtime or compile-time if an Buffer<T, D> cannot be constructed from some other Buffer type.
static Buffer< void, D > make_interleaved (halide_type_t t, int width, int height, int channels)
If you use the (x, y, c) indexing convention, then Halide Buffers are stored planar by default.
static Buffer< T, D > make_interleaved (int width, int height, int channels)
If you use the (x, y, c) indexing convention, then Halide Buffers are stored planar by default.
static Buffer< add_const_if_T_is_const< void >, D > make_interleaved (halide_type_t t, T *data, int width, int height, int channels)
Wrap an existing interleaved image.
static Buffer< T, D > make_interleaved (T *data, int width, int height, int channels)
Wrap an existing interleaved image.
static Buffer< add_const_if_T_is_const< void >, D > make_scalar (halide_type_t t)
Make a zero-dimensional Buffer.
static Buffer< T, D > make_scalar ()
Make a zero-dimensional Buffer.
static Buffer< T, D > make_scalar (T *data)
Make a zero-dimensional Buffer that points to non-owned, existing data.
template<typename T2 , int D2>
static Buffer< T, D > make_with_shape_of (Buffer< T2, D2 > src, void *(*allocate_fn)(size_t)=nullptr, void(*deallocate_fn)(void *)=nullptr)
Make a buffer with the same shape and memory nesting order as another buffer.
Static Public Attributes
static constexpr bool has_static_halide_type = !T_is_void
True if the Halide type is not void (or const void).
Detailed Description
template<typename T = void, int D = 4>
class Halide::Runtime::Buffer< T, D >
A templated Buffer class that wraps halide_buffer_t and adds functionality.
When using Halide from C++, this is the preferred way to create input and output buffers. The overhead of using this class relative to a naked halide_buffer_t is minimal - it uses another ~16 bytes on the stack, and does no dynamic allocations when using it to represent existing memory of a known maximum dimensionality.
The template parameter T is the element type. For buffers where the element type is unknown, or may vary, use void or const void.
D is the maximum number of dimensions that can be represented using space inside the class itself. Set it to the maximum dimensionality you expect this buffer to be. If the actual dimensionality exceeds this, heap storage is allocated to track the shape of the buffer. D defaults to 4, which should cover nearly all usage.
The class optionally allocates and owns memory for the image using a shared pointer allocated with the provided allocator. If they are null, malloc and free are used. Any device-side allocation is considered as owned if and only if the host-side allocation is owned.
Examples
tutorial/lesson_10_aot_compilation_run.cpp.
Definition at line 131 of file HalideBuffer.h.
Member Typedef Documentation
ElemType
template<typename T = void, int D = 4> typedef T Halide::Runtime::Buffer< T, D >::ElemType
Definition at line 439 of file HalideBuffer.h.
Constructor & Destructor Documentation
Buffer() [1/22]
template<typename T = void, int D = 4> Halide::Runtime::Buffer< T, D >::Buffer () inline
Definition at line 588 of file HalideBuffer.h.
References buf, and Halide::Runtime::Buffer< T, D >::static_halide_type().
Buffer() [2/22]
template<typename T = void, int D = 4> Halide::Runtime::Buffer< T, D >::Buffer (const halide_buffer_t & buf, BufferDeviceOwnership ownership = BufferDeviceOwnership::Unmanaged) inline explicit
Make a Buffer from a halide_buffer_t.
Definition at line 595 of file HalideBuffer.h.
References buf, and Halide::Runtime::Buffer< T, D >::static_halide_type().
Buffer() [3/22]
template<typename T = void, int D = 4> Halide::Runtime::Buffer< T, D >::Buffer (const Buffer< T, D > & other) inline
Copy constructor.
Does not copy underlying data.
Definition at line 641 of file HalideBuffer.h.
Buffer() [4/22]
template<typename T = void, int D = 4> template<typename T2 , int D2> Halide::Runtime::Buffer< T, D >::Buffer (const Buffer< T2, D2 > & other) inline
Construct a Buffer from a Buffer of different dimensionality and type.
Asserts that the type matches (at runtime, if one of the types is void). Note that this constructor is implicit. This, for example, lets you pass things like Buffer<T> or Buffer<const void> to functions expected Buffer<const T>.
Definition at line 656 of file HalideBuffer.h.
References Halide::Runtime::Buffer< T, D >::assert_can_convert_from().
Buffer() [5/22]
template<typename T = void, int D = 4> Halide::Runtime::Buffer< T, D >::Buffer (Buffer< T, D > && other) inline noexcept
Move constructor.
Definition at line 666 of file HalideBuffer.h.
Buffer() [6/22]
template<typename T = void, int D = 4> template<typename T2 , int D2> Halide::Runtime::Buffer< T, D >::Buffer (Buffer< T2, D2 > && other) inline
Move-construct a Buffer from a Buffer of different dimensionality and type.
Asserts that the types match (at runtime if one of the types is void).
Definition at line 680 of file HalideBuffer.h.
References Halide::Runtime::Buffer< T, D >::assert_can_convert_from().
Buffer() [7/22]
template<typename T = void, int D = 4> template<typename... Args, typename = typename std::enable_if<AllInts<Args...>::value>::type> Halide::Runtime::Buffer< T, D >::Buffer (halide_type_t t, int first, Args... rest) inline
Allocate a new image of the given size with a runtime type.
Only used when you do know what size you want but you don't know statically what type the elements are. Pass zeroes to make a buffer suitable for bounds query calls.
Definition at line 818 of file HalideBuffer.h.
References Halide::Runtime::Buffer< T, D >::allocate(), Halide::Runtime::Internal::any_zero(), buf, Halide::Runtime::Buffer< T, D >::check_overflow(), and Halide::Runtime::Buffer< T, D >::static_halide_type().
Buffer() [8/22]
template<typename T = void, int D = 4> Halide::Runtime::Buffer< T, D >::Buffer (int first) inline explicit
Allocate a new image of the given size.
Pass zeroes to make a buffer suitable for bounds query calls.
Definition at line 839 of file HalideBuffer.h.
References Halide::Runtime::Buffer< T, D >::allocate(), buf, Halide::Runtime::Buffer< T, D >::check_overflow(), and Halide::Runtime::Buffer< T, D >::static_halide_type().
Buffer() [9/22]
template<typename T = void, int D = 4> template<typename... Args, typename = typename std::enable_if<AllInts<Args...>::value>::type> Halide::Runtime::Buffer< T, D >::Buffer (int first, int second, Args... rest) inline
Definition at line 855 of file HalideBuffer.h.
References Halide::Runtime::Buffer< T, D >::allocate(), Halide::Runtime::Internal::any_zero(), buf, Halide::Runtime::Buffer< T, D >::check_overflow(), and Halide::Runtime::Buffer< T, D >::static_halide_type().
Buffer() [10/22]
template<typename T = void, int D = 4> Halide::Runtime::Buffer< T, D >::Buffer (halide_type_t t, const std::vector< int > & sizes) inline
Allocate a new image of unknown type using a vector of ints as the size.
Definition at line 871 of file HalideBuffer.h.
References Halide::Runtime::Buffer< T, D >::allocate(), Halide::Runtime::Internal::any_zero(), buf, Halide::Runtime::Buffer< T, D >::check_overflow(), and Halide::Runtime::Buffer< T, D >::static_halide_type().
Buffer() [11/22]
template<typename T = void, int D = 4> Halide::Runtime::Buffer< T, D >::Buffer (const std::vector< int > & sizes) inline explicit
Allocate a new image of known type using a vector of ints as the size.
Definition at line 885 of file HalideBuffer.h.
Buffer() [12/22]
template<typename T = void, int D = 4> Halide::Runtime::Buffer< T, D >::Buffer (halide_type_t t, const std::vector< int > & sizes, const std::vector< int > & storage_order) inline
Allocate a new image of unknown type using a vector of ints as the size and a vector of indices indicating the storage order for each dimension.
The length of the sizes vector and the storage-order vector must match. For instance, to allocate an interleaved RGB buffer, you would pass {2, 0, 1} for storage_order.
Definition at line 905 of file HalideBuffer.h.
References Halide::Runtime::Buffer< T, D >::transpose().
Buffer() [13/22]
template<typename T = void, int D = 4> Halide::Runtime::Buffer< T, D >::Buffer (const std::vector< int > & sizes, const std::vector< int > & storage_order) inline
Definition at line 910 of file HalideBuffer.h.
Buffer() [14/22]
template<typename T = void, int D = 4> template<typename Array , size_t N> Halide::Runtime::Buffer< T, D >::Buffer (Array(&) vals[N]) inline explicit
Make an Buffer that refers to a statically sized array.
Does not take ownership of the data, and does not set the host_dirty flag.
Definition at line 917 of file HalideBuffer.h.
References buf.
Buffer() [15/22]
template<typename T = void, int D = 4> template<typename... Args, typename = typename std::enable_if<AllInts<Args...>::value>::type> Halide::Runtime::Buffer< T, D >::Buffer (halide_type_t t, add_const_if_T_is_const< void > * data, int first, Args &&... rest) inline explicit
Initialize an Buffer of runtime type from a pointer and some sizes.
Assumes dense row-major packing and a min coordinate of zero. Does not take ownership of the data and does not set the host_dirty flag.
Definition at line 931 of file HalideBuffer.h.
References buf, Halide::Runtime::Buffer< T, D >::data(), and Halide::Runtime::Buffer< T, D >::static_halide_type().
Buffer() [16/22]
template<typename T = void, int D = 4> template<typename... Args, typename = typename std::enable_if<AllInts<Args...>::value>::type> Halide::Runtime::Buffer< T, D >::Buffer (T * data, int first, Args &&... rest) inline explicit
Initialize an Buffer from a pointer and some sizes.
Assumes dense row-major packing and a min coordinate of zero. Does not take ownership of the data and does not set the host_dirty flag.
Definition at line 948 of file HalideBuffer.h.
References buf, Halide::Runtime::Buffer< T, D >::data(), and Halide::Runtime::Buffer< T, D >::static_halide_type().
Buffer() [17/22]
template<typename T = void, int D = 4> Halide::Runtime::Buffer< T, D >::Buffer (T * data, const std::vector< int > & sizes) inline explicit
Initialize an Buffer from a pointer and a vector of sizes.
Assumes dense row-major packing and a min coordinate of zero. Does not take ownership of the data and does not set the host_dirty flag.
Definition at line 961 of file HalideBuffer.h.
References buf, Halide::Runtime::Buffer< T, D >::data(), and Halide::Runtime::Buffer< T, D >::static_halide_type().
Buffer() [18/22]
template<typename T = void, int D = 4> Halide::Runtime::Buffer< T, D >::Buffer (halide_type_t t, add_const_if_T_is_const< void > * data, const std::vector< int > & sizes) inline explicit
Initialize an Buffer of runtime type from a pointer and a vector of sizes.
Assumes dense row-major packing and a min coordinate of zero. Does not take ownership of the data and does not set the host_dirty flag.
Definition at line 972 of file HalideBuffer.h.
References buf, Halide::Runtime::Buffer< T, D >::data(), and Halide::Runtime::Buffer< T, D >::static_halide_type().
Buffer() [19/22]
template<typename T = void, int D = 4> Halide::Runtime::Buffer< T, D >::Buffer (halide_type_t t, add_const_if_T_is_const< void > * data, int d, const halide_dimension_t * shape) inline explicit
Initialize an Buffer from a pointer to the min coordinate and an array describing the shape.
Does not take ownership of the data, and does not set the host_dirty flag.
Definition at line 985 of file HalideBuffer.h.
References buf, Halide::Runtime::Buffer< T, D >::data(), and Halide::Runtime::Buffer< T, D >::static_halide_type().
Buffer() [20/22]
template<typename T = void, int D = 4> Halide::Runtime::Buffer< T, D >::Buffer (halide_type_t t, add_const_if_T_is_const< void > * data, const std::vector< halide_dimension_t > & shape) inline explicit
Initialize a Buffer from a pointer to the min coordinate and a vector describing the shape.
Does not take ownership of the data, and does not set the host_dirty flag.
Definition at line 1000 of file HalideBuffer.h.
Buffer() [21/22]
template<typename T = void, int D = 4> Halide::Runtime::Buffer< T, D >::Buffer (T * data, int d, const halide_dimension_t * shape) inline explicit
Initialize an Buffer from a pointer to the min coordinate and an array describing the shape.
Does not take ownership of the data and does not set the host_dirty flag.
Definition at line 1008 of file HalideBuffer.h.
References buf, Halide::Runtime::Buffer< T, D >::data(), and Halide::Runtime::Buffer< T, D >::static_halide_type().
Buffer() [22/22]
template<typename T = void, int D = 4> Halide::Runtime::Buffer< T, D >::Buffer (T * data, const std::vector< halide_dimension_t > & shape) inline explicit
Initialize a Buffer from a pointer to the min coordinate and a vector describing the shape.
Does not take ownership of the data, and does not set the host_dirty flag.
Definition at line 1020 of file HalideBuffer.h.
~Buffer()
template<typename T = void, int D = 4> Halide::Runtime::Buffer< T, D >::~Buffer () inline
Destructor.
Will release any underlying owned allocation if this is the last reference to it. Will assert fail if there are weak references to this Buffer outstanding.
Definition at line 1027 of file HalideBuffer.h.
Member Function Documentation
static_halide_type()
template<typename T = void, int D = 4> static halide_type_t Halide::Runtime::Buffer< T, D >::static_halide_type () inline static
Get the Halide type of T.
Callers should not use the result if has_static_halide_type is false.
Definition at line 174 of file HalideBuffer.h.
Referenced by Halide::Runtime::Buffer< T, D >::Buffer(), Halide::Runtime::Buffer< T, D >::can_convert_from(), Halide::Runtime::Buffer< T, D >::make_interleaved(), and Halide::Buffer< T >::static_halide_type().
owns_host_memory()
template<typename T = void, int D = 4> bool Halide::Runtime::Buffer< T, D >::owns_host_memory () const inline
Does this Buffer own the host memory it refers to?
Definition at line 179 of file HalideBuffer.h.
dim()
template<typename T = void, int D = 4> HALIDE_ALWAYS_INLINE Dimension Halide::Runtime::Buffer< T, D >::dim (int i) const inline
Access the shape of the buffer.
Definition at line 498 of file HalideBuffer.h.
References buf, and Halide::Runtime::Buffer< T, D >::dimensions().
Referenced by Halide::Runtime::Buffer< T, D >::bottom(), Halide::Runtime::Buffer< T, D >::channels(), Halide::Runtime::Buffer< T, D >::check_overflow(), Halide::Runtime::Buffer< T, D >::contains(), Halide::Runtime::Buffer< T, D >::copy_from(), Halide::Runtime::Buffer< T, D >::copy_to_planar(), Halide::Runtime::Buffer< T, D >::extent(), Halide::Runtime::Buffer< T, D >::height(), Halide::Runtime::Buffer< T, D >::left(), Halide::Runtime::Buffer< T, D >::min(), Halide::Runtime::Buffer< T, D >::number_of_elements(), Halide::Runtime::Buffer< T, D >::right(), Halide::Runtime::Buffer< T, D >::slice(), Halide::Runtime::Buffer< T, D >::sliced(), Halide::Runtime::Buffer< T, D >::stride(), Halide::Runtime::Buffer< T, D >::top(), and Halide::Runtime::Buffer< T, D >::width().
min()
template<typename T = void, int D = 4> int Halide::Runtime::Buffer< T, D >::min (int i) const inline
Access to the mins, strides, extents.
Will be deprecated. Do not use.
Definition at line 505 of file HalideBuffer.h.
References Halide::Runtime::Buffer< T, D >::dim(), and Halide::Runtime::Buffer< T, D >::Dimension::min().
Referenced by Halide::Runtime::Buffer< T, D >::contains(), Halide::Runtime::Buffer< T, D >::copy_to_interleaved(), Halide::Runtime::Buffer< T, D >::copy_to_planar(), Halide::Runtime::Buffer< T, D >::crop(), Halide::Runtime::Buffer< T, D >::cropped(), Halide::Runtime::Buffer< T, D >::slice(), and Halide::Runtime::Buffer< T, D >::sliced().
extent()
template<typename T = void, int D = 4> int Halide::Runtime::Buffer< T, D >::extent (int i) const inline
Definition at line 508 of file HalideBuffer.h.
References Halide::Runtime::Buffer< T, D >::dim(), and Halide::Runtime::Buffer< T, D >::Dimension::extent().
Referenced by Halide::Runtime::Buffer< T, D >::copy_to_planar(), Halide::Runtime::Buffer< T, D >::crop(), and Halide::Runtime::Buffer< T, D >::cropped().
stride()
template<typename T = void, int D = 4> int Halide::Runtime::Buffer< T, D >::stride (int i) const inline
Definition at line 511 of file HalideBuffer.h.
References Halide::Runtime::Buffer< T, D >::dim(), and Halide::Runtime::Buffer< T, D >::Dimension::stride().
number_of_elements()
template<typename T = void, int D = 4> size_t Halide::Runtime::Buffer< T, D >::number_of_elements () const inline
The total number of elements this buffer represents.
Equal to the product of the extents
Definition at line 518 of file HalideBuffer.h.
References Halide::Runtime::Buffer< T, D >::dim(), Halide::Runtime::Buffer< T, D >::dimensions(), and Halide::Runtime::Buffer< T, D >::Dimension::extent().
dimensions()
template<typename T = void, int D = 4> int Halide::Runtime::Buffer< T, D >::dimensions () const inline
Get the dimensionality of the buffer.
Definition at line 527 of file HalideBuffer.h.
References buf.
Referenced by Halide::Runtime::Buffer< T, D >::channels(), Halide::Runtime::Buffer< T, D >::check_overflow(), Halide::Runtime::Buffer< T, D >::contains(), Halide::Runtime::Buffer< T, D >::copy_from(), Halide::Runtime::Buffer< T, D >::copy_to_interleaved(), Halide::Runtime::Buffer< T, D >::copy_to_planar(), Halide::Runtime::Buffer< T, D >::dim(), Halide::Runtime::Buffer< T, D >::embed(), Halide::Runtime::Buffer< T, D >::height(), Halide::Runtime::Buffer< T, D >::make_with_shape_of(), Halide::Runtime::Buffer< T, D >::number_of_elements(), Halide::Runtime::Buffer< T, D >::set_min(), Halide::Runtime::Buffer< T, D >::translate(), Halide::Runtime::Buffer< T, D >::transpose(), and Halide::Runtime::Buffer< T, D >::width().
type()
template<typename T = void, int D = 4> halide_type_t Halide::Runtime::Buffer< T, D >::type () const inline
Get the type of the elements.
Definition at line 532 of file HalideBuffer.h.
References buf.
Referenced by Halide::Runtime::Buffer< T, D >::begin(), Halide::Runtime::Buffer< T, D >::can_convert_from(), Halide::Runtime::Buffer< T, D >::check_overflow(), Halide::Runtime::Buffer< T, D >::copy_from(), Halide::Runtime::Buffer< T, D >::end(), Halide::Runtime::Buffer< T, D >::make_with_shape_of(), and Halide::Runtime::Buffer< T, D >::size_in_bytes().
begin()
template<typename T = void, int D = 4> T* Halide::Runtime::Buffer< T, D >::begin () const inline
A pointer to the element with the lowest address.
If all strides are positive, equal to the host pointer.
Definition at line 565 of file HalideBuffer.h.
References buf, and Halide::Runtime::Buffer< T, D >::type().
end()
template<typename T = void, int D = 4> T* Halide::Runtime::Buffer< T, D >::end () const inline
A pointer to one beyond the element with the highest address.
Definition at line 571 of file HalideBuffer.h.
References buf, and Halide::Runtime::Buffer< T, D >::type().
size_in_bytes()
template<typename T = void, int D = 4> size_t Halide::Runtime::Buffer< T, D >::size_in_bytes () const inline
The total number of bytes spanned by the data in memory.
Definition at line 577 of file HalideBuffer.h.
References Halide::Runtime::Buffer< T, D >::type().
Referenced by Halide::Runtime::Buffer< T, D >::allocate(), and Halide::Runtime::Buffer< T, D >::msan_check_mem_is_initialized().
reset()
template<typename T = void, int D = 4> void Halide::Runtime::Buffer< T, D >::reset () inline
Reset the Buffer to be equivalent to a default-constructed Buffer of the same static type (if any); Buffer<void> will have its runtime type reset to uint8.
Definition at line 584 of file HalideBuffer.h.
References Halide::Runtime::Buffer< T, D >::Buffer.
can_convert_from()
template<typename T = void, int D = 4> template<typename T2 , int D2> static bool Halide::Runtime::Buffer< T, D >::can_convert_from (const Buffer< T2, D2 > & other) inline static
Determine if if an Buffer<T, D> can be constructed from some other Buffer type.
If this can be determined at compile time, fail with a static assert; otherwise return a boolean based on runtime typing.
Definition at line 621 of file HalideBuffer.h.
References Halide::Runtime::Buffer< T, D >::static_halide_type(), and Halide::Runtime::Buffer< T, D >::type().
Referenced by Halide::Runtime::Buffer< T, D >::assert_can_convert_from(), and Halide::Buffer< T >::can_convert_from().
assert_can_convert_from()
template<typename T = void, int D = 4> template<typename T2 , int D2> static void Halide::Runtime::Buffer< T, D >::assert_can_convert_from (const Buffer< T2, D2 > & other) inline static
Fail an assertion at runtime or compile-time if an Buffer<T, D> cannot be constructed from some other Buffer type.
Definition at line 632 of file HalideBuffer.h.
References Halide::Runtime::Buffer< T, D >::can_convert_from().
Referenced by Halide::Runtime::Buffer< T, D >::as(), Halide::Runtime::Buffer< T, D >::Buffer(), and Halide::Runtime::Buffer< T, D >::operator=().
operator=() [1/4]
template<typename T = void, int D = 4> template<typename T2 , int D2> Buffer<T, D>& Halide::Runtime::Buffer< T, D >::operator= (const Buffer< T2, D2 > & other) inline
Assign from another Buffer of possibly-different dimensionality and type.
Asserts that the types match (at runtime if one of the types is void).
Definition at line 695 of file HalideBuffer.h.
References Halide::Runtime::Buffer< T, D >::assert_can_convert_from(), and buf.
operator=() [2/4]
template<typename T = void, int D = 4> Buffer<T, D>& Halide::Runtime::Buffer< T, D >::operator= (const Buffer< T, D > & other) inline
Standard assignment operator.
Definition at line 711 of file HalideBuffer.h.
References buf.
operator=() [3/4]
template<typename T = void, int D = 4> template<typename T2 , int D2> Buffer<T, D>& Halide::Runtime::Buffer< T, D >::operator= (Buffer< T2, D2 > && other) inline
Move from another Buffer of possibly-different dimensionality and type.
Asserts that the types match (at runtime if one of the types is void).
Definition at line 730 of file HalideBuffer.h.
References Halide::Runtime::Buffer< T, D >::assert_can_convert_from(), and buf.
operator=() [4/4]
template<typename T = void, int D = 4> Buffer<T, D>& Halide::Runtime::Buffer< T, D >::operator= (Buffer< T, D > && other) inline noexcept
Standard move-assignment operator.
Definition at line 745 of file HalideBuffer.h.
References buf.
check_overflow()
template<typename T = void, int D = 4> void Halide::Runtime::Buffer< T, D >::check_overflow () inline
Check the product of the extents fits in memory.
Definition at line 759 of file HalideBuffer.h.
References Halide::Runtime::Buffer< T, D >::dim(), Halide::Runtime::Buffer< T, D >::dimensions(), Halide::Runtime::Buffer< T, D >::Dimension::extent(), and Halide::Runtime::Buffer< T, D >::type().
Referenced by Halide::Runtime::Buffer< T, D >::Buffer().
allocate()
template<typename T = void, int D = 4> void Halide::Runtime::Buffer< T, D >::allocate (void *(*)(size_t) allocate_fn = nullptr, void(*)(void *) deallocate_fn = nullptr) inline
Allocate memory for this Buffer.
Drops the reference to any owned memory.
Definition at line 774 of file HalideBuffer.h.
References buf, Halide::Runtime::Buffer< T, D >::deallocate(), free(), malloc(), and Halide::Runtime::Buffer< T, D >::size_in_bytes().
Referenced by Halide::Runtime::Buffer< T, D >::Buffer().
deallocate()
template<typename T = void, int D = 4> void Halide::Runtime::Buffer< T, D >::deallocate () inline
Drop reference to any owned host or device memory, possibly freeing it, if this buffer held the last reference to it.
Retains the shape of the buffer. Does nothing if this buffer did not allocate its own memory.
Definition at line 801 of file HalideBuffer.h.
Referenced by Halide::Runtime::Buffer< T, D >::allocate().
device_deallocate()
template<typename T = void, int D = 4> void Halide::Runtime::Buffer< T, D >::device_deallocate () inline
Drop reference to any owned device memory, possibly freeing it if this buffer held the last reference to it.
Asserts that device_dirty is false.
Definition at line 808 of file HalideBuffer.h.
Referenced by Halide::Runtime::Buffer< T, D >::cropped(), Halide::Runtime::Buffer< T, D >::set_min(), Halide::Runtime::Buffer< T, D >::sliced(), and Halide::Runtime::Buffer< T, D >::translate().
raw_buffer() [1/2]
template<typename T = void, int D = 4> halide_buffer_t* Halide::Runtime::Buffer< T, D >::raw_buffer () inline
Get a pointer to the raw halide_buffer_t this wraps.
Definition at line 1034 of file HalideBuffer.h.
References buf.
raw_buffer() [2/2]
template<typename T = void, int D = 4> const halide_buffer_t* Halide::Runtime::Buffer< T, D >::raw_buffer () const inline
Definition at line 1038 of file HalideBuffer.h.
References buf.
operator halide_buffer_t *()
template<typename T = void, int D = 4> Halide::Runtime::Buffer< T, D >::operator halide_buffer_t * () inline
Provide a cast operator to halide_buffer_t *, so that instances can be passed directly to Halide filters.
Definition at line 1045 of file HalideBuffer.h.
References buf.
as() [1/3]
template<typename T = void, int D = 4> template<typename T2 , int D2 = D, typename = typename std::enable_if<(D2 <= D)>::type> HALIDE_ALWAYS_INLINE Buffer<T2, D2>& Halide::Runtime::Buffer< T, D >::as () & inline
Return a typed reference to this Buffer.
Useful for converting a reference to a Buffer<void> to a reference to, for example, a Buffer<const uint8_t>, or converting a Buffer<T>& to Buffer<const T>&. Does a runtime assert if the source buffer type is void.
Definition at line 1057 of file HalideBuffer.h.
References Halide::Runtime::Buffer< T, D >::assert_can_convert_from().
as() [2/3]
template<typename T = void, int D = 4> template<typename T2 , int D2 = D, typename = typename std::enable_if<(D2 <= D)>::type> HALIDE_ALWAYS_INLINE const Buffer<T2, D2>& Halide::Runtime::Buffer< T, D >::as () const & inline
Return a const typed reference to this Buffer.
Useful for converting a conference reference to one Buffer type to a const reference to another Buffer type. Does a runtime assert if the source buffer type is void.
Definition at line 1068 of file HalideBuffer.h.
References Halide::Runtime::Buffer< T, D >::assert_can_convert_from().
as() [3/3]
template<typename T = void, int D = 4> template<typename T2 , int D2 = D> HALIDE_ALWAYS_INLINE Buffer<T2, D2> Halide::Runtime::Buffer< T, D >::as () && inline
Returns this rval Buffer with a different type attached.
Does a dynamic type check if the source type is void.
Definition at line 1078 of file HalideBuffer.h.
References Halide::Runtime::Buffer< T, D >::assert_can_convert_from().
as_const() [1/3]
template<typename T = void, int D = 4> HALIDE_ALWAYS_INLINE Buffer<typename std::add_const<T>::type, D>& Halide::Runtime::Buffer< T, D >::as_const () & inline
as_const() is syntactic sugar for .as<const T>(), to avoid the need to recapitulate the type argument.
Definition at line 1087 of file HalideBuffer.h.
as_const() [2/3]
template<typename T = void, int D = 4> HALIDE_ALWAYS_INLINE const Buffer<typename std::add_const<T>::type, D>& Halide::Runtime::Buffer< T, D >::as_const () const & inline
Definition at line 1094 of file HalideBuffer.h.
as_const() [3/3]
template<typename T = void, int D = 4> HALIDE_ALWAYS_INLINE Buffer<typename std::add_const<T>::type, D> Halide::Runtime::Buffer< T, D >::as_const () && inline
Definition at line 1099 of file HalideBuffer.h.
width()
template<typename T = void, int D = 4> int Halide::Runtime::Buffer< T, D >::width () const inline
Conventional names for the first three dimensions.
Definition at line 1106 of file HalideBuffer.h.
References Halide::Runtime::Buffer< T, D >::dim(), Halide::Runtime::Buffer< T, D >::dimensions(), and Halide::Runtime::Buffer< T, D >::Dimension::extent().
Referenced by Halide::Runtime::Buffer< T, D >::copy_to_interleaved(), and Halide::Runtime::Buffer< T, D >::make_interleaved().
height()
template<typename T = void, int D = 4> int Halide::Runtime::Buffer< T, D >::height () const inline
Definition at line 1109 of file HalideBuffer.h.
References Halide::Runtime::Buffer< T, D >::dim(), Halide::Runtime::Buffer< T, D >::dimensions(), and Halide::Runtime::Buffer< T, D >::Dimension::extent().
Referenced by Halide::Runtime::Buffer< T, D >::copy_to_interleaved(), and Halide::Runtime::Buffer< T, D >::make_interleaved().
channels()
template<typename T = void, int D = 4> int Halide::Runtime::Buffer< T, D >::channels () const inline
Definition at line 1112 of file HalideBuffer.h.
References Halide::Runtime::Buffer< T, D >::dim(), Halide::Runtime::Buffer< T, D >::dimensions(), and Halide::Runtime::Buffer< T, D >::Dimension::extent().
Referenced by Halide::Runtime::Buffer< T, D >::copy_to_interleaved(), and Halide::Runtime::Buffer< T, D >::make_interleaved().
left()
template<typename T = void, int D = 4> int Halide::Runtime::Buffer< T, D >::left () const inline
Conventional names for the min and max value of each dimension.
Definition at line 1119 of file HalideBuffer.h.
References Halide::Runtime::Buffer< T, D >::dim(), and Halide::Runtime::Buffer< T, D >::Dimension::min().
right()
template<typename T = void, int D = 4> int Halide::Runtime::Buffer< T, D >::right () const inline
Definition at line 1123 of file HalideBuffer.h.
References Halide::Runtime::Buffer< T, D >::dim(), and Halide::Runtime::Buffer< T, D >::Dimension::max().
top()
template<typename T = void, int D = 4> int Halide::Runtime::Buffer< T, D >::top () const inline
Definition at line 1127 of file HalideBuffer.h.
References Halide::Runtime::Buffer< T, D >::dim(), and Halide::Runtime::Buffer< T, D >::Dimension::min().
bottom()
template<typename T = void, int D = 4> int Halide::Runtime::Buffer< T, D >::bottom () const inline
Definition at line 1131 of file HalideBuffer.h.
References Halide::Runtime::Buffer< T, D >::dim(), and Halide::Runtime::Buffer< T, D >::Dimension::max().
copy()
template<typename T = void, int D = 4> Buffer<not_const_T, D> Halide::Runtime::Buffer< T, D >::copy (void *(*)(size_t) allocate_fn = nullptr, void(*)(void *) deallocate_fn = nullptr) const inline
Make a new image which is a deep copy of this image.
Use crop or slice followed by copy to make a copy of only a portion of the image. The new image uses the same memory layout as the original, with holes compacted away. Note that the returned Buffer is always of a non-const type T (ie:
Buffer<const T>.copy() -> Buffer<T> rather than Buffer<const T>
which is always safe, since we are making a deep copy. (The caller can easily cast it back to Buffer<const T> if desired, which is always safe and free.)
Definition at line 1148 of file HalideBuffer.h.
References dst, and Halide::Runtime::Buffer< T, D >::make_with_shape_of().
copy_to_interleaved()
template<typename T = void, int D = 4> Buffer<not_const_T, D> Halide::Runtime::Buffer< T, D >::copy_to_interleaved (void *(*)(size_t) allocate_fn = nullptr, void(*)(void *) deallocate_fn = nullptr) const inline
Like copy(), but the copy is created in interleaved memory layout (vs.
keeping the same memory layout as the original). Requires that 'this' has exactly 3 dimensions.
Definition at line 1159 of file HalideBuffer.h.
References Halide::Runtime::Buffer< T, D >::channels(), Halide::Runtime::Buffer< T, D >::dimensions(), dst, Halide::Runtime::Buffer< T, D >::height(), Halide::Runtime::Buffer< T, D >::make_interleaved(), Halide::Runtime::Buffer< T, D >::min(), and Halide::Runtime::Buffer< T, D >::width().
copy_to_planar()
template<typename T = void, int D = 4> Buffer<not_const_T, D> Halide::Runtime::Buffer< T, D >::copy_to_planar (void *(*)(size_t) allocate_fn = nullptr, void(*)(void *) deallocate_fn = nullptr) const inline
Like copy(), but the copy is created in planar memory layout (vs.
keeping the same memory layout as the original).
Definition at line 1172 of file HalideBuffer.h.
References Halide::Runtime::Buffer< T, D >::dim(), Halide::Runtime::Buffer< T, D >::dimensions(), dst, Halide::Runtime::Buffer< T, D >::extent(), and Halide::Runtime::Buffer< T, D >::min().
alias()
template<typename T = void, int D = 4> Buffer<T, D> Halide::Runtime::Buffer< T, D >::alias () const inline
Make a copy of the Buffer which shares the underlying host and/or device allocations as the existing Buffer.
This is purely syntactic sugar for cases where you have a const reference to a Buffer but need a temporary non-const copy (e.g. to make a call into AOT-generated Halide code), and want a terse inline way to create a temporary.
void call_my_func(const Buffer<const uint8_t>& input) {
    my_func(input.alias(), output);
}
Definition at line 1198 of file HalideBuffer.h.
copy_from()
template<typename T = void, int D = 4> template<typename T2 , int D2> void Halide::Runtime::Buffer< T, D >::copy_from (const Buffer< T2, D2 > & other) inline
Fill a Buffer with the values at the same coordinates in another Buffer.
Restricts itself to coordinates contained within the intersection of the two buffers. If the two Buffers are not in the same coordinate system, you will need to translate the argument Buffer first. E.g. if you're blitting a sprite onto a framebuffer, you'll want to translate the sprite to the correct location first like so:
framebuffer.copy_from(sprite.translated({x, y}));
Definition at line 1212 of file HalideBuffer.h.
References Halide::Runtime::Buffer< T, D >::crop(), Halide::Runtime::Buffer< T, D >::device_dirty(), Halide::Runtime::Buffer< T, D >::dim(), Halide::Runtime::Buffer< T, D >::dimensions(), dst, Halide::Runtime::Buffer< T, D >::for_each_value(), Halide::Runtime::Buffer< T, D >::Dimension::max(), Halide::max(), Halide::Runtime::Buffer< T, D >::Dimension::min(), Halide::min(), Halide::Runtime::Buffer< T, D >::set_host_dirty(), and Halide::Runtime::Buffer< T, D >::type().
cropped() [1/2]
template<typename T = void, int D = 4> Buffer<T, D> Halide::Runtime::Buffer< T, D >::cropped (int d, int min, int extent) const inline
Make an image that refers to a sub-range of this image along the given dimension.
Asserts that the crop region is within the existing bounds: you cannot "crop outwards", even if you know there is valid Buffer storage (e.g. because you already cropped inwards).
Definition at line 1268 of file HalideBuffer.h.
References buf, Halide::Runtime::Buffer< T, D >::device_deallocate(), Halide::Runtime::Buffer< T, D >::extent(), and Halide::Runtime::Buffer< T, D >::min().
Referenced by Halide::Runtime::Buffer< T, D >::crop().
crop() [1/2]
template<typename T = void, int D = 4> void Halide::Runtime::Buffer< T, D >::crop (int d, int min, int extent) inline
Crop an image in-place along the given dimension.
This does not move any data around in memory - it just changes the min and extent of the given dimension.
Definition at line 1288 of file HalideBuffer.h.
References buf, Halide::Runtime::Buffer< T, D >::cropped(), Halide::Runtime::Buffer< T, D >::extent(), and Halide::Runtime::Buffer< T, D >::min().
Referenced by Halide::Runtime::Buffer< T, D >::copy_from().
cropped() [2/2]
template<typename T = void, int D = 4> Buffer<T, D> Halide::Runtime::Buffer< T, D >::cropped (const std::vector< std::pair< int, int >> & rect) const inline
Make an image that refers to a sub-rectangle of this image along the first N dimensions.
Asserts that the crop region is within the existing bounds. The cropped image may drop any device handle if the device_interface cannot accomplish the crop in-place.
Definition at line 1304 of file HalideBuffer.h.
References buf, and Halide::Runtime::Buffer< T, D >::device_deallocate().
crop() [2/2]
template<typename T = void, int D = 4> void Halide::Runtime::Buffer< T, D >::crop (const std::vector< std::pair< int, int >> & rect) inline
Crop an image in-place along the first N dimensions.
This does not move any data around in memory, nor does it free memory. It just rewrites the min/extent of each dimension to refer to a subregion of the same allocation.
Definition at line 1325 of file HalideBuffer.h.
References buf, and Halide::Runtime::Buffer< T, D >::cropped().
translated() [1/2]
template<typename T = void, int D = 4> Buffer<T, D> Halide::Runtime::Buffer< T, D >::translated (int d, int dx) const inline
Make an image which refers to the same data with using translated coordinates in the given dimension.
Positive values move the image data to the right or down relative to the coordinate system. Drops any device handle.
Definition at line 1341 of file HalideBuffer.h.
References Halide::Runtime::Buffer< T, D >::translate().
translate() [1/2]
template<typename T = void, int D = 4> void Halide::Runtime::Buffer< T, D >::translate (int d, int delta) inline
Translate an image in-place along one dimension by changing how it is indexed.
Does not move any data around in memory.
Definition at line 1349 of file HalideBuffer.h.
References buf, Halide::Runtime::Buffer< T, D >::device_deallocate(), and Halide::Runtime::Buffer< T, D >::dimensions().
Referenced by Halide::Runtime::Buffer< T, D >::embed(), Halide::Runtime::Buffer< T, D >::translate(), and Halide::Runtime::Buffer< T, D >::translated().
translated() [2/2]
template<typename T = void, int D = 4> Buffer<T, D> Halide::Runtime::Buffer< T, D >::translated (const std::vector< int > & delta) const inline
Make an image which refers to the same data translated along the first N dimensions.
Definition at line 1357 of file HalideBuffer.h.
References Halide::Runtime::Buffer< T, D >::translate().
translate() [2/2]
template<typename T = void, int D = 4> void Halide::Runtime::Buffer< T, D >::translate (const std::vector< int > & delta) inline
Translate an image along the first N dimensions by changing how it is indexed.
Does not move any data around in memory.
Definition at line 1365 of file HalideBuffer.h.
References Halide::Runtime::Buffer< T, D >::device_deallocate(), Halide::Runtime::Buffer< T, D >::dimensions(), Halide::max(), and Halide::Runtime::Buffer< T, D >::translate().
set_min() [1/2]
template<typename T = void, int D = 4> void Halide::Runtime::Buffer< T, D >::set_min (const std::vector< int > & mins) inline
Set the min coordinate of an image in the first N dimensions.
Definition at line 1377 of file HalideBuffer.h.
References buf, Halide::Runtime::Buffer< T, D >::device_deallocate(), and Halide::Runtime::Buffer< T, D >::dimensions().
Referenced by Halide::Runtime::Buffer< T, D >::set_min().
set_min() [2/2]
template<typename T = void, int D = 4> template<typename... Args> void Halide::Runtime::Buffer< T, D >::set_min (Args... args) inline
Definition at line 1386 of file HalideBuffer.h.
References Halide::Runtime::Buffer< T, D >::set_min().
contains() [1/2]
template<typename T = void, int D = 4> bool Halide::Runtime::Buffer< T, D >::contains (const std::vector< int > & coords) const inline
Test if a given coordinate is within the bounds of an image.
Definition at line 1393 of file HalideBuffer.h.
References Halide::Runtime::Buffer< T, D >::dim(), Halide::Runtime::Buffer< T, D >::dimensions(), Halide::max(), and Halide::Runtime::Buffer< T, D >::min().
Referenced by Halide::Runtime::Buffer< T, D >::contains().
contains() [2/2]
template<typename T = void, int D = 4> template<typename... Args> bool Halide::Runtime::Buffer< T, D >::contains (Args... args) const inline
Definition at line 1404 of file HalideBuffer.h.
References Halide::Runtime::Buffer< T, D >::contains().
transposed() [1/2]
template<typename T = void, int D = 4> Buffer<T, D> Halide::Runtime::Buffer< T, D >::transposed (int d1, int d2) const inline
Make a buffer which refers to the same data in the same layout using a swapped indexing order for the dimensions given.
So A = B.transposed(0, 1) means that A(i, j) == B(j, i), and more strongly that A.address_of(i, j) == B.address_of(j, i).
Definition at line 1413 of file HalideBuffer.h.
References Halide::Runtime::Buffer< T, D >::transpose().
transpose() [1/2]
template<typename T = void, int D = 4> void Halide::Runtime::Buffer< T, D >::transpose (int d1, int d2) inline
Transpose a buffer in-place by changing how it is indexed.
For example, transpose(0, 1) on a two-dimensional buffer means that the value referred to by coordinates (i, j) is now reached at the coordinates (j, i), and vice versa. This is done by reordering the per-dimension metadata rather than by moving data around in memory, so other views of the same memory will not see the data as having been transposed.
Definition at line 1426 of file HalideBuffer.h.
References buf, and Halide::Runtime::Buffer< T, D >::dimensions().
Referenced by Halide::Runtime::Buffer< T, D >::Buffer(), Halide::Runtime::Buffer< T, D >::embed(), Halide::Runtime::Buffer< T, D >::make_interleaved(), Halide::Runtime::Buffer< T, D >::transpose(), and Halide::Runtime::Buffer< T, D >::transposed().
transpose() [2/2]
template<typename T = void, int D = 4> void Halide::Runtime::Buffer< T, D >::transpose (const std::vector< int > & order) inline
A generalized transpose: instead of swapping two dimensions, pass a vector that lists each dimension index exactly once, in the desired order.
This does not move any data around in memory
it just permutes how it is indexed.
Definition at line 1436 of file HalideBuffer.h.
References Halide::Runtime::Buffer< T, D >::dimensions(), and Halide::Runtime::Buffer< T, D >::transpose().
transposed() [2/2]
template<typename T = void, int D = 4> Buffer<T, D> Halide::Runtime::Buffer< T, D >::transposed (const std::vector< int > & order) const inline
Make a buffer which refers to the same data in the same layout using a different ordering of the dimensions.
Definition at line 1454 of file HalideBuffer.h.
References Halide::Runtime::Buffer< T, D >::transpose().
sliced() [1/2]
template<typename T = void, int D = 4> Buffer<T, D> Halide::Runtime::Buffer< T, D >::sliced (int d, int pos) const inline
Make a lower-dimensional buffer that refers to one slice of this buffer.
Definition at line 1462 of file HalideBuffer.h.
References buf, and Halide::Runtime::Buffer< T, D >::device_deallocate().
Referenced by Halide::Runtime::Buffer< T, D >::slice(), and Halide::Runtime::Buffer< T, D >::sliced().
sliced() [2/2]
template<typename T = void, int D = 4> Buffer<T, D> Halide::Runtime::Buffer< T, D >::sliced (int d) const inline
Make a lower-dimensional buffer that refers to one slice of this buffer at the dimension's minimum.
Definition at line 1479 of file HalideBuffer.h.
References Halide::Runtime::Buffer< T, D >::dim(), Halide::Runtime::Buffer< T, D >::min(), and Halide::Runtime::Buffer< T, D >::sliced().
slice() [1/2]
template<typename T = void, int D = 4> void Halide::Runtime::Buffer< T, D >::slice (int d, int pos) inline
Rewrite the buffer to refer to a single lower-dimensional slice of itself along the given dimension at the given coordinate.
Does not move any data around or free the original memory, so other views of the same data are unaffected.
Definition at line 1487 of file HalideBuffer.h.
References buf, and Halide::Runtime::Buffer< T, D >::sliced().
Referenced by Halide::Runtime::Buffer< T, D >::slice().
slice() [2/2]
template<typename T = void, int D = 4> void Halide::Runtime::Buffer< T, D >::slice (int d) inline
Slice a buffer in-place at the dimension's minimum.
Definition at line 1500 of file HalideBuffer.h.
References Halide::Runtime::Buffer< T, D >::dim(), Halide::Runtime::Buffer< T, D >::min(), and Halide::Runtime::Buffer< T, D >::slice().
embedded()
template<typename T = void, int D = 4> Buffer<T, D> Halide::Runtime::Buffer< T, D >::embedded (int d, int pos = 0) const inline
Make a new buffer that views this buffer as a single slice in a higher-dimensional space.
The new dimension has extent one and the given min. This operation is the opposite of slice. As an example, the following condition is true:
im2 = im.embedded(1, 17);
&im(x, y, c) == &im2(x, 17, y, c);
Definition at line 1514 of file HalideBuffer.h.
References Halide::Runtime::Buffer< T, D >::embed().
embed()
template<typename T = void, int D = 4> void Halide::Runtime::Buffer< T, D >::embed (int d, int pos = 0) inline
Embed a buffer in-place, increasing the dimensionality.
Definition at line 1522 of file HalideBuffer.h.
References Halide::Runtime::Buffer< T, D >::add_dimension(), Halide::Runtime::Buffer< T, D >::dimensions(), Halide::Runtime::Buffer< T, D >::translate(), and Halide::Runtime::Buffer< T, D >::transpose().
Referenced by Halide::Runtime::Buffer< T, D >::embedded().
add_dimension()
template<typename T = void, int D = 4> void Halide::Runtime::Buffer< T, D >::add_dimension () inline
Add a new dimension with a min of zero and an extent of one.
The stride is the extent of the outermost dimension times its stride. The new dimension is the last dimension. This is a special case of embed.
Definition at line 1535 of file HalideBuffer.h.
References buf.
Referenced by Halide::Runtime::Buffer< T, D >::add_dimension_with_stride(), and Halide::Runtime::Buffer< T, D >::embed().
add_dimension_with_stride()
template<typename T = void, int D = 4> void Halide::Runtime::Buffer< T, D >::add_dimension_with_stride (int s) inline
Add a new dimension with a min of zero, an extent of one, and the specified stride.
The new dimension is the last dimension. This is a special case of embed.
Definition at line 1566 of file HalideBuffer.h.
References Halide::Runtime::Buffer< T, D >::add_dimension(), and buf.
set_host_dirty()
template<typename T = void, int D = 4> HALIDE_ALWAYS_INLINE void Halide::Runtime::Buffer< T, D >::set_host_dirty (bool v = true) inline
Methods for managing any GPU allocation.
Definition at line 1576 of file HalideBuffer.h.
References buf, and Halide::Runtime::Buffer< T, D >::device_dirty().
Referenced by Halide::Runtime::Buffer< T, D >::copy_from(), Halide::Runtime::Buffer< T, D >::fill(), and Halide::Runtime::Buffer< T, D >::operator()().
device_dirty()
template<typename T = void, int D = 4> HALIDE_ALWAYS_INLINE bool Halide::Runtime::Buffer< T, D >::device_dirty () const inline
Definition at line 1585 of file HalideBuffer.h.
References buf.
Referenced by Halide::Runtime::Buffer< T, D >::copy_from(), Halide::Runtime::Buffer< T, D >::copy_to_host(), Halide::Runtime::Buffer< T, D >::operator()(), and Halide::Runtime::Buffer< T, D >::set_host_dirty().
host_dirty()
template<typename T = void, int D = 4> bool Halide::Runtime::Buffer< T, D >::host_dirty () const inline
Definition at line 1589 of file HalideBuffer.h.
References buf.
Referenced by Halide::Runtime::Buffer< T, D >::copy_to_device(), and Halide::Runtime::Buffer< T, D >::set_device_dirty().
set_device_dirty()
template<typename T = void, int D = 4> void Halide::Runtime::Buffer< T, D >::set_device_dirty (bool v = true) inline
Definition at line 1593 of file HalideBuffer.h.
References buf, and Halide::Runtime::Buffer< T, D >::host_dirty().
copy_to_host()
template<typename T = void, int D = 4> int Halide::Runtime::Buffer< T, D >::copy_to_host (void * ctx = nullptr) inline
Definition at line 1598 of file HalideBuffer.h.
References buf, and Halide::Runtime::Buffer< T, D >::device_dirty().
copy_to_device()
template<typename T = void, int D = 4> int Halide::Runtime::Buffer< T, D >::copy_to_device (const struct halide_device_interface_t * device_interface, void * ctx = nullptr) inline
Definition at line 1605 of file HalideBuffer.h.
References buf, halide_device_interface_t::copy_to_device, and Halide::Runtime::Buffer< T, D >::host_dirty().
device_malloc()
template<typename T = void, int D = 4> int Halide::Runtime::Buffer< T, D >::device_malloc (const struct halide_device_interface_t * device_interface, void * ctx = nullptr) inline
Definition at line 1612 of file HalideBuffer.h.
References buf, and halide_device_interface_t::device_malloc.
device_free()
template<typename T = void, int D = 4> int Halide::Runtime::Buffer< T, D >::device_free (void * ctx = nullptr) inline
Definition at line 1616 of file HalideBuffer.h.
References Halide::Runtime::Allocated, buf, Halide::Runtime::DeviceRefCount::count, and Halide::Runtime::DeviceRefCount::ownership.
device_wrap_native()
template<typename T = void, int D = 4> int Halide::Runtime::Buffer< T, D >::device_wrap_native (const struct halide_device_interface_t * device_interface, uint64_t handle, void * ctx = nullptr) inline
Definition at line 1639 of file HalideBuffer.h.
References buf, Halide::Runtime::DeviceRefCount::ownership, halide_device_interface_t::wrap_native, and Halide::Runtime::WrappedNative.
device_detach_native()
template<typename T = void, int D = 4> int Halide::Runtime::Buffer< T, D >::device_detach_native (void * ctx = nullptr) inline
Definition at line 1647 of file HalideBuffer.h.
References buf, Halide::Runtime::DeviceRefCount::count, Halide::Runtime::DeviceRefCount::ownership, and Halide::Runtime::WrappedNative.
device_and_host_malloc()
template<typename T = void, int D = 4> int Halide::Runtime::Buffer< T, D >::device_and_host_malloc (const struct halide_device_interface_t * device_interface, void * ctx = nullptr) inline
Definition at line 1669 of file HalideBuffer.h.
References buf, and halide_device_interface_t::device_and_host_malloc.
device_and_host_free()
template<typename T = void, int D = 4> int Halide::Runtime::Buffer< T, D >::device_and_host_free (const struct halide_device_interface_t * device_interface, void * ctx = nullptr) inline
Definition at line 1673 of file HalideBuffer.h.
References Halide::Runtime::AllocatedDeviceAndHost, buf, Halide::Runtime::DeviceRefCount::count, and Halide::Runtime::DeviceRefCount::ownership.
device_sync()
template<typename T = void, int D = 4> int Halide::Runtime::Buffer< T, D >::device_sync (void * ctx = nullptr) inline
Definition at line 1696 of file HalideBuffer.h.
References buf.
has_device_allocation()
template<typename T = void, int D = 4> bool Halide::Runtime::Buffer< T, D >::has_device_allocation () const inline
Definition at line 1704 of file HalideBuffer.h.
References buf.
device_ownership()
template<typename T = void, int D = 4> BufferDeviceOwnership Halide::Runtime::Buffer< T, D >::device_ownership () const inline
Return the method by which the device field is managed.
Definition at line 1709 of file HalideBuffer.h.
References Halide::Runtime::Allocated, and Halide::Runtime::DeviceRefCount::ownership.
make_interleaved() [1/4]
template<typename T = void, int D = 4> static Buffer<void, D> Halide::Runtime::Buffer< T, D >::make_interleaved (halide_type_t t, int width, int height, int channels) inline static
If you use the (x, y, c) indexing convention, then Halide Buffers are stored planar by default.
This function constructs an interleaved RGB or RGBA image that can still be indexed using (x, y, c). Passing it to a generator requires that the generator has been compiled with support for interleaved (also known as packed or chunky) memory layouts.
Definition at line 1723 of file HalideBuffer.h.
References Halide::Runtime::Buffer< T, D >::channels(), Halide::Runtime::Buffer< T, D >::height(), Halide::Runtime::Buffer< T, D >::transpose(), and Halide::Runtime::Buffer< T, D >::width().
Referenced by Halide::Runtime::Buffer< T, D >::copy_to_interleaved(), and Halide::Runtime::Buffer< T, D >::make_interleaved().
make_interleaved() [2/4]
template<typename T = void, int D = 4> static Buffer<T, D> Halide::Runtime::Buffer< T, D >::make_interleaved (int width, int height, int channels) inline static
If you use the (x, y, c) indexing convention, then Halide Buffers are stored planar by default.
This function constructs an interleaved RGB or RGBA image that can still be indexed using (x, y, c). Passing it to a generator requires that the generator has been compiled with support for interleaved (also known as packed or chunky) memory layouts.
Definition at line 1738 of file HalideBuffer.h.
References Halide::Runtime::Buffer< T, D >::channels(), Halide::Runtime::Buffer< T, D >::height(), Halide::Runtime::Buffer< T, D >::make_interleaved(), Halide::Runtime::Buffer< T, D >::static_halide_type(), and Halide::Runtime::Buffer< T, D >::width().
make_interleaved() [3/4]
template<typename T = void, int D = 4> static Buffer<add_const_if_T_is_const<void>, D> Halide::Runtime::Buffer< T, D >::make_interleaved (halide_type_t t, T * data, int width, int height, int channels) inline static
Wrap an existing interleaved image.
Definition at line 1744 of file HalideBuffer.h.
References Halide::Runtime::Buffer< T, D >::channels(), Halide::Runtime::Buffer< T, D >::data(), Halide::Runtime::Buffer< T, D >::height(), Halide::Runtime::Buffer< T, D >::transpose(), and Halide::Runtime::Buffer< T, D >::width().
make_interleaved() [4/4]
template<typename T = void, int D = 4> static Buffer<T, D> Halide::Runtime::Buffer< T, D >::make_interleaved (T * data, int width, int height, int channels) inline static
Wrap an existing interleaved image.
Definition at line 1752 of file HalideBuffer.h.
References Halide::Runtime::Buffer< T, D >::channels(), Halide::Runtime::Buffer< T, D >::data(), Halide::Runtime::Buffer< T, D >::height(), Halide::Runtime::Buffer< T, D >::make_interleaved(), Halide::Runtime::Buffer< T, D >::static_halide_type(), and Halide::Runtime::Buffer< T, D >::width().
make_scalar() [1/3]
template<typename T = void, int D = 4> static Buffer<add_const_if_T_is_const<void>, D> Halide::Runtime::Buffer< T, D >::make_scalar (halide_type_t t) inline static
Make a zero-dimensional Buffer.
Definition at line 1757 of file HalideBuffer.h.
References buf.
make_scalar() [2/3]
template<typename T = void, int D = 4> static Buffer<T, D> Halide::Runtime::Buffer< T, D >::make_scalar () inline static
Make a zero-dimensional Buffer.
Definition at line 1764 of file HalideBuffer.h.
References buf.
make_scalar() [3/3]
template<typename T = void, int D = 4> static Buffer<T, D> Halide::Runtime::Buffer< T, D >::make_scalar (T * data) inline static
Make a zero-dimensional Buffer that points to non-owned, existing data.
Definition at line 1771 of file HalideBuffer.h.
References buf, and Halide::Runtime::Buffer< T, D >::data().
make_with_shape_of()
template<typename T = void, int D = 4> template<typename T2 , int D2> static Buffer<T, D> Halide::Runtime::Buffer< T, D >::make_with_shape_of (Buffer< T2, D2 > src, void *(*)(size_t) allocate_fn = nullptr, void(*)(void *) deallocate_fn = nullptr) inline static
Make a buffer with the same shape and memory nesting order as another buffer.
It may have a different type.
Definition at line 1780 of file HalideBuffer.h.
References halide_buffer_t::dim, Halide::Runtime::Buffer< T, D >::dimensions(), and Halide::Runtime::Buffer< T, D >::type().
Referenced by Halide::Runtime::Buffer< T, D >::copy().
data()
template<typename T = void, int D = 4> T* Halide::Runtime::Buffer< T, D >::data () const inline
Get a pointer to the address of the min coordinate.
Definition at line 1874 of file HalideBuffer.h.
References halide_buffer_t::host.
Referenced by Halide::Runtime::Buffer< T, D >::Buffer(), Halide::Runtime::Buffer< T, D >::make_interleaved(), Halide::Runtime::Buffer< T, D >::make_scalar(), Halide::Runtime::Buffer< T, D >::msan_check_mem_is_initialized(), and Halide::Runtime::Buffer< T, D >::operator()().
operator()() [1/6]
template<typename T = void, int D = 4> template<typename... Args, typename = typename std::enable_if<AllInts<Args...>::value>::type> HALIDE_ALWAYS_INLINE const not_void_T& Halide::Runtime::Buffer< T, D >::operator() (int first, Args... rest) const inline
Access elements.
Use im(...) to get a reference to an element, and use &im(...) to get the address of an element. If you pass fewer arguments than the buffer has dimensions, the rest are treated as their min coordinate. The non-const versions set the host_dirty flag to true.
Definition at line 1887 of file HalideBuffer.h.
References Halide::Runtime::Buffer< T, D >::device_dirty().
operator()() [2/6]
template<typename T = void, int D = 4> HALIDE_ALWAYS_INLINE const not_void_T& Halide::Runtime::Buffer< T, D >::operator() () const inline
Definition at line 1896 of file HalideBuffer.h.
References Halide::Runtime::Buffer< T, D >::data(), and Halide::Runtime::Buffer< T, D >::device_dirty().
operator()() [3/6]
template<typename T = void, int D = 4> HALIDE_ALWAYS_INLINE const not_void_T& Halide::Runtime::Buffer< T, D >::operator() (const int * pos) const inline
Definition at line 1905 of file HalideBuffer.h.
References Halide::Runtime::Buffer< T, D >::device_dirty().
operator()() [4/6]
template<typename T = void, int D = 4> template<typename... Args, typename = typename std::enable_if<AllInts<Args...>::value>::type> HALIDE_ALWAYS_INLINE not_void_T& Halide::Runtime::Buffer< T, D >::operator() (int first, Args... rest) inline
Definition at line 1916 of file HalideBuffer.h.
References Halide::Runtime::Buffer< T, D >::set_host_dirty().
operator()() [5/6]
template<typename T = void, int D = 4> HALIDE_ALWAYS_INLINE not_void_T& Halide::Runtime::Buffer< T, D >::operator() () inline
Definition at line 1925 of file HalideBuffer.h.
References Halide::Runtime::Buffer< T, D >::data(), and Halide::Runtime::Buffer< T, D >::set_host_dirty().
operator()() [6/6]
template<typename T = void, int D = 4> HALIDE_ALWAYS_INLINE not_void_T& Halide::Runtime::Buffer< T, D >::operator() (const int * pos) inline
Definition at line 1934 of file HalideBuffer.h.
References Halide::Runtime::Buffer< T, D >::set_host_dirty().
all_equal()
template<typename T = void, int D = 4> bool Halide::Runtime::Buffer< T, D >::all_equal (not_void_T val) const inline
Tests that all values in this buffer are equal to val.
Definition at line 1943 of file HalideBuffer.h.
fill() [1/2]
template<typename T = void, int D = 4> Buffer<T, D>& Halide::Runtime::Buffer< T, D >::fill (not_void_T val) inline
Definition at line 1949 of file HalideBuffer.h.
References Halide::Runtime::Buffer< T, D >::for_each_value(), and Halide::Runtime::Buffer< T, D >::set_host_dirty().
for_each_value() [1/2]
template<typename T = void, int D = 4> template<typename Fn , typename... Args, int N = sizeof...(Args) + 1> HALIDE_ALWAYS_INLINE const Buffer<T, D>& Halide::Runtime::Buffer< T, D >::for_each_value (Fn && f, Args &&... other_buffers) const inline
Call a function on every value in the buffer, and the corresponding values in some number of other buffers of the same size.
The function should take a reference, const reference, or value of the correct type for each buffer. This effectively lifts a function of scalars to an element-wise function of buffers. This produces code that the compiler can autovectorize. This is slightly cheaper than for_each_element, because it does not need to track the coordinates.
Note that constness of Buffers is preserved: a const Buffer<T> (for either 'this' or the other-buffers arguments) will allow mutation of the buffer contents, while a Buffer<const T> will not. Attempting to specify a mutable reference for the lambda argument of a Buffer<const T> will result in a compilation error.
Definition at line 2110 of file HalideBuffer.h.
Referenced by Halide::Runtime::Buffer< T, D >::copy_from(), Halide::Runtime::Buffer< T, D >::fill(), and Halide::Runtime::Buffer< T, D >::msan_check_mem_is_initialized().
for_each_value() [2/2]
template<typename T = void, int D = 4> template<typename Fn , typename... Args, int N = sizeof...(Args) + 1> HALIDE_ALWAYS_INLINE Buffer<T, D>& Halide::Runtime::Buffer< T, D >::for_each_value (Fn && f, Args &&... other_buffers) inline
Definition at line 2118 of file HalideBuffer.h.
for_each_element() [1/2]
template<typename T = void, int D = 4> template<typename Fn > HALIDE_ALWAYS_INLINE const Buffer<T, D>& Halide::Runtime::Buffer< T, D >::for_each_element (Fn && f) const inline
Call a function at each site in a buffer.
This is likely to be much slower than using Halide code to populate a buffer, but is convenient for tests. If the function has more arguments than the buffer has dimensions, the remaining arguments will be zero. If it has fewer arguments than the buffer has dimensions then the last few dimensions of the buffer are not iterated over. For example, the following code exploits this to set a floating point RGB image to red:
Buffer<float, 3> im(100, 100, 3);
im.for_each_element([&](int x, int y) {
    im(x, y, 0) = 1.0f;
    im(x, y, 1) = 0.0f;
    im(x, y, 2) = 0.0f:
});
The compiled code is equivalent to writing the a nested for loop, and compilers are capable of optimizing it in the same way.
If the callable can be called with an int * as the sole argument, that version is called instead. Each location in the buffer is passed to it in a coordinate array. This version is higher-overhead than the variadic version, but is useful for writing generic code that accepts buffers of arbitrary dimensionality. For example, the following sets the value at all sites in an arbitrary-dimensional buffer to their first coordinate:
im.for_each_element([&](const int *pos) {im(pos) = pos[0];});
It is also possible to use for_each_element to iterate over entire rows or columns by cropping the buffer to a single column or row respectively and iterating over elements of the result. For example, to set the diagonal of the image to 1 by iterating over the columns:
Buffer<float, 3> im(100, 100, 3);
    im.sliced(1, 0).for_each_element([&](int x, int c) {
    im(x, x, c) = 1.0f;
});
Or, assuming the memory layout is known to be dense per row, one can memset each row of an image like so:
Buffer<float, 3> im(100, 100, 3);
im.sliced(0, 0).for_each_element([&](int y, int c) {
    memset(&im(0, y, c), 0, sizeof(float) * im.width());
});
Definition at line 2309 of file HalideBuffer.h.
for_each_element() [2/2]
template<typename T = void, int D = 4> template<typename Fn > HALIDE_ALWAYS_INLINE Buffer<T, D>& Halide::Runtime::Buffer< T, D >::for_each_element (Fn && f) inline
Definition at line 2317 of file HalideBuffer.h.
fill() [2/2]
template<typename T = void, int D = 4> template<typename Fn , typename = typename std::enable_if<!std::is_arithmetic<typename std::decay<Fn>::type>::value>::type> Buffer<T, D>& Halide::Runtime::Buffer< T, D >::fill (Fn && f) inline
Fill a buffer by evaluating a callable at every site.
The callable should look much like a callable passed to for_each_element, but it should return the value that should be stored to the coordinate corresponding to the arguments.
Definition at line 2347 of file HalideBuffer.h.
is_bounds_query()
template<typename T = void, int D = 4> bool Halide::Runtime::Buffer< T, D >::is_bounds_query () const inline
Check if an input buffer passed extern stage is a querying bounds.
Compared to doing the host pointer check directly, this both adds clarity to code and will facilitate moving to another representation for bounds query arguments.
Definition at line 2357 of file HalideBuffer.h.
References buf.
msan_check_mem_is_initialized()
template<typename T = void, int D = 4> void Halide::Runtime::Buffer< T, D >::msan_check_mem_is_initialized (bool entire = false) const inline
Convenient check to verify that all of the interesting bytes in the Buffer are initialized under MSAN.
Note that by default, we use for_each_value() here so that we skip any unused padding that isn't part of the Buffer; this isn't efficient, but in MSAN mode, it doesn't matter. (Pass true for the flag to force check the entire Buffer storage.)
Definition at line 2366 of file HalideBuffer.h.
References Halide::Runtime::Buffer< T, D >::data(), Halide::Runtime::Buffer< T, D >::for_each_value(), and Halide::Runtime::Buffer< T, D >::size_in_bytes().
Member Data Documentation
has_static_halide_type
template<typename T = void, int D = 4> constexpr bool Halide::Runtime::Buffer< T, D >::has_static_halide_type = !T_is_void static constexpr
True if the Halide type is not void (or const void).
Definition at line 170 of file HalideBuffer.h.
The documentation for this class was generated from the following file:
/Users/halidenightly/build_bot_new/worker/halide-main-llvm13-x86-64-osx-cmake/halide-source/src/runtime/HalideBuffer.h