Halide: Halide::Runtime::Buffer< T, D >::Dimension Class Reference
Halide::Runtime::Buffer< T, D >::Dimension Class Reference
Read-only access to the shape.
#include <HalideBuffer.h>
Classes
struct iterator
An iterator class, so that you can iterate over coordinates in a dimensions using a range-based for loop.
Public Member Functions
HALIDE_ALWAYS_INLINE int min () const
The lowest coordinate in this dimension.
HALIDE_ALWAYS_INLINE int stride () const
The number of elements in memory you have to step over to increment this coordinate by one.
HALIDE_ALWAYS_INLINE int extent () const
The extent of the image along this dimension.
HALIDE_ALWAYS_INLINE int max () const
The highest coordinate in this dimension.
HALIDE_ALWAYS_INLINE iterator begin () const
An iterator that points to the min coordinate.
HALIDE_ALWAYS_INLINE iterator end () const
An iterator that points to one past the max coordinate.
Dimension (const halide_dimension_t &dim)
Detailed Description
template<typename T = void, int D = 4>
class Halide::Runtime::Buffer< T, D >::Dimension
Read-only access to the shape.
Definition at line 442 of file HalideBuffer.h.
Constructor & Destructor Documentation
Dimension()
template<typename T = void, int D = 4> Halide::Runtime::Buffer< T, D >::Dimension::Dimension (const halide_dimension_t & dim) inline
Definition at line 493 of file HalideBuffer.h.
Member Function Documentation
min()
template<typename T = void, int D = 4> HALIDE_ALWAYS_INLINE int Halide::Runtime::Buffer< T, D >::Dimension::min () const inline
The lowest coordinate in this dimension.
Definition at line 447 of file HalideBuffer.h.
References halide_dimension_t::min.
Referenced by Halide::Runtime::Buffer< T, D >::Dimension::begin(), Halide::Runtime::Buffer< T, D >::copy_from(), Halide::Runtime::Buffer< T, D >::Dimension::end(), Halide::Runtime::Buffer< T, D >::left(), Halide::Runtime::Buffer< T, D >::Dimension::max(), Halide::Runtime::Buffer< T, D >::min(), and Halide::Runtime::Buffer< T, D >::top().
stride()
template<typename T = void, int D = 4> HALIDE_ALWAYS_INLINE int Halide::Runtime::Buffer< T, D >::Dimension::stride () const inline
The number of elements in memory you have to step over to increment this coordinate by one.
Definition at line 453 of file HalideBuffer.h.
References halide_dimension_t::stride.
Referenced by Halide::Runtime::Buffer< T, D >::stride().
extent()
template<typename T = void, int D = 4> HALIDE_ALWAYS_INLINE int Halide::Runtime::Buffer< T, D >::Dimension::extent () const inline
The extent of the image along this dimension.
Definition at line 458 of file HalideBuffer.h.
References halide_dimension_t::extent.
Referenced by Halide::Runtime::Buffer< T, D >::channels(), Halide::Runtime::Buffer< T, D >::check_overflow(), Halide::Runtime::Buffer< T, D >::Dimension::end(), Halide::Runtime::Buffer< T, D >::extent(), Halide::Runtime::Buffer< T, D >::height(), Halide::Runtime::Buffer< T, D >::Dimension::max(), Halide::Runtime::Buffer< T, D >::number_of_elements(), and Halide::Runtime::Buffer< T, D >::width().
max()
template<typename T = void, int D = 4> HALIDE_ALWAYS_INLINE int Halide::Runtime::Buffer< T, D >::Dimension::max () const inline
The highest coordinate in this dimension.
Definition at line 463 of file HalideBuffer.h.
References Halide::Runtime::Buffer< T, D >::Dimension::extent(), and Halide::Runtime::Buffer< T, D >::Dimension::min().
Referenced by Halide::Runtime::Buffer< T, D >::bottom(), Halide::Runtime::Buffer< T, D >::copy_from(), and Halide::Runtime::Buffer< T, D >::right().
begin()
template<typename T = void, int D = 4> HALIDE_ALWAYS_INLINE iterator Halide::Runtime::Buffer< T, D >::Dimension::begin () const inline
An iterator that points to the min coordinate.
Definition at line 484 of file HalideBuffer.h.
References Halide::Runtime::Buffer< T, D >::Dimension::min().
end()
template<typename T = void, int D = 4> HALIDE_ALWAYS_INLINE iterator Halide::Runtime::Buffer< T, D >::Dimension::end () const inline
An iterator that points to one past the max coordinate.
Definition at line 489 of file HalideBuffer.h.
References Halide::Runtime::Buffer< T, D >::Dimension::extent(), and Halide::Runtime::Buffer< T, D >::Dimension::min().
The documentation for this class was generated from the following file:
/Users/halidenightly/build_bot_new/worker/halide-main-llvm13-x86-64-osx-cmake/halide-source/src/runtime/HalideBuffer.h