Halide: Halide::Runtime::Internal::Synchronization::fast_cond Class Reference
Halide::Runtime::Internal::Synchronization::fast_cond Class Reference
#include <synchronization_common.h>
Public Member Functions
ALWAYS_INLINE fast_cond ()=default
ALWAYS_INLINE void signal ()
ALWAYS_INLINE void broadcast ()
ALWAYS_INLINE void wait (fast_mutex *mutex)
Detailed Description
Definition at line 1072 of file synchronization_common.h.
Constructor & Destructor Documentation
fast_cond()
ALWAYS_INLINE Halide::Runtime::Internal::Synchronization::fast_cond::fast_cond () default
Member Function Documentation
signal()
ALWAYS_INLINE void Halide::Runtime::Internal::Synchronization::fast_cond::signal () inline
Definition at line 1078 of file synchronization_common.h.
References Halide::Runtime::Internal::Synchronization::unpark_one().
Referenced by halide_cond_signal().
broadcast()
ALWAYS_INLINE void Halide::Runtime::Internal::Synchronization::fast_cond::broadcast () inline
Definition at line 1092 of file synchronization_common.h.
References Halide::Runtime::Internal::Synchronization::unpark_requeue().
Referenced by halide_cond_broadcast().
wait()
ALWAYS_INLINE void Halide::Runtime::Internal::Synchronization::fast_cond::wait (fast_mutex * mutex) inline
Definition at line 1105 of file synchronization_common.h.
References halide_assert, Halide::Runtime::Internal::Synchronization::fast_mutex::lock(), and Halide::Runtime::Internal::Synchronization::park().
Referenced by halide_cond_wait().
The documentation for this class was generated from the following file:
/Users/halidenightly/build_bot_new/worker/halide-main-llvm13-x86-64-osx-cmake/halide-source/src/runtime/synchronization_common.h