Halide: Halide::ParamMap Class Reference
Halide::ParamMap Class Reference
#include <ParamMap.h>
Classes
struct ParamMapping
Public Member Functions
ParamMap ()=default
ParamMap (const std::initializer_list< ParamMapping > &init)
template<typename T >
void set (const Param< T > &p, T val)
void set (const ImageParam &p, const Buffer<> &buf)
size_t size () const
const Internal::Parameter & map (const Internal::Parameter &p, Buffer<> *&buf_out_param) const
If there is an entry in the ParamMap for this Parameter, return it.
Internal::Parameter & map (Internal::Parameter &p, Buffer<> *&buf_out_param) const
Static Public Member Functions
static const ParamMap & empty_map ()
A const ref to an empty ParamMap.
Detailed Description
Definition at line 17 of file ParamMap.h.
Constructor & Destructor Documentation
ParamMap() [1/2]
Halide::ParamMap::ParamMap () default
ParamMap() [2/2]
Halide::ParamMap::ParamMap (const std::initializer_list< ParamMapping > & init)
Member Function Documentation
set() [1/2]
template<typename T > void Halide::ParamMap::set (const Param< T > & p, T val) inline
Definition at line 76 of file ParamMap.h.
References Halide::Param< T >::name(), Halide::Param< T >::parameter(), Halide::Internal::Parameter::set_scalar(), and Halide::Param< T >::type().
set() [2/2]
void Halide::ParamMap::set (const ImageParam & p, const Buffer<> & buf) inline
Definition at line 85 of file ParamMap.h.
References buf.
size()
size_t Halide::ParamMap::size () const inline
Definition at line 89 of file ParamMap.h.
map() [1/2]
const Internal::Parameter& Halide::ParamMap::map (const Internal::Parameter & p, Buffer<> *& buf_out_param) const
If there is an entry in the ParamMap for this Parameter, return it.
Otherwise return the parameter itself.
map() [2/2]
Internal::Parameter& Halide::ParamMap::map (Internal::Parameter & p, Buffer<> *& buf_out_param) const
empty_map()
static const ParamMap& Halide::ParamMap::empty_map () inline static
A const ref to an empty ParamMap.
Useful for default function arguments, which would otherwise require a copy constructor (with llvm in c++98 mode)
Definition at line 104 of file ParamMap.h.
The documentation for this class was generated from the following file:
/Users/halidenightly/build_bot_new/worker/halide-main-llvm13-x86-64-osx-cmake/halide-source/src/ParamMap.h