Halide: /Users/halidenightly/build_bot_new/worker/halide-main-llvm13-x86-64-osx-cmake/halide-source/src/autoschedulers/adams2019/cost_model_schedule.h File Reference
cost_model_schedule.h File Reference
#include "Halide.h"
Functions
void do_cost_model_schedule (Halide::Pipeline pipeline)
Function Documentation
do_cost_model_schedule()
void do_cost_model_schedule (Halide::Pipeline pipeline) inline
Definition at line 5 of file cost_model_schedule.h.
References Halide::Func::compute_at(), Halide::Func::compute_root(), Halide::Internal::StageSchedule::dims(), Halide::Func::fuse(), Halide::Pipeline::get_func(), Halide::Stage::get_schedule(), Halide::Func::get_schedule(), Halide::GuardWithIf, Halide::Stage::parallel(), Halide::Func::parallel(), Halide::Stage::reorder(), Halide::Func::reorder(), Halide::Func::split(), Halide::Stack, Halide::Func::store_at(), Halide::Func::store_in(), Halide::sum(), Halide::Func::update(), and Halide::Func::vectorize().