Halide: Halide::Internal::IRMatcher::Intrin< Args > Struct Template Reference
Halide::Internal::IRMatcher::Intrin< Args > Struct Template Reference
#include <IRMatch.h>
Classes
struct pattern_tag
Public Member Functions
template<int i, uint32_t bound, typename = typename std::enable_if<(i < sizeof...(Args))>::type>
HALIDE_ALWAYS_INLINE bool match_args (int, const Call &c, MatcherState &state) const noexcept
template<int i, uint32_t binds>
HALIDE_ALWAYS_INLINE bool match_args (double, const Call &c, MatcherState &state) const noexcept
template<uint32_t bound>
HALIDE_ALWAYS_INLINE bool match (const BaseExprNode &e, MatcherState &state) const noexcept
template<int i, typename = typename std::enable_if<(i < sizeof...(Args))>::type>
HALIDE_ALWAYS_INLINE void print_args (int, std::ostream &s) const
template<int i>
HALIDE_ALWAYS_INLINE void print_args (double, std::ostream &s) const
HALIDE_ALWAYS_INLINE void print_args (std::ostream &s) const
HALIDE_ALWAYS_INLINE Expr make (MatcherState &state, halide_type_t type_hint) const
HALIDE_ALWAYS_INLINE Intrin (Call::IntrinsicOp intrin, Args... args) noexcept
Public Attributes
Call::IntrinsicOp intrin
std::tuple< Args... > args
Static Public Attributes
static constexpr uint32_t binds = bitwise_or_reduce((bindings<Args>::mask)...)
constexpr static IRNodeType min_node_type = IRNodeType::Call
constexpr static IRNodeType max_node_type = IRNodeType::Call
constexpr static bool canonical = and_reduce((Args::canonical)...)
constexpr static bool foldable = false
Detailed Description
template<typename... Args>
struct Halide::Internal::IRMatcher::Intrin< Args >
Definition at line 1376 of file IRMatch.h.
Constructor & Destructor Documentation
Intrin()
template<typename... Args> HALIDE_ALWAYS_INLINE Halide::Internal::IRMatcher::Intrin< Args >::Intrin (Call::IntrinsicOp intrin, Args... args) inline noexcept
Definition at line 1478 of file IRMatch.h.
Member Function Documentation
match_args() [1/2]
template<typename... Args> template<int i, uint32_t bound, typename = typename std::enable_if<(i < sizeof...(Args))>::type> HALIDE_ALWAYS_INLINE bool Halide::Internal::IRMatcher::Intrin< Args >::match_args (int , const Call & c, MatcherState & state) const inline noexcept
Definition at line 1390 of file IRMatch.h.
References Halide::Internal::IRMatcher::Intrin< Args >::args.
match_args() [2/2]
template<typename... Args> template<int i, uint32_t binds> HALIDE_ALWAYS_INLINE bool Halide::Internal::IRMatcher::Intrin< Args >::match_args (double , const Call & c, MatcherState & state) const inline noexcept
Definition at line 1397 of file IRMatch.h.
match()
template<typename... Args> template<uint32_t bound> HALIDE_ALWAYS_INLINE bool Halide::Internal::IRMatcher::Intrin< Args >::match (const BaseExprNode & e, MatcherState & state) const inline noexcept
Definition at line 1402 of file IRMatch.h.
References Halide::Internal::Call, Halide::Internal::IRMatcher::Intrin< Args >::intrin, and Halide::Internal::Call::is_intrinsic().
print_args() [1/3]
template<typename... Args> template<int i, typename = typename std::enable_if<(i < sizeof...(Args))>::type> HALIDE_ALWAYS_INLINE void Halide::Internal::IRMatcher::Intrin< Args >::print_args (int , std::ostream & s) const inline
Definition at line 1412 of file IRMatch.h.
References Halide::Internal::IRMatcher::Intrin< Args >::args.
Referenced by Halide::Internal::IRMatcher::operator<<().
print_args() [2/3]
template<typename... Args> template<int i> HALIDE_ALWAYS_INLINE void Halide::Internal::IRMatcher::Intrin< Args >::print_args (double , std::ostream & s) const inline
Definition at line 1421 of file IRMatch.h.
print_args() [3/3]
template<typename... Args> HALIDE_ALWAYS_INLINE void Halide::Internal::IRMatcher::Intrin< Args >::print_args (std::ostream & s) const inline
Definition at line 1425 of file IRMatch.h.
make()
template<typename... Args> HALIDE_ALWAYS_INLINE Expr Halide::Internal::IRMatcher::Intrin< Args >::make (MatcherState & state, halide_type_t type_hint) const inline
Definition at line 1430 of file IRMatch.h.
References Halide::Internal::Call::abs, Halide::abs(), Halide::Internal::Call::absd, Halide::absd(), Halide::Internal::IRMatcher::Intrin< Args >::args, Halide::Internal::IRMatcher::const_min(), Halide::Internal::Call::halving_add, Halide::Internal::IRMatcher::halving_add(), Halide::Internal::Call::halving_sub, Halide::Internal::IRMatcher::halving_sub(), internal_error, Halide::Internal::IRMatcher::Intrin< Args >::intrin, Halide::Internal::Call::likely, Halide::likely(), Halide::Internal::Call::likely_if_innermost, Halide::likely_if_innermost(), Halide::Internal::Call::rounding_halving_add, Halide::Internal::IRMatcher::rounding_halving_add(), Halide::Internal::Call::rounding_halving_sub, Halide::Internal::IRMatcher::rounding_halving_sub(), Halide::Internal::Call::rounding_shift_left, Halide::Internal::IRMatcher::rounding_shift_left(), Halide::Internal::Call::rounding_shift_right, Halide::Internal::IRMatcher::rounding_shift_right(), Halide::Internal::Call::saturating_add, Halide::Internal::IRMatcher::saturating_add(), Halide::Internal::Call::saturating_sub, Halide::Internal::IRMatcher::saturating_sub(), Halide::Internal::Call::shift_left, Halide::Internal::Call::shift_right, Halide::Internal::Call::widening_add, Halide::Internal::IRMatcher::widening_add(), Halide::Internal::Call::widening_mul, Halide::Internal::IRMatcher::widening_mul(), Halide::Internal::Call::widening_sub, and Halide::Internal::IRMatcher::widening_sub().
Member Data Documentation
intrin
template<typename... Args> Call::IntrinsicOp Halide::Internal::IRMatcher::Intrin< Args >::intrin
Definition at line 1378 of file IRMatch.h.
Referenced by Halide::Internal::IRMatcher::Intrin< Args >::make(), Halide::Internal::IRMatcher::Intrin< Args >::match(), and Halide::Internal::IRMatcher::operator<<().
args
template<typename... Args> std::tuple<Args...> Halide::Internal::IRMatcher::Intrin< Args >::args
Definition at line 1379 of file IRMatch.h.
Referenced by Halide::Internal::IRMatcher::Intrin< Args >::make(), Halide::Internal::IRMatcher::Intrin< Args >::match_args(), and Halide::Internal::IRMatcher::Intrin< Args >::print_args().
binds
template<typename... Args> constexpr uint32_t Halide::Internal::IRMatcher::Intrin< Args >::binds = bitwise_or_reduce((bindings<Args>::mask)...) static constexpr
Definition at line 1381 of file IRMatch.h.
min_node_type
template<typename... Args> constexpr static IRNodeType Halide::Internal::IRMatcher::Intrin< Args >::min_node_type = IRNodeType::Call static constexpr
Definition at line 1383 of file IRMatch.h.
max_node_type
template<typename... Args> constexpr static IRNodeType Halide::Internal::IRMatcher::Intrin< Args >::max_node_type = IRNodeType::Call static constexpr
Definition at line 1384 of file IRMatch.h.
canonical
template<typename... Args> constexpr static bool Halide::Internal::IRMatcher::Intrin< Args >::canonical = and_reduce((Args::canonical)...) static constexpr
Definition at line 1385 of file IRMatch.h.
foldable
template<typename... Args> constexpr static bool Halide::Internal::IRMatcher::Intrin< Args >::foldable = false static constexpr
Definition at line 1475 of file IRMatch.h.
The documentation for this struct was generated from the following file:
/Users/halidenightly/build_bot_new/worker/halide-main-llvm13-x86-64-osx-cmake/halide-source/src/IRMatch.h