Halide: Halide::Internal::IRMatcher::Wild< i > Struct Template Reference
Halide::Internal::IRMatcher::Wild< i > Struct Template Reference
#include <IRMatch.h>
Classes
struct pattern_tag
Public Member Functions
template<uint32_t bound>
HALIDE_ALWAYS_INLINE bool match (const BaseExprNode &e, MatcherState &state) const noexcept
HALIDE_ALWAYS_INLINE Expr make (MatcherState &state, halide_type_t type_hint) const
HALIDE_ALWAYS_INLINE void make_folded_const (halide_scalar_value_t &val, halide_type_t &ty, MatcherState &state) const noexcept
Static Public Attributes
constexpr static uint32_t binds = 1 << (i + 16)
constexpr static IRNodeType min_node_type = IRNodeType::IntImm
constexpr static IRNodeType max_node_type = StrongestExprNodeType
constexpr static bool canonical = true
constexpr static bool foldable = true
Detailed Description
template<int i>
struct Halide::Internal::IRMatcher::Wild< i >
Definition at line 462 of file IRMatch.h.
Member Function Documentation
match()
template<int i> template<uint32_t bound> HALIDE_ALWAYS_INLINE bool Halide::Internal::IRMatcher::Wild< i >::match (const BaseExprNode & e, MatcherState & state) const inline noexcept
Definition at line 472 of file IRMatch.h.
References Halide::Internal::IRMatcher::Wild< i >::binds, and Halide::Internal::IRMatcher::equal().
make()
template<int i> HALIDE_ALWAYS_INLINE Expr Halide::Internal::IRMatcher::Wild< i >::make (MatcherState & state, halide_type_t type_hint) const inline
Definition at line 481 of file IRMatch.h.
References Halide::Internal::IRMatcher::MatcherState::get_binding().
make_folded_const()
template<int i> HALIDE_ALWAYS_INLINE void Halide::Internal::IRMatcher::Wild< i >::make_folded_const (halide_scalar_value_t & val, halide_type_t & ty, MatcherState & state) const inline noexcept
Definition at line 487 of file IRMatch.h.
References Halide::Internal::FloatImm, Halide::Internal::IntImm, and Halide::Internal::UIntImm.
Member Data Documentation
binds
template<int i> constexpr static uint32_t Halide::Internal::IRMatcher::Wild< i >::binds = 1 << (i + 16) static constexpr
Definition at line 465 of file IRMatch.h.
Referenced by Halide::Internal::IRMatcher::Wild< i >::match().
min_node_type
template<int i> constexpr static IRNodeType Halide::Internal::IRMatcher::Wild< i >::min_node_type = IRNodeType::IntImm static constexpr
Definition at line 467 of file IRMatch.h.
max_node_type
template<int i> constexpr static IRNodeType Halide::Internal::IRMatcher::Wild< i >::max_node_type = StrongestExprNodeType static constexpr
Definition at line 468 of file IRMatch.h.
canonical
template<int i> constexpr static bool Halide::Internal::IRMatcher::Wild< i >::canonical = true static constexpr
Definition at line 469 of file IRMatch.h.
foldable
template<int i> constexpr static bool Halide::Internal::IRMatcher::Wild< i >::foldable = true static constexpr
Definition at line 485 of file IRMatch.h.
The documentation for this struct was generated from the following file:
/Users/halidenightly/build_bot_new/worker/halide-main-llvm13-x86-64-osx-cmake/halide-source/src/IRMatch.h