Halide: Halide::Internal::IRMatcher::IsInt< A > Struct Template Reference
Halide::Internal::IRMatcher::IsInt< A > Struct Template Reference
#include <IRMatch.h>
Classes
struct pattern_tag
Public Member Functions
HALIDE_ALWAYS_INLINE void make_folded_const (halide_scalar_value_t &val, halide_type_t &ty, MatcherState &state) const
Public Attributes
A a
int bits
Static Public Attributes
constexpr static uint32_t binds = bindings<A>::mask
constexpr static IRNodeType min_node_type = IRNodeType::UIntImm
constexpr static IRNodeType max_node_type = IRNodeType::UIntImm
constexpr static bool canonical = true
constexpr static bool foldable = true
Detailed Description
template<typename A>
struct Halide::Internal::IRMatcher::IsInt< A >
Definition at line 2262 of file IRMatch.h.
Member Function Documentation
make_folded_const()
template<typename A > HALIDE_ALWAYS_INLINE void Halide::Internal::IRMatcher::IsInt< A >::make_folded_const (halide_scalar_value_t & val, halide_type_t & ty, MatcherState & state) const inline
Definition at line 2277 of file IRMatch.h.
References Halide::Internal::IRMatcher::IsInt< A >::a, Halide::Internal::IRMatcher::IsInt< A >::bits, halide_type_t::bits, Halide::Type::bits(), halide_type_t::code, halide_type_uint, Halide::Type::is_int(), halide_type_t::lanes, Halide::Type::lanes(), halide_scalar_value_t::u, and halide_scalar_value_t::u64.
Member Data Documentation
a
template<typename A > A Halide::Internal::IRMatcher::IsInt< A >::a
Definition at line 2264 of file IRMatch.h.
Referenced by Halide::Internal::IRMatcher::IsInt< A >::make_folded_const(), and Halide::Internal::IRMatcher::operator<<().
bits
template<typename A > int Halide::Internal::IRMatcher::IsInt< A >::bits
Definition at line 2265 of file IRMatch.h.
Referenced by Halide::Internal::IRMatcher::IsInt< A >::make_folded_const(), and Halide::Internal::IRMatcher::operator<<().
binds
template<typename A > constexpr static uint32_t Halide::Internal::IRMatcher::IsInt< A >::binds = bindings<A>::mask static constexpr
Definition at line 2267 of file IRMatch.h.
min_node_type
template<typename A > constexpr static IRNodeType Halide::Internal::IRMatcher::IsInt< A >::min_node_type = IRNodeType::UIntImm static constexpr
Definition at line 2270 of file IRMatch.h.
max_node_type
template<typename A > constexpr static IRNodeType Halide::Internal::IRMatcher::IsInt< A >::max_node_type = IRNodeType::UIntImm static constexpr
Definition at line 2271 of file IRMatch.h.
canonical
template<typename A > constexpr static bool Halide::Internal::IRMatcher::IsInt< A >::canonical = true static constexpr
Definition at line 2272 of file IRMatch.h.
foldable
template<typename A > constexpr static bool Halide::Internal::IRMatcher::IsInt< A >::foldable = true static constexpr
Definition at line 2274 of file IRMatch.h.
The documentation for this struct was generated from the following file:
/Users/halidenightly/build_bot_new/worker/halide-main-llvm13-x86-64-osx-cmake/halide-source/src/IRMatch.h