Halide: Halide::Internal::IRMatcher::CastOp< A > Struct Template Reference
Halide::Internal::IRMatcher::CastOp< A > Struct Template Reference
#include <IRMatch.h>
Classes
struct pattern_tag
Public Member Functions
template<uint32_t bound>
HALIDE_ALWAYS_INLINE bool match (const BaseExprNode &e, MatcherState &state) const noexcept
template<uint32_t bound, typename A2 >
HALIDE_ALWAYS_INLINE bool match (const CastOp< A2 > &op, MatcherState &state) const noexcept
HALIDE_ALWAYS_INLINE Expr make (MatcherState &state, halide_type_t type_hint) const
Public Attributes
Type t
A a
Static Public Attributes
constexpr static uint32_t binds = bindings<A>::mask
constexpr static IRNodeType min_node_type = IRNodeType::Cast
constexpr static IRNodeType max_node_type = IRNodeType::Cast
constexpr static bool canonical = A::canonical
constexpr static bool foldable = false
Detailed Description
template<typename A>
struct Halide::Internal::IRMatcher::CastOp< A >
Definition at line 1973 of file IRMatch.h.
Member Function Documentation
match() [1/2]
template<typename A > template<uint32_t bound> HALIDE_ALWAYS_INLINE bool Halide::Internal::IRMatcher::CastOp< A >::match (const BaseExprNode & e, MatcherState & state) const inline noexcept
Definition at line 1985 of file IRMatch.h.
References Halide::Internal::Cast::_node_type, Halide::Internal::IRMatcher::CastOp< A >::a, Halide::Expr::get(), Halide::Internal::IRMatcher::CastOp< A >::t, and Halide::Internal::Cast::value.
match() [2/2]
template<typename A > template<uint32_t bound, typename A2 > HALIDE_ALWAYS_INLINE bool Halide::Internal::IRMatcher::CastOp< A >::match (const CastOp< A2 > & op, MatcherState & state) const inline noexcept
Definition at line 1994 of file IRMatch.h.
References Halide::Internal::IRMatcher::CastOp< A >::a, Halide::Internal::IRMatcher::CastOp< A >::t, and Halide::Internal::IRMatcher::unwrap().
make()
template<typename A > HALIDE_ALWAYS_INLINE Expr Halide::Internal::IRMatcher::CastOp< A >::make (MatcherState & state, halide_type_t type_hint) const inline
Definition at line 1999 of file IRMatch.h.
References Halide::Internal::IRMatcher::CastOp< A >::a, Halide::Internal::IRMatcher::cast(), and Halide::Internal::IRMatcher::CastOp< A >::t.
Member Data Documentation
t
template<typename A > Type Halide::Internal::IRMatcher::CastOp< A >::t
Definition at line 1975 of file IRMatch.h.
Referenced by Halide::Internal::IRMatcher::CastOp< A >::make(), Halide::Internal::IRMatcher::CastOp< A >::match(), and Halide::Internal::IRMatcher::operator<<().
a
template<typename A > A Halide::Internal::IRMatcher::CastOp< A >::a
Definition at line 1976 of file IRMatch.h.
Referenced by Halide::Internal::IRMatcher::CastOp< A >::make(), Halide::Internal::IRMatcher::CastOp< A >::match(), and Halide::Internal::IRMatcher::operator<<().
binds
template<typename A > constexpr static uint32_t Halide::Internal::IRMatcher::CastOp< A >::binds = bindings<A>::mask static constexpr
Definition at line 1978 of file IRMatch.h.
min_node_type
template<typename A > constexpr static IRNodeType Halide::Internal::IRMatcher::CastOp< A >::min_node_type = IRNodeType::Cast static constexpr
Definition at line 1980 of file IRMatch.h.
max_node_type
template<typename A > constexpr static IRNodeType Halide::Internal::IRMatcher::CastOp< A >::max_node_type = IRNodeType::Cast static constexpr
Definition at line 1981 of file IRMatch.h.
canonical
template<typename A > constexpr static bool Halide::Internal::IRMatcher::CastOp< A >::canonical = A::canonical static constexpr
Definition at line 1982 of file IRMatch.h.
foldable
template<typename A > constexpr static bool Halide::Internal::IRMatcher::CastOp< A >::foldable = false static constexpr
Definition at line 2003 of file IRMatch.h.
The documentation for this struct was generated from the following file:
/Users/halidenightly/build_bot_new/worker/halide-main-llvm13-x86-64-osx-cmake/halide-source/src/IRMatch.h