Halide: Halide::Internal::IRMatcher::VectorReduceOp< A, B, reduce_op > Struct Template Reference
Halide::Internal::IRMatcher::VectorReduceOp< A, B, reduce_op > Struct Template Reference
#include <IRMatch.h>
Classes
struct pattern_tag
Public Member Functions
template<uint32_t bound>
HALIDE_ALWAYS_INLINE bool match (const BaseExprNode &e, MatcherState &state) const noexcept
template<uint32_t bound, typename A2 , typename B2 , VectorReduce::Operator reduce_op_2>
HALIDE_ALWAYS_INLINE bool match (const VectorReduceOp< A2, B2, reduce_op_2 > &op, MatcherState &state) const noexcept
HALIDE_ALWAYS_INLINE Expr make (MatcherState &state, halide_type_t type_hint) const
Public Attributes
A a
B lanes
Static Public Attributes
constexpr static uint32_t binds = bindings<A>::mask
constexpr static IRNodeType min_node_type = IRNodeType::VectorReduce
constexpr static IRNodeType max_node_type = IRNodeType::VectorReduce
constexpr static bool canonical = A::canonical
constexpr static bool foldable = false
Detailed Description
template<typename A, typename B, VectorReduce::Operator reduce_op>
struct Halide::Internal::IRMatcher::VectorReduceOp< A, B, reduce_op >
Definition at line 1811 of file IRMatch.h.
Member Function Documentation
match() [1/2]
template<typename A , typename B , VectorReduce::Operator reduce_op> template<uint32_t bound> HALIDE_ALWAYS_INLINE bool Halide::Internal::IRMatcher::VectorReduceOp< A, B, reduce_op >::match (const BaseExprNode & e, MatcherState & state) const inline noexcept
Definition at line 1823 of file IRMatch.h.
References Halide::Internal::VectorReduce::_node_type, Halide::Internal::IRMatcher::VectorReduceOp< A, B, reduce_op >::a, Halide::Expr::get(), Halide::Internal::IRMatcher::VectorReduceOp< A, B, reduce_op >::lanes, Halide::Type::lanes(), Halide::Internal::VectorReduce::op, Halide::Internal::BaseExprNode::type, and Halide::Internal::VectorReduce::value.
Referenced by Halide::Internal::IRMatcher::VectorReduceOp< A, B, reduce_op >::match().
match() [2/2]
template<typename A , typename B , VectorReduce::Operator reduce_op> template<uint32_t bound, typename A2 , typename B2 , VectorReduce::Operator reduce_op_2> HALIDE_ALWAYS_INLINE bool Halide::Internal::IRMatcher::VectorReduceOp< A, B, reduce_op >::match (const VectorReduceOp< A2, B2, reduce_op_2 > & op, MatcherState & state) const inline noexcept
Definition at line 1836 of file IRMatch.h.
References Halide::Internal::IRMatcher::VectorReduceOp< A, B, reduce_op >::a, Halide::Internal::IRMatcher::VectorReduceOp< A, B, reduce_op >::lanes, Halide::Internal::IRMatcher::VectorReduceOp< A, B, reduce_op >::match(), and Halide::Internal::IRMatcher::unwrap().
make()
template<typename A , typename B , VectorReduce::Operator reduce_op> HALIDE_ALWAYS_INLINE Expr Halide::Internal::IRMatcher::VectorReduceOp< A, B, reduce_op >::make (MatcherState & state, halide_type_t type_hint) const inline
Definition at line 1843 of file IRMatch.h.
References Halide::Internal::IRMatcher::VectorReduceOp< A, B, reduce_op >::a, halide_scalar_value_t::i64, Halide::Internal::IRMatcher::VectorReduceOp< A, B, reduce_op >::lanes, Halide::Internal::VectorReduce::make(), and halide_scalar_value_t::u.
Member Data Documentation
a
template<typename A , typename B , VectorReduce::Operator reduce_op> A Halide::Internal::IRMatcher::VectorReduceOp< A, B, reduce_op >::a
Definition at line 1813 of file IRMatch.h.
Referenced by Halide::Internal::IRMatcher::VectorReduceOp< A, B, reduce_op >::make(), Halide::Internal::IRMatcher::VectorReduceOp< A, B, reduce_op >::match(), and Halide::Internal::IRMatcher::operator<<().
lanes
template<typename A , typename B , VectorReduce::Operator reduce_op> B Halide::Internal::IRMatcher::VectorReduceOp< A, B, reduce_op >::lanes
Definition at line 1814 of file IRMatch.h.
Referenced by Halide::Internal::IRMatcher::VectorReduceOp< A, B, reduce_op >::make(), Halide::Internal::IRMatcher::VectorReduceOp< A, B, reduce_op >::match(), and Halide::Internal::IRMatcher::operator<<().
binds
template<typename A , typename B , VectorReduce::Operator reduce_op> constexpr static uint32_t Halide::Internal::IRMatcher::VectorReduceOp< A, B, reduce_op >::binds = bindings<A>::mask static constexpr
Definition at line 1816 of file IRMatch.h.
min_node_type
template<typename A , typename B , VectorReduce::Operator reduce_op> constexpr static IRNodeType Halide::Internal::IRMatcher::VectorReduceOp< A, B, reduce_op >::min_node_type = IRNodeType::VectorReduce static constexpr
Definition at line 1818 of file IRMatch.h.
max_node_type
template<typename A , typename B , VectorReduce::Operator reduce_op> constexpr static IRNodeType Halide::Internal::IRMatcher::VectorReduceOp< A, B, reduce_op >::max_node_type = IRNodeType::VectorReduce static constexpr
Definition at line 1819 of file IRMatch.h.
canonical
template<typename A , typename B , VectorReduce::Operator reduce_op> constexpr static bool Halide::Internal::IRMatcher::VectorReduceOp< A, B, reduce_op >::canonical = A::canonical static constexpr
Definition at line 1820 of file IRMatch.h.
foldable
template<typename A , typename B , VectorReduce::Operator reduce_op> constexpr static bool Halide::Internal::IRMatcher::VectorReduceOp< A, B, reduce_op >::foldable = false static constexpr
Definition at line 1851 of file IRMatch.h.
The documentation for this struct was generated from the following file:
/Users/halidenightly/build_bot_new/worker/halide-main-llvm13-x86-64-osx-cmake/halide-source/src/IRMatch.h