Halide: Halide::Internal::Autoscheduler::BoundContents Struct Reference
Halide::Internal::Autoscheduler::BoundContents Struct Reference
#include <FunctionDAG.h>
Classes
class Layout
Public Member Functions
Span * data () const
Span & region_required (int i)
Span & region_computed (int i)
Span & loops (int i, int j)
const Span & region_required (int i) const
const Span & region_computed (int i) const
const Span & loops (int i, int j) const
BoundContents * make_copy () const
void validate () const
Public Attributes
RefCount ref_count
const Layout * layout = nullptr
Detailed Description
Definition at line 273 of file FunctionDAG.h.
Member Function Documentation
data()
Span* Halide::Internal::Autoscheduler::BoundContents::data () const inline
Definition at line 279 of file FunctionDAG.h.
Referenced by loops(), make_copy(), region_computed(), and region_required().
region_required() [1/2]
Span& Halide::Internal::Autoscheduler::BoundContents::region_required (int i) inline
Definition at line 284 of file FunctionDAG.h.
References data().
region_computed() [1/2]
Span& Halide::Internal::Autoscheduler::BoundContents::region_computed (int i) inline
Definition at line 288 of file FunctionDAG.h.
References Halide::Internal::Autoscheduler::BoundContents::Layout::computed_offset, data(), and layout.
loops() [1/2]
Span& Halide::Internal::Autoscheduler::BoundContents::loops (int i, int j) inline
Definition at line 292 of file FunctionDAG.h.
References data(), layout, and Halide::Internal::Autoscheduler::BoundContents::Layout::loop_offset.
region_required() [2/2]
const Span& Halide::Internal::Autoscheduler::BoundContents::region_required (int i) const inline
Definition at line 296 of file FunctionDAG.h.
References data().
region_computed() [2/2]
const Span& Halide::Internal::Autoscheduler::BoundContents::region_computed (int i) const inline
Definition at line 300 of file FunctionDAG.h.
References Halide::Internal::Autoscheduler::BoundContents::Layout::computed_offset, data(), and layout.
loops() [2/2]
const Span& Halide::Internal::Autoscheduler::BoundContents::loops (int i, int j) const inline
Definition at line 304 of file FunctionDAG.h.
References data(), layout, and Halide::Internal::Autoscheduler::BoundContents::Layout::loop_offset.
make_copy()
BoundContents* Halide::Internal::Autoscheduler::BoundContents::make_copy () const inline
Definition at line 308 of file FunctionDAG.h.
References data(), layout, Halide::Internal::Autoscheduler::BoundContents::Layout::make(), memcpy(), and Halide::Internal::Autoscheduler::BoundContents::Layout::total_size.
validate()
void Halide::Internal::Autoscheduler::BoundContents::validate () const
Member Data Documentation
ref_count
RefCount Halide::Internal::Autoscheduler::BoundContents::ref_count mutable
Definition at line 274 of file FunctionDAG.h.
layout
const Layout* Halide::Internal::Autoscheduler::BoundContents::layout = nullptr
Definition at line 277 of file FunctionDAG.h.
Referenced by loops(), make_copy(), and region_computed().
The documentation for this struct was generated from the following file:
/Users/halidenightly/build_bot_new/worker/halide-main-llvm13-x86-64-osx-cmake/halide-source/src/autoschedulers/adams2019/FunctionDAG.h